packages/teleport/src/cluster/components/Nodes/Nodes.tsx
packages/teleport/src/cluster/components/Nodes/__snapshots__/Nodes.story.test.tsx.snap
packages/teleport/src/components/QuickLaunch/QuickLaunch.jsx
packages/teleport/src/dashboard/components/Clusters/ClusterList/ClusterList.tsx
packages/teleport/src/dashboard/components/Clusters/__snapshots__/Clusters.story.test.tsx.snap

This PR adds Terminal Button to the Cluster list.

Add Open Terminal Button to the Cluster List

---

packages/shared/hooks/useAttemptNext.ts
packages/teleport/src/dashboard/People/Users/UserAddEdit/useDialog.tsx
packages/teleport/src/dashboard/People/Users/UserList/UserList.tsx
packages/teleport/src/dashboard/People/Users/Users.story.tsx
packages/teleport/src/dashboard/features/featurePeople.ts
packages/teleport/src/dashboard/features/featureSettings.ts

This PR fixes several bugs around handling of feature flags (users/roles/settings)

Fix handling of feature flags

---

.drone.yml

Adds a sample `.drone.yml` file for automatically running tests and building artifacts on PRs/pushes.

Add initial .drone.yml

---

packages/shared/components/ButtonSso/ButtonSso.test.tsx
packages/shared/components/ButtonSso/ButtonSso.tsx
packages/shared/components/FormLogin/FormLogin.story.tsx
packages/shared/components/FormLogin/__snapshots__/FormLogin.story.test.tsx.snap

fixes https://github.com/gravitational/teleport/issues/4525
- updated testing values to mimic bug (break tests)
- lowercased to be compared values, to fix broken tests

[teleport] Fix case sensitive testing for sso providers

---

packages/teleport/src/Nodes/NodeAdd/ByScript.tsx
packages/teleport/src/Nodes/NodeAdd/NodeAdd.story.tsx
packages/teleport/src/Nodes/NodeAdd/NodeAdd.tsx
packages/teleport/src/Nodes/NodeAdd/NodeAddEnterprise.tsx
packages/teleport/src/Nodes/NodeAdd/__snapshots__/NodeAdd.story.test.tsx.snap
packages/teleport/src/Nodes/NodeAdd/useNodeAdd.ts
packages/teleport/src/services/nodes/makeNodeJoinToken.ts
packages/teleport/src/services/nodes/types.ts

To reflect the changes made in backend: https://github.com/gravitational/teleport.e/pull/165#discussion_r504823440
Display 4 hours intead of 4h0m0s format

Change expires prop to expiry

---

packages/teleport/src/Apps/AppList/AppList.tsx
packages/teleport/src/Apps/Apps.story.tsx
packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
packages/teleport/src/Apps/fixtures/index.ts
packages/teleport/src/AuthConnectors/EmptyList/EmptyList.tsx
packages/teleport/src/Clusters/ClusterList/ClusterList.tsx
packages/teleport/src/Console/components/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
packages/teleport/src/Main/Main.story.tsx
packages/teleport/src/Main/fixtures/index.ts
packages/teleport/src/Nodes/Nodes.tsx
packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
packages/teleport/src/Sessions/SessionList/SessionList.tsx
packages/teleport/src/components/QuickLaunch/QuickLaunch.jsx
packages/teleport/src/features.ts
packages/teleport/src/services/audit/audit.ts
packages/teleport/src/services/user/makeAcl.ts
packages/teleport/src/services/user/types.ts
packages/teleport/src/stores/storeUserContext.ts
packages/teleport/src/teleportContext.ts

This PR removes empty state from nodes list. This change is temporary as the empty state indicates: 1 cluster + 0 server. 
It also adds missing ACL for the appServers.
It also adds a few css changes to the ssh input box.

Remove empty state from NodesList

---

packages/teleport/src/Nodes/NodeAdd/useNodeAdd.ts

resolves https://github.com/gravitational/webapps/issues/177
Add `-f` flag to curl command

Add -f flag to curl command

---

packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
packages/teleport/src/Apps/AddApp/__snapshots__/AddApp.story.test.tsx.snap
packages/teleport/src/Nodes/AddNode/Manually/Manually.tsx
packages/teleport/src/Nodes/AddNode/__snapshots__/AddNode.story.test.tsx.snap
packages/teleport/src/Users/UserTokenLink/UserTokenLink.tsx
packages/teleport/src/components/TextSelectCopy/TextSelectCopy.story.test.tsx
packages/teleport/src/components/TextSelectCopy/TextSelectCopy.story.tsx
packages/teleport/src/components/TextSelectCopy/TextSelectCopy.tsx
packages/teleport/src/components/TextSelectCopy/__snapshots__/TextSelectCopy.story.test.tsx.snap

resolves https://github.com/gravitational/webapps/issues/187#event-3976022264
- Add a bash field to TextSelectCopy component to determine if a `$` needs to be concatenated
- Update test
After chagnes:

Auto add $ sign during render with bash text

---

packages/teleport/src/Apps/AddApp/AddApp.tsx
packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
packages/teleport/src/Apps/AddApp/__snapshots__/AddApp.story.test.tsx.snap
packages/teleport/src/Apps/useApps.ts
packages/teleport/src/Console/DocumentSsh/ShareSession/ShareSession.tsx
packages/teleport/src/Nodes/Nodes.story.tsx
packages/teleport/src/Nodes/Nodes.tsx
packages/teleport/src/Nodes/useNodes.ts

resolves https://github.com/gravitational/webapps/issues/194
- ShareSession closes on esc key down
- Uncomment Add App tabs
- Removed use of attempt.run on node/app dialogues

Minor improvements to dialogs

---

packages/teleport/src/Apps/AddApp/AddApp.tsx
packages/teleport/src/Apps/AddApp/Automatically/Automatically.tsx
packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
packages/teleport/src/Apps/AddApp/__snapshots__/AddApp.story.test.tsx.snap
packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx
packages/teleport/src/Main/Main.story.tsx
packages/teleport/src/Nodes/AddNode/AddNode.story.tsx
packages/teleport/src/Nodes/AddNode/Automatically/Automatically.tsx
packages/teleport/src/Nodes/AddNode/Manually/Manually.tsx
packages/teleport/src/Nodes/AddNode/__snapshots__/AddNode.story.test.tsx.snap
packages/teleport/src/Nodes/AddNode/useAddNode.ts
packages/teleport/src/services/nodes/nodes.ts

This PR fixes a few bugs with invalid instructions on the manual steps of the add node and app dialogs.

Fix instructions for Manual steps

---

packages/teleport/src/Apps/AddApp/AddApp.story.tsx
packages/teleport/src/Apps/AddApp/AddApp.tsx
packages/teleport/src/Apps/AddApp/Automatically/Automatically.tsx
packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
packages/teleport/src/Apps/AddApp/__snapshots__/AddApp.story.test.tsx.snap
packages/teleport/src/Apps/AddApp/useAddApp.ts
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Console/DocumentSsh/ActionBar/ActionBar.tsx
packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx
packages/teleport/src/Console/DocumentSsh/ShareSession/ShareSession.tsx
packages/teleport/src/Console/DocumentSsh/useSshSession.ts
packages/teleport/src/Nodes/AddNode/AddNode.story.tsx
packages/teleport/src/Nodes/AddNode/AddNode.tsx
packages/teleport/src/Nodes/AddNode/Manually/Manually.tsx
packages/teleport/src/Nodes/AddNode/__snapshots__/AddNode.story.test.tsx.snap
packages/teleport/src/Nodes/AddNode/useAddNode.ts
packages/teleport/src/Recordings/__snapshots__/Recordings.story.test.tsx.snap
packages/teleport/src/Users/UserReset/__snapshots__/UserReset.story.test.tsx.snap
packages/teleport/src/Users/UserTokenLink/__snapshots__/UserTokenLink.story.test.tsx.snap
packages/teleport/src/components/TextSelectCopy/TextSelectCopy.tsx
packages/teleport/src/components/TextSelectCopy/__snapshots__/TextSelectCopy.story.test.tsx.snap
packages/teleport/src/useAuditEvents.ts

This PR fixes some of the manual steps:
1) Ensures there is a default port 443 specified so teleport does not use 3080
2) Populates local user parameter name --user
3) Removed Share Session dialog (after talking to Ben)
4) Css changes to the CmdTextComponent (script text should not break)
5) Changes efault Date Range value from 7 days back to 1 day.

Fix manual steps and remove share session dialog

---

packages/design/src/DataTable/Table.story.js
packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
packages/teleport/src/Apps/ButtonAdd.tsx
packages/teleport/src/Nodes/ButtonAdd.tsx
packages/teleport/src/Roles/Roles.tsx
packages/teleport/src/Support/Support.tsx
packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
packages/teleport/src/TrustedClusters/TrustedClusters.tsx

Was cleaning up some Gravitational references, if this isn't helpful please close and use as inspiration.  I didn't change Gravity URLs

Update links to https://goteleport.com

---

packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts

@alex-kovoy @kimlisa Added new database access audit events, PTAL.

Add database access audit events

---

packages/shared/libs/stores/useStore.ts
packages/teleport/src/AuthConnectors/templates/github.yaml
packages/teleport/src/Main/Main.story.tsx
packages/teleport/src/Main/fixtures/index.ts
packages/teleport/src/Support/Support.story.tsx
packages/teleport/src/components/Authenticated/Authenticated.jsx
packages/teleport/src/config.ts
packages/teleport/src/services/clusters/makeCluster.ts
packages/teleport/src/services/localStorage/localStorage.ts
packages/teleport/src/services/localStorage/types.ts
packages/teleport/src/services/user/makeAcl.ts
packages/teleport/src/services/user/makeUser.ts
packages/teleport/src/services/user/makeUserContext.ts
packages/teleport/src/services/user/types.ts
packages/teleport/src/services/user/user.test.ts
packages/teleport/src/stores/storeUserContext.ts
packages/teleport/src/teleportContext.tsx

redo of https://github.com/gravitational/webapps/pull/203
- Remove enterprise features: workflow routes, config, access request session storage
- Set/Check AccessRequest access perms
- Set Roles Requestable for UserContext

Define workflow access perms and roles requestable

---

packages/teleport/src/Roles/Roles.tsx
packages/teleport/src/TrustedClusters/TrustedClusters.tsx

Tiny grammar fix

---

packages/teleport/src/Apps/AddApp/Automatically/Automatically.tsx

Frontend counterpart to https://github.com/gravitational/teleport.e/pull/201

Add app URI validation regexp to match backend logic

---

packages/teleport/src/Apps/AddApp/Automatically/Automatically.tsx

Backports #227 into `teleport-5.0`

[5.0] Backport "Add app URI validation regexp to match backend logic (#227)"

---

packages/shared/components/TextEditor/TextEditor.jsx
packages/teleport/src/AuthConnectors/DeleteConnectorDialog/DeleteConnectorDialog.tsx
packages/teleport/src/Roles/DeleteRole/DeleteRole.tsx
packages/teleport/src/TrustedClusters/DeleteTrust/DeleteTrust.tsx
packages/teleport/src/Users/UserDelete/UserDelete.tsx
packages/teleport/src/Users/UserDelete/__snapshots__/UserDelete.story.test.tsx.snap

Backport(v6): Fix cn dialog err handling and disable ace web workers

---

packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Audit/fixtures/index.ts
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts

Support for mfa.add and mfa.delete events.

Handle new MFA audit events

---

packages/teleport/src/Support/Support.tsx
packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap

Updated to reflect new github community and updates feedback email to be captured by Zendesk

Update link to github discussion

---

packages/design/src/DataTable/Table.jsx
packages/design/src/ThemeProvider/globals.js
packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Clusters/__snapshots__/Clusters.story.test.tsx.snap
packages/teleport/src/Main/fixtures/index.ts
packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
packages/teleport/src/Recordings/__snapshots__/Recordings.story.test.tsx.snap
packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
packages/teleport/src/Support/Support.story.tsx
packages/teleport/src/Support/Support.tsx
packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
packages/teleport/src/Users/__snapshots__/Users.story.test.tsx.snap
packages/teleport/src/components/Layout/Layout.jsx
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts
packages/teleport/src/services/user/makeUserContext.ts
packages/teleport/src/services/user/types.ts
packages/teleport/src/services/user/user.test.ts
packages/teleport/src/stores/storeUserContext.ts

- update user context: grouped `suggestedReviewers` and `requestableRoles` under new type `AccessCapabilities` (similar to backend)
- allow table td element to use title attribute, this was needed to allow on hover to display full text on shortened access request reasons
- replace `flex-shrink:0` with `white-space: nowrap` and update snapshots
- add global font setting for html element textarea
- add access request review event

Add more fields to user context

---

packages/build/webpack/webpack.base.js
packages/design/src/DataTable/StyledTable.jsx
packages/shared/components/Select/types.ts
packages/shared/services/loc/index.ts
packages/shared/services/loc/loc.ts
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Clusters/__snapshots__/Clusters.story.test.tsx.snap
packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
packages/teleport/src/Main/fixtures/index.ts
packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
packages/teleport/src/Recordings/__snapshots__/Recordings.story.test.tsx.snap
packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
packages/teleport/src/Support/index.ts
packages/teleport/src/Users/__snapshots__/Users.story.test.tsx.snap
yarn.lock

part of https://github.com/gravitational/cloud/issues/511
Type and style tweaks and add unix display date

Type and style tweaks and add unix display date

---

packages/build/webpack/webpack.base.js
packages/design/src/DataTable/StyledTable.jsx
packages/shared/components/Select/types.ts
packages/shared/services/loc/index.ts
packages/shared/services/loc/loc.ts
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Clusters/__snapshots__/Clusters.story.test.tsx.snap
packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
packages/teleport/src/Main/fixtures/index.ts
packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
packages/teleport/src/Recordings/__snapshots__/Recordings.story.test.tsx.snap
packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
packages/teleport/src/Users/__snapshots__/Users.story.test.tsx.snap
yarn.lock

Type and style tweaks and add unix display date 

---

packages/teleport/src/AppLauncher/useAppLauncher.ts
packages/teleport/src/config.ts
packages/teleport/src/services/apps/apps.ts

Backport of https://github.com/gravitational/webapps/pull/284.

[v6] Use dedicated API for app FQDN resolving

---

packages/teleport/src/Apps/AddApp/AddApp.story.test.tsx
packages/teleport/src/Apps/AddApp/AddApp.story.tsx
packages/teleport/src/Apps/AddApp/AddApp.tsx
packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
packages/teleport/src/Apps/AddApp/__snapshots__/AddApp.story.test.tsx.snap
packages/teleport/src/Apps/AddApp/useAddApp.ts
packages/teleport/src/Nodes/AddNode/AddNode.story.test.tsx
packages/teleport/src/Nodes/AddNode/AddNode.story.tsx
packages/teleport/src/Nodes/AddNode/AddNode.tsx
packages/teleport/src/Nodes/AddNode/Manually/Manually.tsx
packages/teleport/src/Nodes/AddNode/__snapshots__/AddNode.story.test.tsx.snap
packages/teleport/src/Nodes/AddNode/useAddNode.ts

fixes https://github.com/gravitational/teleport/issues/6858
- Use `ctx.storeUser.authType` instead of `cfg.authType` (which is the type defined in teleport.yaml) to determine `tsh login` cmd
- Updated stories and snapshots
Local users:
SSO users:
cc @stevenGravy

Fix manual tsh login commands for apps and nodes

---

packages/teleport/src/Apps/AddApp/AddApp.story.test.tsx
packages/teleport/src/Apps/AddApp/AddApp.story.tsx
packages/teleport/src/Apps/AddApp/AddApp.tsx
packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
packages/teleport/src/Apps/AddApp/__snapshots__/AddApp.story.test.tsx.snap
packages/teleport/src/Apps/AddApp/useAddApp.ts
packages/teleport/src/Nodes/AddNode/AddNode.story.test.tsx
packages/teleport/src/Nodes/AddNode/AddNode.story.tsx
packages/teleport/src/Nodes/AddNode/AddNode.tsx
packages/teleport/src/Nodes/AddNode/Manually/Manually.tsx
packages/teleport/src/Nodes/AddNode/__snapshots__/AddNode.story.test.tsx.snap
packages/teleport/src/Nodes/AddNode/useAddNode.ts

Backport v6.1

---

packages/teleport/src/Apps/AddApp/AddApp.story.test.tsx
packages/teleport/src/Apps/AddApp/AddApp.story.tsx
packages/teleport/src/Apps/AddApp/AddApp.tsx
packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
packages/teleport/src/Apps/AddApp/__snapshots__/AddApp.story.test.tsx.snap
packages/teleport/src/Apps/AddApp/useAddApp.ts
packages/teleport/src/Nodes/AddNode/AddNode.story.test.tsx
packages/teleport/src/Nodes/AddNode/AddNode.story.tsx
packages/teleport/src/Nodes/AddNode/AddNode.tsx
packages/teleport/src/Nodes/AddNode/Manually/Manually.tsx
packages/teleport/src/Nodes/AddNode/__snapshots__/AddNode.story.test.tsx.snap
packages/teleport/src/Nodes/AddNode/useAddNode.ts
packages/teleport/src/services/session/session.ts

Backports to v6

---

packages/teleport/src/AuthConnectors/DeleteConnectorDialog/DeleteConnectorDialog.tsx
packages/teleport/src/Clusters/ClusterList/ClusterList.tsx
packages/teleport/src/Clusters/Clusters.tsx
packages/teleport/src/Clusters/useClusters.ts
packages/teleport/src/Roles/DeleteRole/DeleteRole.tsx
packages/teleport/src/TrustedClusters/DeleteTrust/DeleteTrust.tsx
packages/teleport/src/Users/UserDelete/UserDelete.tsx
packages/teleport/src/Users/UserDelete/__snapshots__/UserDelete.story.test.tsx.snap

- backport of #323 
- update e-ref on switchback banner fix

[backport v6] add db/kube to cluster list action menu and update-e-ref

---

packages/teleport/src/Audit/EventList/EventList.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Users/UserReset/UserReset.story.test.tsx
packages/teleport/src/Users/UserReset/UserReset.story.tsx
packages/teleport/src/Users/UserReset/__snapshots__/UserReset.story.test.tsx.snap
packages/teleport/src/Users/UserTokenLink/UserTokenLink.story.test.tsx
packages/teleport/src/Users/UserTokenLink/UserTokenLink.story.tsx
packages/teleport/src/Users/UserTokenLink/UserTokenLink.tsx
packages/teleport/src/Users/UserTokenLink/__snapshots__/UserTokenLink.story.test.tsx.snap

- Reverts event list sorting back to original (latest to oldest)
- Tests were breaking b/c some test with dates were time sensitive (my mistake), so i locked the dates

Revert events list sorting back to original

---

packages/teleport/src/Audit/EventList/EventList.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Users/UserReset/UserReset.story.test.tsx
packages/teleport/src/Users/UserReset/UserReset.story.tsx
packages/teleport/src/Users/UserReset/__snapshots__/UserReset.story.test.tsx.snap
packages/teleport/src/Users/UserTokenLink/UserTokenLink.story.test.tsx
packages/teleport/src/Users/UserTokenLink/UserTokenLink.story.tsx
packages/teleport/src/Users/UserTokenLink/UserTokenLink.tsx
packages/teleport/src/Users/UserTokenLink/__snapshots__/UserTokenLink.story.test.tsx.snap

Revert events list sorting back to original (latest to oldest) 

---

packages/teleport/src/Audit/EventList/EventList.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Users/UserReset/UserReset.story.test.tsx
packages/teleport/src/Users/UserReset/UserReset.story.tsx
packages/teleport/src/Users/UserReset/__snapshots__/UserReset.story.test.tsx.snap
packages/teleport/src/Users/UserTokenLink/UserTokenLink.story.test.tsx
packages/teleport/src/Users/UserTokenLink/UserTokenLink.story.tsx
packages/teleport/src/Users/UserTokenLink/UserTokenLink.tsx
packages/teleport/src/Users/UserTokenLink/__snapshots__/UserTokenLink.story.test.tsx.snap

Revert events list sorting back to original (latest to oldest)

---

packages/teleport/src/AppLauncher/useAppLauncher.ts
packages/teleport/src/Apps/AppList/AppList.tsx
packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap

- Decode the `arn` in the URL before setting the `awsrole` url search param, as this was causing an issue where it would be encoded twice
- Keep the yellow-ish color consistent for all AWS Console Apps
- Revert sorting order

AWS Console Access Tweaks

---

packages/teleport/src/AppLauncher/useAppLauncher.ts
packages/teleport/src/Apps/AppList/AppList.tsx
packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap

[forward-port] AWS Console Access Tweaks

---

packages/teleport/src/DesktopSession/DesktopSession.story.tsx
packages/teleport/src/DesktopSession/DesktopSession.tsx
packages/teleport/src/DesktopSession/TdpClientCanvas.tsx
packages/teleport/src/DesktopSession/useDesktopSession.tsx
packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
packages/teleport/src/lib/tdp/client.ts

Adds mouse and keyboard functionality, refactors DesktopSession state management.

Mouse and keyboard functionality

---

packages/teleport/src/services/auth/auth.js

v7 backport for https://github.com/gravitational/webapps/pull/389

[Backport v7] Add support for unicode passwords

---

packages/teleport/src/Desktops/Desktops.story.tsx
packages/teleport/src/Desktops/Desktops.tsx

Adds a storybook and fixes faulty jsx logic

DA Storybook

---

package.json

This PR fixes the following known issue with yarn https://github.com/yarnpkg/yarn/issues/4878

Yarn workspace fails to add local package as dependency

---

packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts

Cherry-pick of https://github.com/gravitational/webapps/pull/371

Add Support for SessionProcessExit event

---

packages/teleport/src/services/auth/auth.ts
packages/teleport/src/services/auth/makeMfa.ts

- Define webauth methods for changing password, login, invite/reset
- Define navigator credetial get/create response makers
https://github.com/gravitational/webapps.e/pull/77

Add webauthn methods to auth service

---

packages/teleport/src/lib/term/enums.js
packages/teleport/src/lib/term/protobuf.js
packages/teleport/src/lib/term/terminal.js
packages/teleport/src/lib/term/tty.js

In response to https://github.com/gravitational/teleport/pull/8642
Note: lots of noise from prettier formatting files, so i suggest reviewing the [second commit](https://github.com/gravitational/webapps/pull/421/commits/3dceb9a7a60c848fb83328c4978abe2501d9ca01)

Add webauthn support to web terminal mfa prompt

---

packages/shared/components/FormPassword/FormPassword.story.tsx
packages/shared/components/FormPassword/FormPassword.test.tsx
packages/shared/components/FormPassword/FormPassword.tsx
packages/shared/components/FormPassword/__snapshots__/FormPassword.test.tsx.snap
packages/teleport/src/Account/Account.tsx
packages/teleport/src/Invite/Invite.story.tsx
packages/teleport/src/Invite/Invite.test.tsx
packages/teleport/src/Invite/Invite.tsx
packages/teleport/src/Invite/__snapshots__/Invite.test.tsx.snap
packages/teleport/src/Invite/useInvite.ts
packages/teleport/src/Login/Login.story.tsx
packages/teleport/src/Login/Login.test.tsx
packages/teleport/src/Login/Login.tsx
packages/teleport/src/Login/__snapshots__/Login.test.tsx.snap
packages/teleport/src/Login/useLogin.ts
packages/teleport/src/components/FormInvite/FormInvite.story.test.tsx
packages/teleport/src/components/FormInvite/FormInvite.story.tsx
packages/teleport/src/components/FormInvite/FormInvite.tsx
packages/teleport/src/components/FormInvite/__snapshots__/FormInvite.story.test.tsx.snap
packages/teleport/src/components/FormLogin/FormLogin.story.test.tsx
packages/teleport/src/components/FormLogin/FormLogin.story.tsx
packages/teleport/src/components/FormLogin/FormLogin.test.tsx
packages/teleport/src/components/FormLogin/FormLogin.tsx
packages/teleport/src/components/FormLogin/__snapshots__/FormLogin.story.test.tsx.snap
packages/teleport/src/services/mfa/makeMfaDevice.ts
packages/teleport/src/services/mfa/utils.test.ts
packages/teleport/src/services/mfa/utils.ts

Adds webauthn to:
- Invite
- Login
- Account change password
https://github.com/gravitational/webapps.e/pull/79
Note test is breaking b/c it requires the changes in enterprise

Add webauthn options to forms

---

packages/teleport/src/Desktops/DesktopList/DesktopList.tsx

Adds an address column to the Desktop List table

adding name column

---

packages/teleport/src/Console/DocumentSsh/AuthnDialog/AuthnDialog.story.tsx
packages/teleport/src/Console/DocumentSsh/AuthnDialog/AuthnDialog.tsx
packages/teleport/src/Console/DocumentSsh/AuthnDialog/index.ts
packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx
packages/teleport/src/Console/DocumentSsh/useSshSession.ts
packages/teleport/src/Console/DocumentSsh/useWebauthn.ts
packages/teleport/src/lib/term/terminal.js

[backport v8] Bug fix: Show a authentication dialog for web terminal (#452)

---

packages/shared/components/Select/types.ts
packages/teleport/src/components/SelectFilter/SelectFilter.story.tsx
packages/teleport/src/components/SelectFilter/SelectFilter.tsx
packages/teleport/src/components/SelectFilter/index.ts

part of https://github.com/gravitational/teleport/issues/5021
opened
with labels

Create a general select filter component

---

packages/teleport/src/DesktopSession/TdpClientCanvas/useTdpClientCanvas.tsx
packages/teleport/src/DesktopSession/useDesktopSession.tsx
packages/teleport/src/Desktops/DesktopList/DesktopList.tsx
packages/teleport/src/Desktops/DesktopList/index.ts
packages/teleport/src/Desktops/Desktops.story.tsx
packages/teleport/src/Desktops/useDesktops.ts
packages/teleport/src/config.ts
packages/teleport/src/services/desktops/desktops.ts

fixes https://github.com/gravitational/teleport/issues/8854

"clusterId • username@hostname" document title

---

packages/build/index.ejs
packages/teleport/src/Invite/CardWelcome.tsx
packages/teleport/src/Invite/Invite.story.tsx
packages/teleport/src/Invite/Invite.test.tsx
packages/teleport/src/Invite/Invite.tsx
packages/teleport/src/config.ts

v8 backport of https://github.com/gravitational/webapps/pull/479

[backport v8] Add prompt prior to Invite and Reset

---

packages/teleport/src/Invite/CardWelcome.tsx
packages/teleport/src/Invite/Invite.jsx
packages/teleport/src/Teleport.tsx

Alternate implementation of https://github.com/gravitational/webapps/pull/487

Fix TOTP Fetch Hook (alt)

---

.storybook/main.js
packages/build/.eslintrc.js
packages/build/webpack/webpack.base.js
packages/build/webpack/webpack.dev.config.js
packages/build/webpack/webpack.prod.config.js
packages/design/package.json
packages/design/src/.storybook/webpack.config.js
packages/teleport/webpack.dev.config.js
packages/teleport/webpack.prod.config.js

- created separated fields for each config part in `webpack.base.js` to indicate that this file doesn't contain a valid Webpack config
- added TS annotations to enable code completion

webpack configs cleanup

---

packages/teleterm/package.json
packages/teleterm/src/ui/App.tsx
packages/teleterm/src/ui/TabHost/TabHost.tsx
packages/teleterm/src/ui/Tabs/TabItem.tsx
packages/teleterm/src/ui/Tabs/Tabs.tsx
packages/teleterm/src/ui/Tabs/useTabDnD.ts
packages/teleterm/src/ui/services/docs/docs.ts
yarn.lock

Arrange the cards evenly depending on the available space

---

packages/build/.eslintrc.js

Jest rules configuration should be placed in test overrides, otherwise is is omitted

Move jest rules to test overrides

---

packages/build/modules/raw-loader.d.ts
packages/teleport/src/AuthConnectors/templates/index.ts
packages/teleport/src/Roles/templates/index.ts
packages/teleport/src/TrustedClusters/templates/index.ts

Fixes the breaking bug that prevents users from being able to add new roles, auth connectors, and trusted clusters.

Fix YAML template imports

---

packages/teleterm/src/mainProcess/clusterContextMenu.ts
packages/teleterm/src/mainProcess/fixtures/mocks.ts
packages/teleterm/src/mainProcess/mainProcess.ts
packages/teleterm/src/mainProcess/mainProcessClient.ts
packages/teleterm/src/mainProcess/types.ts
packages/teleterm/src/preload.ts
packages/teleterm/src/services/tshd/fixtures/mocks.ts
packages/teleterm/src/ui/ClusterRemove/ClusterRemove.tsx
packages/teleterm/src/ui/ClusterRemove/index.ts
packages/teleterm/src/ui/ClusterRemove/useClusterRemove.ts
packages/teleterm/src/ui/ModalsHost/ModalsHost.tsx
packages/teleterm/src/ui/Navigator/Expander.tsx
packages/teleterm/src/ui/Navigator/ExpanderClusters/ExpanderClusters.tsx
packages/teleterm/src/ui/Navigator/ExpanderClusters/useExpanderClusters.ts
packages/teleterm/src/ui/services/clusters/clusters.ts
packages/teleterm/src/ui/services/modals/modals.ts

Closes #471
* Added context menu for clusters 
* Added new dialog to remove cluster

Add context menu to clusters

---

packages/build/devserver/modifyResponse.js

The latest version of htmlWebpackPlugin automatically compresses the index html file.  Below change fixes the dev-server which failed to extract the csrf and bearer tokens from html because of week regex parsing that could not match the tokens in compressed html file.

Fix devServer csrf and berear token handling

---

packages/teleport/src/Console/DocumentNodes/DocumentNodes.tsx
packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
packages/teleport/src/Console/DocumentNodes/useNodes.ts
packages/teleport/src/Nodes/Nodes.story.tsx
packages/teleport/src/Nodes/Nodes.test.tsx
packages/teleport/src/Nodes/Nodes.tsx
packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
packages/teleport/src/Nodes/useNodes.ts
packages/teleport/src/components/NodeList/NodeList.tsx

Part of #523 
Switches NodeList to using Table V2

Update NodeList to use Table V2

---

packages/teleport/src/Databases/DatabaseList/DatabaseList.test.tsx
packages/teleport/src/Databases/DatabaseList/DatabaseList.tsx
packages/teleport/src/Databases/Databases.story.tsx
packages/teleport/src/Databases/Databases.tsx
packages/teleport/src/Databases/__snapshots__/Databases.story.test.tsx.snap
packages/teleport/src/Databases/useDatabases.ts

Part of #523 
Updates DatabaseList to use Table V2

Update DatabaseList to use TableV2

---

packages/teleport/src/Kubes/KubeList/KubeList.test.tsx
packages/teleport/src/Kubes/KubeList/KubeList.tsx
packages/teleport/src/Kubes/Kubes.story.tsx
packages/teleport/src/Kubes/Kubes.tsx
packages/teleport/src/Kubes/__snapshots__/Kubes.story.test.tsx.snap
packages/teleport/src/Kubes/useKubes.ts

Part of #523 
Updates KubeList to use Table V2

Update KubeList to use TableV2

---

packages/teleport/src/Desktops/DesktopList/DesktopList.test.tsx
packages/teleport/src/Desktops/DesktopList/DesktopList.tsx
packages/teleport/src/Desktops/Desktops.story.tsx
packages/teleport/src/Desktops/Desktops.tsx
packages/teleport/src/Desktops/useDesktops.ts

Part of #523 
Updates DesktopList to use Table V2
Adds a unit test for the table.

Update DesktopList to use TableV2

---

packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Audit/fixtures/index.ts
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts

Subordinate to https://github.com/gravitational/teleport/pull/9552

Add the `access_request.delete` event

---

packages/teleport/src/Apps/AppList/AppList.test.tsx
packages/teleport/src/Apps/AppList/AppList.tsx
packages/teleport/src/Apps/Apps.story.tsx
packages/teleport/src/Apps/Apps.tsx
packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
packages/teleport/src/Apps/useApps.ts

Part of #523
Updates AppList to use Table V2

Update AppList to use TableV2

---

packages/design/src/DataTableNext/DataTableNext.story.tsx
packages/design/src/DataTableNext/Pager/usePager.ts
packages/design/src/DataTableNext/Table.tsx
packages/design/src/DataTableNext/types.ts
packages/design/src/DataTableNext/useTable.ts
packages/teleport/src/Audit/Audit.story.test.tsx
packages/teleport/src/Audit/Audit.story.tsx
packages/teleport/src/Audit/Audit.tsx
packages/teleport/src/Audit/EventList/EventList.tsx
packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Audit/useAuditEvents.ts
packages/teleport/src/Desktops/DesktopList/DesktopList.tsx
packages/teleport/src/services/audit/audit.ts

Part of #523 
Update EventList to Table V2

Update EventList to TableV2

---

packages/teleport/src/Apps/AppList/AwsLaunchButton/AwsLaunchButton.tsx
packages/teleport/src/Users/UserList/UserList.tsx
packages/teleport/src/Users/Users.tsx
packages/teleport/src/Users/__snapshots__/Users.story.test.tsx.snap

Part of #523
Updates UserList to use TableV2

Update UserList to TableV2

---

packages/teleport/src/Roles/RoleList/RoleList.tsx

Part of #523
Updates RoleList to TableV2

Update RoleList to TableV2

---

packages/design/src/DataTableNext/types.ts
packages/design/src/DataTableNext/useTable.ts
packages/teleport/src/Clusters/ClusterList/ClusterList.tsx
packages/teleport/src/Clusters/Clusters.tsx
packages/teleport/src/Clusters/__snapshots__/Clusters.story.test.tsx.snap
packages/teleport/src/Clusters/useClusters.ts

Part of #523 
Updates ClusterList to use TableV2
Adds an optional `showFirst` field to table config to tell the table which item to show first.

Update ClusterList to TableV2

---

packages/teleport/src/Recordings/Recordings.tsx
packages/teleport/src/Recordings/RecordingsList.tsx
packages/teleport/src/Recordings/__snapshots__/Recordings.story.test.tsx.snap
packages/teleport/src/Recordings/useRecordings.ts
packages/teleport/src/Roles/RoleList/RoleList.tsx

Part of #523 
Update RecordingList to use TableV2

Update RecordingList to TableV2

---

packages/teleport/src/Account/Account.tsx
packages/teleport/src/Account/ManageDevices/ManageDevices.tsx
packages/teleport/src/Account/ManageDevices/__snapshots__/ManageDevices.story.test.tsx.snap
packages/teleport/src/components/MfaDeviceList/MfaDeviceList.tsx

Part of #523 
Updates MfaDeviceList to use TableV2

Update MfaDeviceList to use TableV2

---

packages/teleport/src/Apps/AppList/AppList.tsx
packages/teleport/src/Audit/EventList/EventList.tsx
packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/Clusters/ClusterList/ClusterList.tsx
packages/teleport/src/Databases/DatabaseList/DatabaseList.tsx
packages/teleport/src/Desktops/DesktopList/DesktopList.tsx
packages/teleport/src/Kubes/KubeList/KubeList.tsx
packages/teleport/src/Sessions/SessionList/DescCell.tsx
packages/teleport/src/Sessions/SessionList/SessionList.tsx
packages/teleport/src/components/NodeList/NodeList.tsx

Cleans up custom cells and their types and makes them easier to read.

Clean up custom cells in Tables

---

packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Audit/fixtures/index.ts
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts

Add x11 forward events (#561)

---

packages/teleport/src/services/clusters/clusters.test.ts
packages/teleport/src/services/clusters/makeCluster.ts

Fixes a typo that was causing a console error and invalid `connectedText`

Fix typo in makeCluster

---

packages/teleterm/src/services/tshd/v1/app_pb.d.ts
packages/teleterm/src/services/tshd/v1/app_pb.js
packages/teleterm/src/services/tshd/v1/database_pb.d.ts
packages/teleterm/src/services/tshd/v1/database_pb.js
packages/teleterm/src/services/tshd/v1/server_pb.d.ts
packages/teleterm/src/services/tshd/v1/server_pb.js
packages/teleterm/src/services/tshd/v1/service_grpc_pb.js
packages/teleterm/src/ui/QuickInput/QuickInputList/QuickInputList.tsx
packages/teleterm/src/ui/ServerConnect/ServerConnect.story.tsx
packages/teleterm/src/ui/services/clusters/clustersService.test.ts

This PR updates `teleterm` proto files (after minor cleanups)

Update teleterm proto files

---

packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Audit/fixtures/index.ts
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts

Subordinate PR to gravitational/teleport#9822

Add the `cert.create` event

---

packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Audit/fixtures/index.ts
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts

[v7] backport #584 (`cert.create` event)

---

packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Audit/fixtures/index.ts
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts

[v8] backport #584 (`cert.create` event)

---

packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Audit/fixtures/index.ts
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts

[v6.2] backport #584 (`cert.create` event)

---

packages/design/src/DataTable/Pager/Pager.tsx
packages/design/src/DataTable/Pager/StyledPager.tsx
packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Clusters/__snapshots__/Clusters.story.test.tsx.snap
packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
packages/teleport/src/Databases/__snapshots__/Databases.story.test.tsx.snap
packages/teleport/src/Kubes/__snapshots__/Kubes.story.test.tsx.snap
packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
packages/teleport/src/Recordings/__snapshots__/Recordings.story.test.tsx.snap
packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
packages/teleport/src/Users/__snapshots__/Users.story.test.tsx.snap

Moves the `Fetch More` button to the right side of the table for improved UX

Move Fetch More Button In Table

---

packages/design/src/DataTable/useTable.ts
packages/design/src/utils/match.ts
packages/teleterm/src/ui/DocumentCluster/ClusterResources/Applications/Applications.tsx
packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/Databases.tsx
packages/teleterm/src/ui/DocumentCluster/ClusterResources/Kubes/Kubes.tsx
packages/teleterm/src/ui/DocumentCluster/ClusterResources/Servers/Servers.tsx
packages/teleterm/src/ui/DocumentCluster/ClusterResources/renderLabelCell.tsx
packages/teleterm/src/ui/LayoutManager.tsx
packages/teleterm/src/ui/TabHost/TabHost.test.tsx
packages/teleterm/src/ui/TabHost/TabHost.tsx
packages/teleterm/src/ui/TabHost/index.ts
packages/teleterm/src/ui/TabHost/useTabShortcuts.ts
packages/teleterm/src/ui/TabHost/useTabSortcuts.test.tsx
packages/teleterm/src/ui/Tabs/TabItem.tsx
packages/teleterm/src/ui/Tabs/Tabs.tsx
packages/teleterm/src/ui/Tabs/index.ts
packages/teleterm/src/ui/fixtures/MockAppContextProvider.tsx
packages/teleterm/src/ui/fixtures/mocks.ts
packages/teleterm/src/ui/services/clusters/clustersService.test.ts
packages/teleterm/src/ui/services/clusters/clustersService.ts
packages/teleterm/src/ui/services/docs/documentsService.test.ts
packages/teleterm/src/ui/services/docs/documentsService.ts
packages/teleterm/src/ui/services/keyboardShortcuts/useKeyboardShortcuts.ts

This PR adds more tests to parts that shouldn't change so much with design changes.

Add more tests to Teleterm

---

packages/teleport/src/Kubes/ConnectDialog/ConnectDialog.story.tsx
packages/teleport/src/Kubes/ConnectDialog/ConnectDialog.tsx
packages/teleport/src/Kubes/ConnectDialog/__snapshots__/ConnectDialog.story.test.tsx.snap
packages/teleport/src/Kubes/KubeList/KubeList.test.tsx
packages/teleport/src/Kubes/KubeList/KubeList.tsx
packages/teleport/src/Kubes/Kubes.tsx

resolves https://github.com/gravitational/teleport/issues/8616

Adds cluster name with the `tsh login` for kube instructions

---

packages/teleport/src/Kubes/ConnectDialog/ConnectDialog.story.tsx
packages/teleport/src/Kubes/ConnectDialog/ConnectDialog.tsx
packages/teleport/src/Kubes/ConnectDialog/__snapshots__/ConnectDialog.story.test.tsx.snap
packages/teleport/src/Kubes/KubeList/KubeList.test.tsx
packages/teleport/src/Kubes/KubeList/KubeList.tsx
packages/teleport/src/Kubes/Kubes.tsx

[backport v9] Add cluster name to `tsh login` for kube instructions (#632)

---

packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx

A less-than-ideal fix for https://github.com/gravitational/teleport/issues/10649. These changes can be reverted once we implement https://github.com/gravitational/teleport/issues/8583, which will send us a signal that the user has fully authenticated, at which point we can begin sharing the clipboard without silent failures.

Fix clipboard-having-an-initial-value bug

---

packages/teleport/src/DesktopSession/DesktopSession.story.tsx
packages/teleport/src/DesktopSession/DesktopSession.tsx
packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
packages/teleport/src/components/TdpClientCanvas/TdpClientCanvas.tsx

fixes https://github.com/gravitational/webapps/issues/626

Fix clipboard sync

---

packages/teleport/src/Apps/Apps.story.test.tsx
packages/teleport/src/Apps/useApps.ts
packages/teleport/src/Console/consoleContext.tsx
packages/teleport/src/Databases/useDatabases.ts
packages/teleport/src/Desktops/useDesktops.ts
packages/teleport/src/Kubes/useKubes.ts
packages/teleport/src/Main/Main.story.tsx
packages/teleport/src/Nodes/useNodes.ts
packages/teleport/src/services/apps/apps.test.ts
packages/teleport/src/services/apps/apps.ts
packages/teleport/src/services/apps/makeApps.ts
packages/teleport/src/services/apps/types.ts
packages/teleport/src/services/databases/databases.test.ts
packages/teleport/src/services/databases/databases.ts
packages/teleport/src/services/databases/types.ts
packages/teleport/src/services/desktops/desktops.test.ts
packages/teleport/src/services/desktops/desktops.ts
packages/teleport/src/services/desktops/types.ts
packages/teleport/src/services/kube/kube.test.ts
packages/teleport/src/services/kube/kube.ts
packages/teleport/src/services/kube/types.ts
packages/teleport/src/services/nodes/makeNode.ts
packages/teleport/src/services/nodes/nodes.test.ts
packages/teleport/src/services/nodes/nodes.ts
packages/teleport/src/services/nodes/types.ts

[backport v9] Edit api response for getXXX (resources) (#622)

---

packages/teleport/src/Roles/templates/role.yaml

[v9] Update default roles template

---

packages/teleport/src/Player/ProgressBar/ProgressBarDesktop.tsx

Adds an interval for smoothing out the progress bar.

smooth out progress bar

---

packages/teleport/src/DesktopSession/DesktopSession.story.tsx
packages/teleport/src/DesktopSession/DesktopSession.tsx
packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
packages/teleport/src/Player/DesktopPlayer.tsx
packages/teleport/src/Player/ProgressBar/ProgressBar.tsx
packages/teleport/src/Player/ProgressBar/ProgressBarDesktop.tsx
packages/teleport/src/Player/ProgressBar/index.tsx
packages/teleport/src/components/TdpClientCanvas/TdpClientCanvas.tsx
packages/teleport/src/lib/tdp/client.ts
packages/teleport/src/lib/tdp/playerClient.ts

backports for:
https://github.com/gravitational/webapps/pull/628
https://github.com/gravitational/webapps/pull/635
https://github.com/gravitational/webapps/pull/638
https://github.com/gravitational/webapps/pull/640
https://github.com/gravitational/webapps/pull/648

v9 backports

---

packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Audit/fixtures/index.ts
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts

Backport https://github.com/gravitational/webapps/pull/656 to teleport-v9

Support the 'unknown' audit event (#656)

---

packages/teleport/src/Apps/AddApp/AddApp.tsx
packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
packages/teleport/src/Databases/AddDatabase/AddDatabase.story.tsx
packages/teleport/src/Databases/AddDatabase/AddDatabase.test.tsx
packages/teleport/src/Databases/AddDatabase/AddDatabase.tsx
packages/teleport/src/Databases/Databases.tsx
packages/teleport/src/Nodes/AddNode/AddNode.tsx
packages/teleport/src/Nodes/AddNode/Manually/Manually.tsx
packages/teleport/src/Nodes/AddNode/__snapshots__/AddNode.story.test.tsx.snap
packages/teleport/src/components/DownloadLinks/DownloadLinks.tsx
packages/teleport/src/components/DownloadLinks/index.tsx

Backport #621 to v8.

---

packages/teleport/src/Apps/AddApp/AddApp.tsx
packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
packages/teleport/src/Databases/AddDatabase/AddDatabase.story.tsx
packages/teleport/src/Databases/AddDatabase/AddDatabase.test.tsx
packages/teleport/src/Databases/AddDatabase/AddDatabase.tsx
packages/teleport/src/Databases/Databases.tsx
packages/teleport/src/Nodes/AddNode/AddNode.tsx
packages/teleport/src/Nodes/AddNode/Manually/Manually.tsx
packages/teleport/src/Nodes/AddNode/__snapshots__/AddNode.story.test.tsx.snap
packages/teleport/src/Nodes/AddNode/useAddNode.ts
packages/teleport/src/components/DownloadLinks/DownloadLinks.tsx
packages/teleport/src/components/DownloadLinks/index.ts

Backport https://github.com/gravitational/webapps/pull/621

[v9] If running in enterprise version then provide the enterprise download links (#621)

---

packages/teleterm/src/ui/TopBar/Identity/IdentitySelector/IdentitySelector.tsx

Closes https://github.com/gravitational/webapps.e/issues/136

Prevent breaking layout on long cluster name

---

packages/teleterm/src/ui/TopBar/Identity/IdentityList/ClusterItem.tsx
packages/teleterm/src/ui/TopBar/Identity/IdentityList/IdentityList.tsx
packages/teleterm/src/ui/TopBar/Identity/useIdentity.ts

Closes https://github.com/gravitational/webapps.e/issues/142

Show username when possible in identity list

---

packages/design/src/DataTable/useTable.ts
packages/teleport/src/Sessions/SessionList/SessionList.tsx
packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap

[backport v9] Fix Active Sessions Table Misalignment

---

packages/teleterm/package.json
yarn.lock

Closes https://github.com/gravitational/webapps.e/issues/144

Update to `electron@13.6.9`

---

packages/teleterm/src/ui/ClusterConnect/ClusterAdd/ClusterAdd.tsx
packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormLogin.tsx
packages/teleterm/src/ui/ClusterLogout/ClusterLogout.tsx
packages/teleterm/src/ui/GatewayCreate/GatewayCreate.tsx
packages/teleterm/src/ui/TopBar/Identity/Identity.tsx
packages/teleterm/src/ui/TopBar/Identity/IdentityList/IdentityList.tsx
packages/teleterm/src/ui/components/KeyboardArrowsNavigation/KeyboardArrowsNavigation.test.tsx
packages/teleterm/src/ui/components/KeyboardArrowsNavigation/KeyboardArrowsNavigation.tsx

I moved submit functions from `onClick` to `onSubmit` - it seems to be more correct usage of `form` element (they works in `onClick` too).
Closes: https://github.com/gravitational/webapps.e/issues/152

Submit modals' forms on `Enter`

---

packages/teleport/src/Databases/AddDatabase/AddDatabase.tsx
packages/teleport/src/services/databases/databases.test.ts
packages/teleport/src/services/databases/makeDatabase.ts
packages/teleport/src/services/databases/types.ts

backport of https://github.com/gravitational/webapps/pull/709

[V9] Add Redis, MariaDB and Microsoft SQL Server to DB wizard #709

---

packages/teleterm/src/ui/services/clusters/clustersService.ts

Closes https://github.com/gravitational/webapps.e/issues/204

Prevent crash when network or cluster is offline

---

packages/design/src/theme/utils/getPlatform.js
packages/teleterm/src/mainProcess/mainProcess.ts
packages/teleterm/src/ui/AppInitializer.tsx
packages/teleterm/src/ui/appContext.ts
packages/teleterm/src/ui/boot.tsx

Thanks to `BrowserWindow.backgroundColor` we won't have white splash before _Loading_.

App initialization improvements 

---

packages/teleterm/src/ui/TopBar/Identity/EmptyIdentityList/EmptyIdentityList.tsx
packages/teleterm/src/ui/TopBar/Identity/Identity.tsx

Closes https://github.com/gravitational/webapps.e/issues/230

Close `Identity` popover after selecting an option

---

packages/teleterm/src/services/config/providers/keyboardShortcutsConfigProvider.ts

Closes https://github.com/gravitational/webapps.e/issues/199

Change connections shortcut to `Command/Ctrl-P`

---

packages/teleterm/src/ui/ClusterLogout/useClusterLogout.ts
packages/teleterm/src/ui/TabHost/TabHost.test.tsx
packages/teleterm/src/ui/TabHost/TabHost.tsx
packages/teleterm/src/ui/TabHost/useNewTabOpener.ts
packages/teleterm/src/ui/TabHost/useTabShortcuts.test.tsx
packages/teleterm/src/ui/TabHost/useTabShortcuts.ts
packages/teleterm/src/ui/TopBar/Clusters/useClusters.ts
packages/teleterm/src/ui/services/workspacesService/workspacesService.ts

Closes https://github.com/gravitational/webapps.e/issues/226

Resolve issues on logout

---

packages/design/src/Input/Input.jsx
packages/shared/components/FieldInput/FieldInput.story.tsx
packages/shared/components/FieldInput/FieldInput.test.tsx
packages/shared/components/FieldInput/FieldInput.tsx
packages/shared/components/FieldInput/__snapshots__/FieldInput.test.tsx.snap
packages/teleport/src/Apps/AddApp/AddApp.story.tsx
packages/teleport/src/Apps/AddApp/AddApp.tsx
packages/teleport/src/Apps/AddApp/Automatically/Automatically.test.tsx
packages/teleport/src/Apps/AddApp/Automatically/Automatically.tsx
packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
packages/teleport/src/Apps/AddApp/useAddApp.ts
packages/teleport/src/Databases/AddDatabase/AddDatabase.story.tsx
packages/teleport/src/Databases/AddDatabase/AddDatabase.test.tsx
packages/teleport/src/Databases/AddDatabase/AddDatabase.tsx
packages/teleport/src/Databases/AddDatabase/useAddDatabase.ts
packages/teleport/src/Nodes/AddNode/AddNode.story.test.tsx
packages/teleport/src/Nodes/AddNode/AddNode.story.tsx
packages/teleport/src/Nodes/AddNode/AddNode.tsx
packages/teleport/src/Nodes/AddNode/Automatically/Automatically.tsx
packages/teleport/src/Nodes/AddNode/Iam/Iam.tsx
packages/teleport/src/Nodes/AddNode/Iam/iam.test.ts
packages/teleport/src/Nodes/AddNode/Iam/index.ts
packages/teleport/src/Nodes/AddNode/Manually/Manually.tsx
packages/teleport/src/Nodes/AddNode/__snapshots__/AddNode.story.test.tsx.snap
packages/teleport/src/Nodes/AddNode/useAddNode.test.ts
packages/teleport/src/Nodes/AddNode/useAddNode.ts
packages/teleport/src/services/joinToken/joinToken.ts
packages/teleport/src/services/joinToken/makeJoinToken.ts
packages/teleport/src/services/joinToken/types.ts

Backport of https://github.com/gravitational/webapps/pull/690

[v8] Add IAM method to web ui (#690)

---

packages/teleport/src/Nodes/AddNode/AddNode.story.tsx
packages/teleport/src/Nodes/AddNode/AddNode.tsx
packages/teleport/src/Nodes/AddNode/useAddNode.ts

backports https://github.com/gravitational/webapps/pull/759 to v8
yarn tsc && yarn test passing

[V9] Fix trying to read from a null token (#759)

---

packages/teleport/src/Nodes/AddNode/AddNode.story.tsx
packages/teleport/src/Nodes/AddNode/AddNode.tsx
packages/teleport/src/Nodes/AddNode/useAddNode.ts

backports https://github.com/gravitational/webapps/pull/759 to v8
`yarn tsc && yarn test` passing

[V8] Fix trying to read from a null token (#759)

---

packages/teleport/src/components/ServersideSearchPanel/ServersideSearchPanel.tsx

in response to: https://github.com/gravitational/teleport/pull/12237

Change predicate example to use bracket notation

---

packages/teleport/src/components/ServersideSearchPanel/ServersideSearchPanel.tsx

[v9] backport #774 (Change predicate example to use bracket notation)

---

packages/teleterm/package.json
packages/teleterm/src/mainProcess/fixtures/mocks.ts
packages/teleterm/src/mainProcess/runtimeSettings.ts
packages/teleterm/src/mainProcess/types.ts
packages/teleterm/src/services/pty/ptyService.ts

[v9] Backport Prepend PATH with bundled tsh (#769)

---

packages/teleterm/src/ui/TabHost/ClusterConnectPanel/ClusterConnectPanel.tsx
packages/teleterm/src/ui/TopBar/Identity/EmptyIdentityList/EmptyIdentityList.tsx

Closes https://github.com/gravitational/webapps.e/issues/227

Replace "Lorem ipsum"

---

packages/teleterm/src/services/pty/ptyService.ts
packages/teleterm/src/services/pty/types.ts
packages/teleterm/src/services/tshd/v1/cluster_pb.d.ts
packages/teleterm/src/services/tshd/v1/cluster_pb.js
packages/teleterm/src/ui/ClusterConnect/ClusterLogin/useClusterLogin.ts
packages/teleterm/src/ui/DocumentCluster/DocumentCluster.story.tsx
packages/teleterm/src/ui/DocumentCluster/DocumentCluster.tsx
packages/teleterm/src/ui/DocumentCluster/clusterContext.tsx
packages/teleterm/src/ui/DocumentGateway/useDocumentGateway.ts
packages/teleterm/src/ui/DocumentTerminal/useDocumentTerminal.ts
packages/teleterm/src/ui/QuickInput/QuickInput.story.tsx
packages/teleterm/src/ui/QuickInput/useQuickInput.ts
packages/teleterm/src/ui/TopBar/Clusters/Clusters.tsx
packages/teleterm/src/ui/TopBar/Clusters/ClustersFilterableList/ClusterItem.tsx
packages/teleterm/src/ui/TopBar/Identity/Identity.tsx
packages/teleterm/src/ui/TopBar/Identity/useIdentity.ts
packages/teleterm/src/ui/commandLauncher.ts
packages/teleterm/src/ui/services/clusters/clustersService.test.ts
packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.ts
packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts
packages/teleterm/src/ui/utils/getClusterName.ts
packages/teleterm/src/ui/utils/index.ts

Backports https://github.com/gravitational/webapps/pull/767

[v9] Backport pin local shell to the specified cluster (#767)

---

packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
packages/teleport/src/Apps/AddApp/__snapshots__/AddApp.story.test.tsx.snap
packages/teleport/src/Nodes/AddNode/Manually/Manually.tsx
packages/teleport/src/Nodes/AddNode/__snapshots__/AddNode.story.test.tsx.snap
packages/teleport/src/config.ts

Backports https://github.com/gravitational/webapps/pull/751 to v8
`yarn tsc` and `yarn test` are clear
* Add configure step for adding nodes
Co-authored-by: David <david@goteleport.com>
Co-authored-by: Justinas <justinas@goteleport.com>

[V8] Add configure step (#751)

---

packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
packages/teleport/src/Apps/AddApp/__snapshots__/AddApp.story.test.tsx.snap
packages/teleport/src/Nodes/AddNode/Manually/Manually.tsx
packages/teleport/src/Nodes/AddNode/__snapshots__/AddNode.story.test.tsx.snap
packages/teleport/src/config.ts

Backports https://github.com/gravitational/webapps/pull/751 to v9
`yarn tsc` and `yarn test` are clear
* Add configure step for adding nodes
Co-authored-by: David <david@goteleport.com>
Co-authored-by: Justinas <justinas@goteleport.com>

[v9] Add configure step (#751)

---

packages/teleterm/src/ui/services/workspacesService/workspacesService.ts

Closes https://github.com/gravitational/webapps.e/issues/252

Omit title when comparing previous and current documents

---

packages/teleterm/src/ui/services/workspacesService/workspacesService.ts

Backport https://github.com/gravitational/webapps/pull/788

[v9] Backport Omit title when comparing previous and current documents

---

packages/teleport/src/Apps/useApps.ts
packages/teleport/src/Console/DocumentNodes/useNodes.ts
packages/teleport/src/Databases/useDatabases.ts
packages/teleport/src/Desktops/useDesktops.ts
packages/teleport/src/Kubes/useKubes.ts
packages/teleport/src/Nodes/useNodes.ts

[v9] backport #798 (Fix pagination bug)

---

packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Audit/fixtures/index.ts
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts
yarn.lock

* Indicate whether session.network events were allowed or blocked
Backports #800 
Fixes TEL-Q421-2
Fixes gravitational/teleport.e#331

[v8] Indicate whether session.network events were allowed or blocked (#800)

---

packages/teleport/src/Apps/Apps.tsx
packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
packages/teleport/src/Console/DocumentNodes/DocumentNodes.tsx
packages/teleport/src/Databases/Databases.tsx
packages/teleport/src/Databases/__snapshots__/Databases.story.test.tsx.snap
packages/teleport/src/Desktops/Desktops.tsx
packages/teleport/src/Kubes/Kubes.tsx
packages/teleport/src/Kubes/__snapshots__/Kubes.story.test.tsx.snap
packages/teleport/src/Nodes/Nodes.tsx
packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
packages/teleport/src/components/AgentErrorMessage/AgentErrorMessage.story.tsx
packages/teleport/src/components/AgentErrorMessage/AgentErrorMessage.tsx
packages/teleport/src/components/AgentErrorMessage/index.ts

part of https://github.com/gravitational/teleport/issues/12193
When agent errors are from predicate expression, add a link to the docs as part of the error
https://github.com/gravitational/teleport/pull/12262

Add predicate doc link with predicate error messages

---

packages/teleport/src/Apps/Apps.tsx
packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
packages/teleport/src/Console/DocumentNodes/DocumentNodes.tsx
packages/teleport/src/Databases/Databases.tsx
packages/teleport/src/Databases/__snapshots__/Databases.story.test.tsx.snap
packages/teleport/src/Desktops/Desktops.tsx
packages/teleport/src/Kubes/Kubes.tsx
packages/teleport/src/Kubes/__snapshots__/Kubes.story.test.tsx.snap
packages/teleport/src/Nodes/Nodes.tsx
packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
packages/teleport/src/components/AgentErrorMessage/AgentErrorMessage.story.tsx
packages/teleport/src/components/AgentErrorMessage/AgentErrorMessage.tsx
packages/teleport/src/components/AgentErrorMessage/index.ts

[v9] Backport #776 (Add predicate doc link with predicate error messages)

---

packages/teleport/src/Kubes/useKubes.ts

Adds initial sorting for Kubes table

Add Initial Sorting for Kubes

---

packages/teleterm/package.json
yarn.lock

I checked PTY & db access as well as restoring window state, anything other we should do a quick check on during upgrades like that?

Upgrade Electron to 19.0.0

---

yarn.lock

I forgot to update yarn.lock in b6cdfd7f.

yarn.lock: electron@^19 -> electron@19.0.0

---

yarn.lock

[v9] yarn.lock: electron@^19 -> electron@19.0.0 (#833)

---

packages/teleport/src/Support/Support.story.test.tsx
packages/teleport/src/Support/Support.story.tsx
packages/teleport/src/Support/Support.tsx
packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap

[v9] Add cloud link download to Help & Support (#820)

---

packages/teleterm/src/services/tshd/middleware.test.ts
packages/teleterm/src/services/tshd/middleware.ts

Closes https://github.com/gravitational/webapps.e/issues/285
Object values which keys includes `passw` will be changed to `~FILTERED~`.

Do not include secrets in gRPC logs

---

packages/teleterm/src/ui/DocumentTerminal/Terminal/ctrl.ts

Closes: https://github.com/gravitational/webapps.e/issues/220

Increase scrollback size to 5k lines

---

packages/teleterm/src/ui/ClusterLogout/useClusterLogout.ts
packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.test.ts
packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.ts
packages/teleterm/src/ui/services/workspacesService/workspacesService.ts

Closes https://github.com/gravitational/webapps.e/issues/270

Remove connections when logging out

---

packages/teleterm/src/ui/TopBar/Identity/IdentityList/IdentityListItem.tsx

Closes https://github.com/gravitational/webapps.e/issues/288

Prevent `active` label jumping in identity list

---

packages/teleterm/src/services/tshd/middleware.test.ts
packages/teleterm/src/services/tshd/middleware.ts

Backports https://github.com/gravitational/webapps/pull/829

[v9] Do not include secrets in gRPC logs

---

packages/teleterm/src/ui/DocumentTerminal/Terminal/ctrl.ts

Backports https://github.com/gravitational/webapps/pull/838

[v9] Increase scrollback size to 5k lines

---

packages/teleterm/src/ui/ClusterLogout/useClusterLogout.ts
packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.test.ts
packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.ts

Backports https://github.com/gravitational/webapps/pull/837

[v9] Remove connections when logging out

---

packages/teleterm/src/ui/TopBar/Identity/IdentityList/IdentityListItem.tsx

Backports https://github.com/gravitational/webapps/pull/839

[v9] Prevent active label jumping in identity list

---

packages/teleterm/src/ui/ClusterConnect/ClusterConnect.tsx

Backports https://github.com/gravitational/webapps/pull/840

[v9] Do not show the login dialog when a user adds a cluster that is connected

---

packages/teleterm/src/ui/DocumentGateway/useDocumentGateway.ts

Backport #814.
When a root cluster gets removed (the user logs out of it), we remove
resources related to it, so the `rootCluster` variable should never be
null at this point.

[v9] useDocumentGateway: Remove null rootCluster checks (#814)

---

package.json
packages/teleterm/package.json

[v9] Add dmg-only target for Connect and get-teleport-connect-dir script (#855 #856)

---

packages/teleport/src/services/user/makeUser.ts
packages/teleport/src/services/user/user.test.ts

[v9] Backport #871 (Fix null role response from users fetch)

---

packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Audit/fixtures/index.ts
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts

Add `access_request.search` event to audit log

---

packages/teleport/src/Kubes/ConnectDialog/ConnectDialog.tsx
packages/teleport/src/Kubes/ConnectDialog/__snapshots__/ConnectDialog.story.test.tsx.snap

Backport of https://github.com/gravitational/webapps/pull/880 to v9

[V9] Re-order kube resource connection instructions for clarity

---

README.md
packages/teleterm/README.md

Also, make a better distinction about which sections are Web UI related. Plus a small improvement to the command for copying protogen files.

Mention Teleport Connect in the README

---

packages/teleterm/src/ui/TopBar/Identity/Identity.story.tsx
packages/teleterm/src/ui/TopBar/Identity/Identity.tsx
packages/teleterm/src/ui/TopBar/Identity/IdentityList/IdentityList.tsx
packages/teleterm/src/ui/TopBar/Identity/IdentitySelector/IdentitySelector.tsx
packages/teleterm/src/ui/TopBar/Identity/index.ts
packages/teleterm/src/ui/TopBar/Identity/useIdentity.ts

Tbh, I've done this mostly so that we can easily test the long username stuff.
It's probably best to hide whitespace changes when viewing the diff.

Add story for Identity

---

packages/teleterm/src/ui/TopBar/Identity/Identity.story.tsx
packages/teleterm/src/ui/TopBar/Identity/Identity.tsx
packages/teleterm/src/ui/TopBar/Identity/IdentityList/IdentityList.tsx
packages/teleterm/src/ui/TopBar/Identity/IdentitySelector/IdentitySelector.tsx
packages/teleterm/src/ui/TopBar/Identity/index.ts
packages/teleterm/src/ui/TopBar/Identity/useIdentity.ts

[v10] Add story for Identity (#902)

---

packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
packages/teleport/src/Apps/AddApp/__snapshots__/AddApp.story.test.tsx.snap
packages/teleport/src/AuthConnectors/AuthConnectors.tsx
packages/teleport/src/AuthConnectors/EmptyList/EmptyList.tsx
packages/teleport/src/Nodes/AddNode/Iam/Iam.tsx
packages/teleport/src/Nodes/AddNode/__snapshots__/AddNode.story.test.tsx.snap
packages/teleport/src/Roles/Roles.tsx
packages/teleport/src/Support/Support.tsx
packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
packages/teleport/src/TrustedClusters/TrustedClusters.tsx
packages/teleport/src/Users/UserList/UserList.tsx
packages/teleport/src/Users/UserReset/UserReset.tsx
packages/teleport/src/Users/UserReset/__snapshots__/UserReset.story.test.tsx.snap
packages/teleport/src/Users/__snapshots__/Users.story.test.tsx.snap
packages/teleport/src/Welcome/NewCredentials/NewMfaDevice.tsx
packages/teleport/src/Welcome/NewCredentials/__snapshots__/NewCredentials.story.test.tsx.snap
packages/teleport/src/services/user/makeUser.ts

[v10] Small fixes and tweaks while going through test plan (#908)

---

packages/design/src/Popover/Popover.jsx
packages/design/src/Popover/Popover.story.js
packages/design/src/Popover/Popover.story.test.js
packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
packages/teleport/src/Databases/__snapshots__/Databases.story.test.tsx.snap
packages/teleport/src/Kubes/__snapshots__/Kubes.story.test.tsx.snap
packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
packages/teleport/src/components/Toggle/Toggle.tsx
packages/teleterm/src/ui/StatusBar/ShareFeedback/ShareFeedback.test.tsx
packages/teleterm/src/ui/StatusBar/ShareFeedback/ShareFeedback.tsx
packages/teleterm/src/ui/StatusBar/ShareFeedback/ShareFeedbackForm.tsx
packages/teleterm/src/ui/StatusBar/ShareFeedback/ShareFeedbackFormFields.tsx
packages/teleterm/src/ui/StatusBar/ShareFeedback/index.ts
packages/teleterm/src/ui/StatusBar/ShareFeedback/types.ts
packages/teleterm/src/ui/StatusBar/ShareFeedback/useShareFeedback.ts
packages/teleterm/src/ui/StatusBar/StatusBar.tsx
packages/teleterm/src/ui/services/statePersistence/statePersistenceService.ts

Backports https://github.com/gravitational/webapps/pull/899

[v10] Connect `ShareFeedback` with API (#899)

---

packages/teleterm/src/ui/TopBar/Clusters/ClusterSelector/ClusterSelector.tsx
packages/teleterm/src/ui/TopBar/Identity/IdentitySelector/IdentitySelector.tsx
packages/teleterm/src/ui/TopBar/TopBar.tsx

Backports https://github.com/gravitational/webapps/pull/903

[v10] Remove username from the `Identity` selector  (#903)

---

packages/teleterm/src/ui/StatusBar/StatusBar.tsx
packages/teleterm/src/ui/StatusBar/useActiveDocumentClusterBreadcrumbs.ts
packages/teleterm/src/ui/services/workspacesService/documentsService/documentsUtils.ts
packages/teleterm/src/ui/services/workspacesService/documentsService/index.ts

Backports https://github.com/gravitational/webapps/pull/901

[v10] Show cluster breadcrumbs (#901)

---

packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionItem.tsx

Show connection type in connection tracker

---

packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionItem.tsx

Backports https://github.com/gravitational/webapps/pull/906

[v10] Show connection type in connection tracker (#906)

---

packages/teleterm/src/ui/DocumentTerminal/useDocumentTerminal.ts

Backports https://github.com/gravitational/webapps/pull/920

[v10] Fall back to leaf cluster id when restoring leaf cluster terminal document

---

packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/useDatabases.ts
packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.ts
packages/teleterm/src/ui/services/connectionTracker/trackedConnectionUtils.ts

Backports https://github.com/gravitational/webapps/pull/889

[v10] Limit db connections to one per db server & db username (#889)

---

packages/teleport/src/Account/ChangePassword/ChangePassword.tsx
packages/teleport/src/stores/index.ts
packages/teleport/src/stores/storeNav.ts
packages/teleport/src/teleportContext.tsx

[v10] Fix menu bug (#929)

---

packages/shared/components/MenuLogin/MenuLogin.tsx
packages/shared/components/MenuLogin/types.ts
packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/Databases.tsx
packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/useDatabases.ts

Closes https://github.com/gravitational/webapps.e/issues/320 
I was unsure whether I should pass `default` value from the `MenuLogin` picker when it is empty (for redis protocol) or it is better to do have a default value in `connect` in `useDatabases`. IMO the second way is more universal 🤔

Add default username for Redis

---

packages/shared/components/MenuLogin/MenuLogin.tsx
packages/shared/components/MenuLogin/types.ts
packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/Databases.tsx
packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/useDatabases.ts

Backports https://github.com/gravitational/webapps/pull/919

[v10] Add default username for Redis (#919)

---

packages/teleterm/src/ui/services/clusters/clustersService.ts

Closes https://github.com/gravitational/webapps.e/issues/294

Filter out logins starting with dash

---

packages/teleterm/src/mainProcess/windowsManager.ts
packages/teleterm/src/ui/DocumentGateway/DocumentGateway.tsx

[v10] Update "Connect with GUI" section, add universal context menu (#926)

---

packages/teleterm/src/ui/services/clusters/clustersService.ts

Backports https://github.com/gravitational/webapps/pull/932

[v10] Filter out logins starting with dash (#932)

---

packages/teleterm/src/mainProcess/windowsManager.ts

Changing the window title as discussed on Slack.

Change window title to `Teleport Connect Preview`

---

packages/teleterm/src/mainProcess/windowsManager.ts

Backports https://github.com/gravitational/webapps/pull/939

[v10] Change window title to `Teleport Connect Preview` (#939)

---

packages/teleterm/src/ui/DocumentGateway/DocumentGateway.tsx

Make DocumentGateway responsive (#944)

---

packages/teleterm/src/ui/TabHost/useTabShortcuts.test.tsx
packages/teleterm/src/ui/TabHost/useTabShortcuts.ts

Backport https://github.com/gravitational/webapps/pull/941

[v10] on switchTab when tabs exist

---

packages/teleport/src/AppLauncher/useAppLauncher.ts

Backport https://github.com/gravitational/webapps/pull/913

[v10] fowards path parameter to app access authentication

---

packages/teleport/src/AppLauncher/useAppLauncher.ts

Backport https://github.com/gravitational/webapps/pull/913

[v9] fowards path parameter to app access authentication

---

packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.story.tsx
packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.tsx
packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormLogin.tsx
packages/teleterm/src/ui/ClusterConnect/ClusterLogin/useClusterLogin.ts

Backport https://github.com/gravitational/webapps/pull/954

[v10] autofill username if loggedInUser exists on cluster (#954)

---

packages/teleport/src/Discover/Discover.tsx
packages/teleport/src/Discover/discoverContext.ts
packages/teleport/src/Discover/useDiscover.tsx
packages/teleport/src/config.ts
packages/teleport/src/services/agents/types.ts

part of https://github.com/gravitational/teleport/issues/13997
- apply perm check that determines what type of agents are connectable by user
- moves agent id kind type from enterprise to open source
- merge enterprise PR: https://github.com/gravitational/webapps.e/pull/358
- update e-ref 
- in another PR, update permission checking for resources else where

Apply discover perm check

---

packages/design/src/Flex/Flex.jsx
packages/design/src/Flex/Flex.story.js
packages/design/src/system/index.js

[v10] Add gap property to Flex (#981)

---

README.md
packages/README.md
packages/build/.babelrc.js

Backport https://github.com/gravitational/webapps/pull/977 to teleport-v10

[v10] Updates Babel build targets (#977)

---

packages/teleport/src/Audit/EventList/EventList.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/services/audit/audit.test.ts
packages/teleport/src/services/audit/makeEvent.ts

Backport https://github.com/gravitational/webapps/pull/991

[v10] Display UTC time in audit log and session recording log (#991)

---

packages/teleport/src/components/Router/Router.jsx

[v8] Remove pathname injection in 404 message (#1002)

---

packages/teleport/src/components/Router/Router.jsx

Backport https://github.com/gravitational/webapps/pull/1002

[v10] Remove pathname injection in 404 message (#1002)

---

packages/teleport/src/components/Router/Router.jsx

Backport https://github.com/gravitational/webapps/pull/1002

[v9] Remove pathname injection in 404 message (#1002)

---

packages/teleterm/src/ui/StatusBar/ShareFeedback/useShareFeedback.ts

[v10] Add `c-` prefix to the OS field of the feedback form (#1009)

---

packages/teleterm/webpack.renderer.extend.js

Backport https://github.com/gravitational/webapps/pull/987

[v10] added a content-security-policy (#987)

---

packages/teleterm/src/mainProcess/windowsManager.ts

Backport https://github.com/gravitational/webapps/pull/986

[v10] deny any permission requests until needed (#986)

---

packages/teleterm/src/mainProcess/windowsManager.ts

Backport https://github.com/gravitational/webapps/pull/988

[v10] updated webPreferences config (#988)

---

packages/teleport/src/Audit/EventList/EventList.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/services/audit/audit.test.ts
packages/teleport/src/services/audit/makeEvent.ts

Backport https://github.com/gravitational/webapps/pull/991

[v9] Display UTC time in audit log and session recording log (#991)

---

packages/teleterm/src/mainProcess/mainProcess.ts
packages/teleterm/src/services/config/providers/keyboardShortcutsConfigProvider.ts
packages/teleterm/src/sharedProcess/ptyHost/ptyProcess.ts

This PR addresses three issues:
- fixes incorrect default cwd for terminal sessions
- adds `About` menu
- makes keyboard shortcuts similar to shortcuts in a browser

Minor Windows fixes

---

packages/teleterm/src/mainProcess/mainProcess.ts
packages/teleterm/src/services/config/providers/keyboardShortcutsConfigProvider.ts
packages/teleterm/src/sharedProcess/ptyHost/ptyProcess.ts

Backports https://github.com/gravitational/webapps/pull/1027

[v10] Fix minor Windows issues (#1027)

---

packages/teleterm/src/mainProcess/mainProcess.ts
packages/teleterm/src/mainProcess/resolveNetworkAddress.test.ts
packages/teleterm/src/mainProcess/resolveNetworkAddress.ts
packages/teleterm/src/mainProcess/testProcess.js

[v10] Connect: Wait for tshd gRPC server to start (#1021)

---

packages/teleterm/src/main.ts
packages/teleterm/src/mainProcess/windowsManager.ts

Backports https://github.com/gravitational/webapps/pull/1038

[v10] Allow only one instance of Connect (#1038)

---

packages/teleterm/src/mainProcess/mainProcess.ts

We already know what the URL is going to be. Let's wire up the button right now and the docs will be added soon.

Make "Learn More" button open Connect docs

---

packages/teleterm/src/mainProcess/mainProcess.ts

[v10] Make "Learn More" button open Connect docs (#1040)

---

packages/teleterm/package.json

Backports https://github.com/gravitational/webapps/pull/1039

[v10] Add dash to Windows artifact name (#1039)

---

packages/teleterm/src/mainProcess/runtimeSettings.ts
packages/teleterm/src/sharedProcess/sharedProcess.ts

Backports https://github.com/gravitational/webapps/pull/1048

[v10] Set TCP protocol explicitly (#1048)

---

.github/workflows/update-webassets.yaml

- Allow empty commits (in the event nothing changed)
- Include git status to help with troubleshooting
- Attempt to fix the webassets push with a fresh checkout

Further improvements to the webassets automation

---

.github/workflows/update-webassets.yaml

This didn't work. I don't think it should be necessary anyway.

webassets: remove the stash workflow

---

Dockerfile

[v10] CI: Fail if an update to yarn.lock is needed (#1047)

---

packages/teleterm/src/ui/DocumentGateway/useDocumentGateway.ts

[v10] useDocumentGateway: Default to '' rather than '0' (#1061)

---

.gitignore
packages/teleterm/src/main.ts
packages/teleterm/src/mainProcess/protocolHandler.ts

[v10] Add protocol interceptor (#1025)

---

Dockerfile

[v10] Use git diff to show the difference after yarn install (#1069)

---

packages/shared/hooks/index.ts
packages/shared/hooks/useRefAutoFocus/index.ts
packages/shared/hooks/useRefAutoFocus/useRefAutoFocus.test.tsx
packages/shared/hooks/useRefAutoFocus/useRefAutoFocus.ts
packages/teleterm/src/ui/Document/Document.tsx
packages/teleterm/src/ui/DocumentTerminal/DocumentTerminal.tsx
packages/teleterm/src/ui/Documents/DocumentsRenderer.tsx
packages/teleterm/src/ui/TabHost/TabHost.test.tsx

Backports https://github.com/gravitational/webapps/pull/1070

[v10] Move focus to active document (#1070)

---

packages/design/src/StepSlider/StepSlider.tsx
packages/shared/components/FieldInput/FieldInput.tsx
packages/teleport/src/Welcome/NewCredentials/NewCredentials.story.tsx
packages/teleport/src/Welcome/NewCredentials/NewMfaDevice.tsx
packages/teleport/src/Welcome/NewCredentials/NewPassword.tsx
packages/teleport/src/Welcome/NewCredentials/NewPasswordlessDevice.tsx
packages/teleport/src/components/FormLogin/FormLogin.tsx
packages/teleterm/src/ui/DocumentGateway/common.tsx

Backports https://github.com/gravitational/webapps/pull/1071

[v10] Refactor input focusing after transition (#1071)

---

packages/teleport/src/Player/ProgressBar/ProgressBar.tsx
packages/teleport/src/Player/ProgressBar/ProgressBarDesktop.tsx
packages/teleport/src/lib/tdp/playerClient.ts

[v10] Add a playback speed selector for Desktop Access recordings (#1072)

---

packages/teleport/src/Player/ProgressBar/ProgressBar.tsx
packages/teleport/src/Player/ProgressBar/ProgressBarDesktop.tsx
packages/teleport/src/lib/tdp/playerClient.ts

[v9] Add a playback speed selector for Desktop Access recordings (#1072)

---

packages/teleterm/src/services/pty/ptyHost/buildPtyOptions.ts
packages/teleterm/src/services/pty/types.ts
packages/teleterm/src/services/tshd/v1/cluster_pb.d.ts
packages/teleterm/src/services/tshd/v1/cluster_pb.js
packages/teleterm/src/ui/ClusterConnect/ClusterLogin/useClusterLogin.ts
packages/teleterm/src/ui/DocumentCluster/DocumentCluster.story.tsx
packages/teleterm/src/ui/DocumentCluster/clusterContext.tsx
packages/teleterm/src/ui/DocumentTerminal/useDocumentTerminal.ts
packages/teleterm/src/ui/QuickInput/QuickInput.story.tsx
packages/teleterm/src/ui/StatusBar/useActiveDocumentClusterBreadcrumbs.ts
packages/teleterm/src/ui/TabHost/ClusterConnectPanel/RecentClusters.tsx
packages/teleterm/src/ui/TopBar/Clusters/Clusters.tsx
packages/teleterm/src/ui/TopBar/Clusters/ClustersFilterableList/ClusterItem.tsx
packages/teleterm/src/ui/TopBar/Identity/Identity.story.tsx
packages/teleterm/src/ui/TopBar/Identity/Identity.tsx
packages/teleterm/src/ui/TopBar/Identity/useIdentity.ts
packages/teleterm/src/ui/commandLauncher.ts
packages/teleterm/src/ui/services/clusters/clustersService.test.ts
packages/teleterm/src/ui/services/clusters/clustersService.ts
packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.ts
packages/teleterm/src/ui/services/workspacesService/documentsService/documentsUtils.ts
packages/teleterm/src/ui/services/workspacesService/workspacesService.test.ts
packages/teleterm/src/ui/utils/getClusterName.ts
packages/teleterm/src/ui/utils/index.ts

Backport https://github.com/gravitational/webapps/pull/1086

[v10] Reorganize approach to cluster names (#1086)

---

packages/design/src/Icon/Icon.jsx
packages/design/src/Icon/Icon.story.js
packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Audit/fixtures/index.ts
packages/teleport/src/Support/Support.story.tsx
packages/teleport/src/Support/Support.tsx
packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts

backports https://github.com/gravitational/webapps/pull/980

[v10] Allow users to update Upgrade Window Start

---

packages/teleterm/electron-builder-config.js

Backport https://github.com/gravitational/webapps/pull/1142

[v10] Change Linux artifact names (#1142)

---

packages/teleport/src/DesktopSession/ActionMenu.tsx

Add `(preview)` to Share Directory menu item

---

packages/teleport/src/config.ts
packages/teleport/src/services/user/makeAcl.ts
packages/teleport/src/services/user/user.test.ts

[v10] backport #1141

---

packages/teleterm/src/services/tshd/v1/service_grpc_pb.d.ts
packages/teleterm/src/services/tshd/v1/service_grpc_pb.js
packages/teleterm/src/services/tshd/v1/service_pb.d.ts
packages/teleterm/src/services/tshd/v1/service_pb.js

gravitational/teleport#15877 changes a bit how the protos are generated. This PR simply updates the generated JS files.

Update generated protos for Connect

---

packages/teleterm/src/services/tshd/v1/service_grpc_pb.d.ts
packages/teleterm/src/services/tshd/v1/service_grpc_pb.js
packages/teleterm/src/services/tshd/v1/service_pb.d.ts
packages/teleterm/src/services/tshd/v1/service_pb.js

[v10] Update generated protos for Connect

---

packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Audit/fixtures/index.ts
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts

[v8] Add an event for when a session recording is accessed

---

packages/teleport/src/Audit/EventList/EventTypeCell.tsx
packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Audit/fixtures/index.ts
packages/teleport/src/services/audit/makeEvent.ts
packages/teleport/src/services/audit/types.ts

[v10] Add an event for when a session recording is accessed

---

packages/teleport/src/lib/tdp/client.ts
packages/teleport/src/lib/tdp/codec.ts
packages/teleport/src/lib/tdp/sharedDirectoryManager.ts

Corresponds with https://github.com/gravitational/teleport/pull/16022
Backport to v10 required

Adds `is_empty` to the File System Object

---

packages/teleport/src/lib/tdp/client.ts
packages/teleport/src/lib/tdp/codec.ts
packages/teleport/src/lib/tdp/sharedDirectoryManager.ts

Backports #1174 to teleport-v10

[v10] backport #1174

---

packages/teleport/src/Discover/LoginTrait/LoginTrait.test.tsx
packages/teleport/src/Discover/LoginTrait/LoginTrait.tsx
packages/teleport/src/Discover/LoginTrait/__snapshots__/LoginTrait.story.test.tsx.snap

backport of #1180 to teleport-v10

[v10] Discover Bug fix appending index number to login trait names (#1180)

---

packages/teleterm/electron-builder-config.js

Backport https://github.com/gravitational/webapps/pull/1183

[v10] Change DEB artifact name (#1183)

---

packages/teleport/src/Discover/Discover.tsx
packages/teleport/src/Discover/DownloadScript/DownloadScript.tsx
packages/teleport/src/Discover/DownloadScript/__snapshots__/DownloadScript.story.test.tsx.snap
packages/teleport/src/Discover/Finished/Finished.story.tsx
packages/teleport/src/Discover/LoginTrait/LoginTrait.story.test.tsx
packages/teleport/src/Discover/LoginTrait/LoginTrait.story.tsx
packages/teleport/src/Discover/LoginTrait/LoginTrait.test.tsx
packages/teleport/src/Discover/LoginTrait/LoginTrait.tsx
packages/teleport/src/Discover/LoginTrait/__snapshots__/LoginTrait.story.test.tsx.snap
packages/teleport/src/Discover/LoginTrait/useLoginTrait.ts
packages/teleport/src/Discover/SelectResource/SelectResource.test.tsx
packages/teleport/src/Discover/SelectResource/SelectResource.tsx
packages/teleport/src/Discover/Shared.tsx
packages/teleport/src/Discover/TestConnection/TestConnection.story.tsx
packages/teleport/src/Discover/TestConnection/TestConnection.tsx
packages/teleport/src/Discover/TestConnection/useTestConnection.ts
packages/teleport/src/Discover/templates/index.ts
packages/teleport/src/Discover/templates/logins.yaml
packages/teleport/src/Discover/templates/loginsAndRuleUsers.yaml
packages/teleport/src/Discover/templates/ruleConnectionDiagnostic.yaml
packages/teleport/src/Discover/useDiscover.tsx
packages/teleport/src/stores/storeUserContext.ts

backport of #1185 to teleport-v10

[Discover] Check perms during the flow step instead of at beg (#1185)

---

package.json
packages/build/package.json
packages/teleport/src/Discover/Discover.tsx
packages/teleport/src/Discover/useDiscover.tsx
packages/teleport/src/Main/Main.story.tsx
packages/teleport/src/Main/Main.tsx
packages/teleport/src/Main/MainContainer.tsx
packages/teleport/src/Main/useMain.ts
packages/teleport/src/components/BannerList/Banner.test.tsx
packages/teleport/src/components/BannerList/Banner.tsx
packages/teleport/src/components/BannerList/BannerList.test.tsx
packages/teleport/src/components/BannerList/BannerList.tsx
packages/teleport/src/components/BannerList/index.tsx
packages/teleport/src/components/BannerList/useAlerts.test.tsx
packages/teleport/src/components/BannerList/useAlerts.tsx
packages/teleport/src/config.ts
packages/teleport/src/services/alerts/alerts.tsx
packages/teleport/src/services/alerts/index.ts
yarn.lock

[v10] Add BannerList and Banner components to display cluster alerts on load (#1169)

---

packages/teleport/src/Discover/Discover.tsx
packages/teleport/src/Main/Main.tsx
packages/teleport/src/components/BannerList/Banner.test.tsx
packages/teleport/src/components/BannerList/Banner.tsx
packages/teleport/src/components/BannerList/BannerList.tsx
packages/teleport/src/components/BannerList/useAlerts.test.tsx
packages/teleport/src/services/alerts/alerts.tsx

backports gravitational/webapps#1193

[v10] add cluster alert links to UX (#1193)

---

@types/raw-loader.d.ts

Backport #1206 to teleport-v10

[v10] Remove `raw-loader` completely

---

README.md
packages/build/webpack/webpack.dev.config.js

Backports #1207 to teleport-v10.

[v10] Add caching to Webpack during development 

---

packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/services/audit/makeEvent.ts

[v10] Remove database reference when undefined in session start, end for Audit Log

---

packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/services/audit/makeEvent.ts

[v9] Remove database reference when undefined in session start, end for Audit Log

---

packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/services/audit/makeEvent.ts

[v8] Remove database reference when undefined in session start, end for Audit Log

---

packages/teleport/src/Audit/EventList/EventList.tsx
packages/teleport/src/DesktopSession/ActionMenu.tsx
packages/teleport/src/DesktopSession/DesktopSession.story.tsx
packages/teleport/src/DesktopSession/DesktopSession.tsx
packages/teleport/src/DesktopSession/TopBar.tsx
packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
packages/teleport/src/DesktopSession/useDesktopSession.tsx
packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
packages/teleport/src/Kubes/AddKube/AddKube.story.tsx
packages/teleport/src/Main/fixtures/index.ts
packages/teleport/src/Player/ProgressBar/ProgressBarDesktop.tsx
packages/teleport/src/components/Router/Router.jsx
packages/teleport/src/config.ts
packages/teleport/src/lib/tdp/client.ts
packages/teleport/src/lib/tdp/codec.ts
packages/teleport/src/services/user/makeAcl.ts
packages/teleport/src/services/user/types.ts
packages/teleport/src/services/user/user.test.ts

also removes some unecessary directory sharing stuff that somehow snuck in to v9

[v9] backport TDP PNG2 (#1230)

---

packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/services/audit/makeEvent.ts

Updates gravitational/teleport#3900

Fix copy for SCP upload audit event

---

packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/services/audit/makeEvent.ts

[v10] Fix copy for SCP upload audit event

---

packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/services/audit/makeEvent.ts

[v9] Fix copy for SCP upload audit event

---

packages/teleport/src/Discover/Desktop/ConnectTeleport/CreateTeleportConfigAnimation.tsx
packages/teleport/src/Discover/Desktop/ConnectTeleport/RunConfigureScript.tsx
packages/teleport/src/Discover/Desktop/ConnectTeleport/RunConfigureScriptAnimation.tsx

This backports the following to teleport-v11:
- https://github.com/gravitational/webapps/pull/1247
- https://github.com/gravitational/webapps/pull/1205

[v11] Backports

---

packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
packages/teleport/src/Audit/fixtures/index.ts
packages/teleport/src/services/audit/makeEvent.ts

Backport https://github.com/gravitational/webapps/pull/1242:

[v10] Fix DB SQLServer audit events typos

---

packages/teleport/src/Support/Support.tsx
packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap

[v8] backport #1257 (Update "Create a Support Ticket" URL)

---

packages/teleterm/package.json
packages/teleterm/src/ui/DocumentCluster/DocumentCluster.tsx
packages/teleterm/src/ui/TopBar/NavigationMenu/NavigationMenu.tsx
packages/teleterm/src/ui/components/Notifcations/Notification.tsx
packages/teleterm/src/ui/components/Notifcations/Notifications.tsx
yarn.lock

A few UI fixes and Electron update to the latest 19.x.

Connect testing fixes

---

packages/teleterm/package.json
packages/teleterm/src/ui/DocumentCluster/DocumentCluster.tsx
packages/teleterm/src/ui/TopBar/NavigationMenu/NavigationMenu.tsx
packages/teleterm/src/ui/components/Notifcations/Notification.tsx
packages/teleterm/src/ui/components/Notifcations/Notifications.tsx
yarn.lock

Backport https://github.com/gravitational/webapps/pull/1269

[v11] Connect testing fixes (#1269)

---

packages/shared/components/FileTransfer/FileTransferStateless/FileList/FileListItem.tsx
packages/shared/components/FileTransfer/FileTransferStateless/UploadForm/UploadForm.tsx
packages/shared/components/FileTransfer/useFilesStore.ts
packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx

Backport https://github.com/gravitational/webapps/pull/1276

[v11] File Transfer UI fixes (#1276)

---

packages/teleport/src/Desktops/Desktops.tsx
packages/teleport/src/Kubes/Kubes.tsx
packages/teleport/src/Kubes/__snapshots__/Kubes.story.test.tsx.snap

Backport https://github.com/gravitational/webapps/pull/1288 to teleport-v11.

[v11] Change Desktop page to link to Discover, fix k8s typo

---

packages/shared/utils/pipe.ts
packages/teleterm/src/ui/services/clusters/clustersService.ts

[v11] Connect: Fix filtering internal logins

---

packages/teleport/src/DesktopSession/DesktopSession.story.test.tsx
packages/teleport/src/DesktopSession/DesktopSession.story.tsx
packages/teleport/src/DesktopSession/DesktopSession.tsx
packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
packages/teleport/src/DesktopSession/useDesktopSession.tsx
packages/teleport/src/Player/DesktopPlayer.tsx
packages/teleport/src/components/TdpClientCanvas/TdpClientCanvas.tsx
packages/teleport/src/config.ts
packages/teleport/src/lib/tdp/client.ts
packages/teleport/src/lib/useWebAuthn.ts
packages/teleport/src/services/desktops/desktops.ts

Backports #1297 to v11
Do not merge until https://github.com/gravitational/teleport/pull/17935 is merged or desktop sessions will break.

[v11] Warn user when desktop is active (#1297)

---

packages/teleport/src/DesktopSession/DesktopSession.story.test.tsx
packages/teleport/src/DesktopSession/DesktopSession.story.tsx
packages/teleport/src/DesktopSession/DesktopSession.tsx
packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
packages/teleport/src/DesktopSession/useDesktopSession.tsx
packages/teleport/src/Player/DesktopPlayer.tsx
packages/teleport/src/components/TdpClientCanvas/TdpClientCanvas.tsx
packages/teleport/src/config.ts
packages/teleport/src/lib/tdp/client.ts
packages/teleport/src/lib/useWebAuthn.ts
packages/teleport/src/services/desktops/desktops.ts

Backports #1297 to v10
I found a stumper of a webpack dev server error when manually testing which was fixed by b27c1b831ac2a403519aef2c640899317d21b930
Do not merge until https://github.com/gravitational/teleport/pull/17936 is merged or desktop sessions will break.

[v10] Warn user when desktop is active (#1297)

---

packages/teleport/src/DesktopSession/DesktopSession.story.test.tsx
packages/teleport/src/DesktopSession/DesktopSession.story.tsx
packages/teleport/src/DesktopSession/DesktopSession.tsx
packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
packages/teleport/src/DesktopSession/useDesktopSession.tsx
packages/teleport/src/Player/DesktopPlayer.tsx
packages/teleport/src/components/TdpClientCanvas/TdpClientCanvas.tsx
packages/teleport/src/config.ts
packages/teleport/src/lib/tdp/client.ts
packages/teleport/src/lib/useWebAuthn.ts
packages/teleport/src/services/desktops/desktops.ts

Backports #1297 to v9
Do not merge until https://github.com/gravitational/teleport/pull/17937 is merged or desktop sessions will break.

[v9] Warn user when desktop is active (#1297)

---

packages/teleport/src/services/history/history.test.ts
packages/teleport/src/services/history/history.ts

[v9] Update ensureBaseUrl conditional (#1320)

---

packages/teleport/src/services/history/history.test.ts
packages/teleport/src/services/history/history.ts

[v10] Update ensureBaseUrl conditional (#1320)

---

packages/build/.eslintrc.js
packages/build/package.json
packages/teleport/src/Databases/Databases.tsx
packages/teleport/src/Discover/Server/TestConnection/TestConnection.tsx
packages/teleport/src/Kubes/Kubes.tsx
packages/teleport/src/Nodes/Nodes.tsx
packages/teleport/src/Welcome/NewCredentials/NewMfaDevice.tsx
packages/teleport/src/components/NodeList/NodeList.tsx
packages/teleterm/src/ui/DocumentTerminal/DocumentTerminal.tsx
packages/teleterm/src/ui/TopBar/Identity/Identity.tsx
packages/teleterm/src/ui/TopBar/Identity/IdentitySelector/IdentitySelector.tsx
yarn.lock

Also tentatively adds some react hooks rule.

Enable and fix useless fragment eslint error

---

packages/teleport/src/services/history/history.test.ts
packages/teleport/src/services/history/history.ts

[v9] Update ensureBaseUrl to use URL constructors only (#1328)

---

packages/teleport/src/services/history/history.test.ts
packages/teleport/src/services/history/history.ts

[v11] Update ensureBaseUrl to use URL constructors only (#1328)

---

packages/teleport/src/Sessions/SessionList/SessionList.tsx
packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
packages/teleport/src/Sessions/fixtures/index.ts
packages/teleport/src/services/session/makeSession.ts
packages/teleport/src/services/session/types.ts

Updates gravitational/teleport#17126
Updates gravitational/teleport#17871

Show all kinds of active sessions

---

packages/teleport/src/Discover/Kubernetes/TestConnection/TestConnection.story.tsx
packages/teleport/src/Discover/Kubernetes/TestConnection/TestConnection.tsx
packages/teleport/src/Discover/Kubernetes/TestConnection/useTestConnection.ts
packages/teleport/src/Discover/Server/TestConnection/TestConnection.story.tsx
packages/teleport/src/Discover/Server/TestConnection/TestConnection.tsx
packages/teleport/src/Discover/Server/TestConnection/useTestConnection.ts
packages/teleport/src/Discover/Shared/Header.tsx
packages/teleport/src/Discover/Shared/index.ts
packages/teleport/src/Discover/types.ts
packages/teleport/src/Discover/useDiscover.tsx
packages/teleport/src/services/agents/agents.test.ts
packages/teleport/src/services/agents/agents.ts

backport #1319 to teleport-v10

[v10] Discover: Add back button for `TestConnection` screens (#1319)

---

packages/teleterm/src/main.ts
packages/teleterm/src/mainProcess/mainProcess.ts
packages/teleterm/src/preload.ts
packages/teleterm/src/services/logger/index.ts
packages/teleterm/src/services/logger/loggerService.ts
packages/teleterm/src/sharedProcess/sharedProcess.ts

Backport https://github.com/gravitational/webapps/pull/1046

[v11] Log shared process `stdout` and `stderr` (#1046)

---

packages/teleport/src/Sessions/SessionList/SessionList.tsx
packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
packages/teleport/src/Sessions/fixtures/index.ts
packages/teleport/src/services/session/makeSession.ts
packages/teleport/src/services/session/types.ts

[v11] Show all kinds of active sessions

---

packages/teleterm/src/services/tshd/createClient.ts
packages/teleterm/src/services/tshd/types.ts
packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/Databases.tsx
packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/useDatabases.ts
packages/teleterm/src/ui/DocumentCluster/clusterContext.tsx
packages/teleterm/src/ui/DocumentGateway/useDocumentGateway.ts
packages/teleterm/src/ui/DocumentTerminal/DocumentTerminal.tsx
packages/teleterm/src/ui/DocumentTerminal/useTshFileTransferHandlers.ts
packages/teleterm/src/ui/services/clusters/clustersService.ts
packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
packages/teleterm/src/ui/utils/retryWithRelogin.test.ts
packages/teleterm/src/ui/utils/retryWithRelogin.ts

Backport #1238
webapps.e: https://github.com/gravitational/webapps.e/pull/433

[v11] retryWithRelogin: Enable use outside of document context

---

packages/teleterm/src/main.ts

[v10] Prevent non-https protocol from opening external windows (#1343)

---

Dockerfile
package.json
packages/build/package.json
packages/teleterm/package.json
packages/teleterm/src/mainProcess/windowsManager.ts
yarn.lock

Closes https://github.com/gravitational/webapps.e/issues/369 
Closes https://github.com/gravitational/teleport-private/issues/175
Drone build https://drone.platform.teleport.sh/gravitational/teleport/17585 
I quickly tested the updated app and didn't see any issues.
I removed custom `node-gyp` resolution, it doesn't have any effect.

Update to Electron 21

---

Dockerfile
package.json
packages/build/package.json
packages/teleterm/package.json
packages/teleterm/src/mainProcess/windowsManager.ts
yarn.lock

Backport https://github.com/gravitational/webapps/pull/1351

[v11] Update to Electron 21 (#1351)

---

packages/design/src/Checkbox/Checkbox.story.tsx
packages/design/src/Checkbox/Checkbox.tsx
packages/design/src/Checkbox/index.ts
packages/teleport/src/Discover/Kubernetes/DownloadScript/DownloadScript.tsx

v10 backport of https://github.com/gravitational/webapps/pull/1321

[v10] backport #1321 (Add checkbox component to design package)

---

packages/teleterm/src/services/pty/ptyHost/buildPtyOptions.ts

Backport https://github.com/gravitational/webapps/pull/1366

[v10] Forward SSH agent (#1366)

---

.github/workflows/codeql.yml

Fixes to address suggestions from the original CodeQL config PR: https://github.com/gravitational/webapps/pull/1373

CodeQL Config fixes

---

packages/teleport/src/components/BannerList/useAlerts.tsx
packages/teleport/src/services/alerts/alerts.tsx

Backport #1395 to teleport-v10.

[v10] Fix alerts from not disappearing on route changes

---

packages/teleport/src/boot.tsx

Backport #1396 to teleport-v11.

Lazy load Telemetry only when needed

---

packages/teleport/package.json
yarn.lock

[v11] Update xterm to 5.0.0 (#1400)

---

packages/teleport/package.json
yarn.lock

[v10] Update xterm to 5.0.0 (#1400)

---

packages/shared/hooks/useAsync.test.ts
packages/shared/hooks/useAsync.ts

[v11] useAsync: Add support for abort signal (#1377)

---

packages/teleport/src/Main/OnboardDiscover/OnboardDiscover.tsx
packages/teleport/src/Welcome/NewCredentials/NewCredentials.tsx
packages/teleport/src/Welcome/NewCredentials/NewMfaDevice.tsx
packages/teleport/src/Welcome/NewCredentials/NewPassword.tsx
packages/teleport/src/Welcome/Welcome.test.tsx
packages/teleport/src/components/BannerList/Banner.tsx
packages/teleport/src/components/RecoveryCodes/RecoveryCodes.tsx
packages/teleport/src/config.ts
packages/teleport/src/services/userEvent/index.ts
packages/teleport/src/services/userEvent/types.ts
packages/teleport/src/services/userEvent/userEvent.ts

[v11] capture events from webapps

---

packages/teleport/src/lib/tdp/sharedDirectoryManager.ts

backports #1382 to teleport-v10

[v10] Fix large file corruption (#1382)

---

packages/teleport/src/lib/tdp/sharedDirectoryManager.ts

backports #1382 to teleport-v11

[v11] Fix large file corruption (#1382)

---

packages/teleport/src/components/BannerList/Banner.tsx
packages/teleport/src/services/userEvent/userEvent.ts

[v11] update alert field on banner capture 

---

packages/teleport/src/AppLauncher/useAppLauncher.ts
packages/teleport/src/services/apps/apps.ts

[v11] add subject session value

---

packages/teleport/src/AppLauncher/useAppLauncher.ts
packages/teleport/src/services/apps/apps.ts

[v10] Add subject value to app sessions

---

packages/teleport/src/AppLauncher/useAppLauncher.ts
packages/teleport/src/services/apps/apps.ts

Backports https://github.com/gravitational/webapps/pull/1413

[v9] add subject session value

---

packages/teleterm/src/services/tshd/v1/app_pb.js
packages/teleterm/src/services/tshd/v1/auth_settings_pb.js
packages/teleterm/src/services/tshd/v1/cluster_pb.js
packages/teleterm/src/services/tshd/v1/database_pb.js
packages/teleterm/src/services/tshd/v1/gateway_pb.js
packages/teleterm/src/services/tshd/v1/kube_pb.js
packages/teleterm/src/services/tshd/v1/label_pb.js
packages/teleterm/src/services/tshd/v1/server_pb.js
packages/teleterm/src/services/tshd/v1/service_pb.js

gravitational/teleport#19206 updated Buf and protoc in teleport v10. The changes shouldn't affect how Connect works, but I'm copying the updates protos anyway, just to be safe.

[v10] Update Connect proto files

---

packages/teleterm/src/mainProcess/fixtures/mocks.ts
packages/teleterm/src/ui/DocumentCluster/DocumentCluster.story.tsx
packages/teleterm/src/ui/QuickInput/QuickInput.story.tsx
packages/teleterm/src/ui/TopBar/Connections/Connections.story.tsx

[v11] Fix Connect stories

---

packages/build/package.json
yarn.lock

[v11] Update electron-builder to 24.0.0-alpha.5

---

packages/teleport/src/Console/DocumentSsh/useSshSession.ts
packages/teleport/src/DesktopSession/DesktopSession.tsx
packages/teleport/src/Player/DesktopPlayer.tsx
packages/teleport/src/Player/ProgressBar/ProgressBarDesktop.tsx
packages/teleport/src/Player/Xterm/Xterm.tsx
packages/teleport/src/components/TdpClientCanvas/TdpClientCanvas.tsx
packages/teleport/src/lib/tdp/client.ts
packages/teleport/src/lib/term/enums.ts
packages/teleport/src/lib/term/terminal.ts
packages/teleport/src/lib/term/tty.ts
packages/teleport/src/lib/term/ttyPlayer.js
packages/teleport/src/lib/term/ttyPlayer.test.js
packages/teleport/src/lib/term/ttyPlayerEventProvider.js
packages/teleport/src/lib/useWebAuthn.ts

Backports #1442 to teleport-v10

[v10] Adds a status code to the closing of the tdp client's websocket

---

packages/build/package.json
packages/teleport/src/Console/Console.tsx
packages/teleport/src/Console/consoleContext.tsx
packages/teleport/src/Console/useOnExitConfirmation.test.ts
packages/teleport/src/Console/useOnExitConfirmation.ts
packages/teleport/src/Discover/Discover.test.tsx
packages/teleport/src/Discover/Discover.tsx
packages/teleport/src/Discover/Shared/SetupAccess/useUserTraits.test.tsx
packages/teleport/src/Discover/Shared/SetupAccess/useUserTraits.ts
packages/teleport/src/Discover/useDiscover.tsx
packages/teleport/src/Login/useLogin.ts
packages/teleport/src/Player/Player.tsx
packages/teleport/src/TopBar/useTopBar.ts
packages/teleport/src/WebSessionContext.tsx
packages/teleport/src/components/Authenticated/Authenticated.tsx
packages/teleport/src/services/api/api.js
packages/teleport/src/services/localStorage/localStorage.ts
packages/teleport/src/services/user/user.ts
packages/teleport/src/services/websession/index.ts
packages/teleport/src/services/websession/storeWebSession.ts
packages/teleport/src/services/websession/test-utils.ts
packages/teleport/src/services/websession/types.ts
packages/teleport/src/services/websession/websession.ts
packages/teleport/src/useWebSession.ts
yarn.lock

v11 backport of #1275 
`e` counterpart: https://github.com/gravitational/webapps.e/pull/460

[v11] backport #1275 (Use sessionStorage for Authentication Bearer Token)

---

packages/teleport/src/Databases/ConnectDialog/ConnectDialog.test.tsx
packages/teleport/src/Databases/ConnectDialog/ConnectDialog.tsx
packages/teleport/src/Databases/ConnectDialog/__snapshots__/ConnectDialog.test.tsx.snap
packages/teleport/src/Discover/Database/AddDatabaseModal/AddDatabase.tsx
packages/teleport/src/lib/util.ts
packages/teleport/src/services/user/types.ts

Fixes https://github.com/gravitational/teleport/issues/15353

Display instructions for connecting to a database with passwordless auth

---

packages/teleport/src/lib/tdp/client.ts
packages/teleport/src/lib/term/enums.ts

backports #1463 to teleport-v9

[v9] Fix websocket close (#1463)

---

packages/teleport/src/lib/tdp/client.ts
packages/teleport/src/lib/term/enums.ts

backports #1463 to teleport-v10

[v10] Fix websocket close (#1463)

---

packages/teleport/src/lib/tdp/sharedDirectoryManager.ts

backports #1471 to teleport-v11

[v11] awaits the file write and close to avoid data corruption (#1471)

---

packages/teleport/src/services/audit/makeEvent.ts

[v10] Include session id in Session Uploaded event display

---

packages/teleport/src/services/audit/makeEvent.ts

[v11] Include session id in Session Uploaded event display

---

packages/teleport/src/Discover/Database/IamPolicy/IamPolicy.story.tsx
packages/teleport/src/Discover/Database/IamPolicy/IamPolicy.tsx
packages/teleport/src/Discover/Database/IamPolicy/index.ts
packages/teleport/src/Discover/Database/IamPolicy/useIamPolicy.ts
packages/teleport/src/Discover/Database/index.tsx
packages/teleport/src/Discover/Shared/CommandWithTimer/__snapshots__/CommandWithTimer.story.test.tsx.snap
packages/teleport/src/Discover/resource-lists.ts
packages/teleport/src/components/TextSelectCopy/TextSelectCopyMulti.tsx
packages/teleport/src/components/TextSelectCopy/__snapshots__/TextSelectCopyMulti.story.test.tsx.snap
packages/teleport/src/config.ts
packages/teleport/src/services/databases/databases.ts
packages/teleport/src/services/databases/types.ts

part of https://github.com/gravitational/teleport/issues/16858
https://www.figma.com/file/8DQZl1mYUPLgvKgmA6zPOM/In-Progress-Work?node-id=1296%3A67243&t=xGS8qRDdKJMGq6PA-0

[Discover] Implement the IAM policy screen

---

packages/teleterm/src/ui/ClusterConnect/ClusterAdd/ClusterAdd.story.tsx
packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.story.tsx
packages/teleterm/src/ui/ClusterLogout/ClusterLogout.story.tsx
packages/teleterm/src/ui/DocumentsReopen/DocumentsReopen.story.tsx
packages/teleterm/src/ui/services/modals/modalsService.ts

[v11] Connect: Add missing modal stories, misc modal fixes

---

packages/teleterm/src/services/tshd/v1/cluster_pb.d.ts
packages/teleterm/src/services/tshd/v1/cluster_pb.js
packages/teleterm/src/ui/DocumentCluster/DocumentCluster.story.tsx
packages/teleterm/src/ui/QuickInput/QuickInput.story.tsx
packages/teleterm/src/ui/TopBar/Identity/Identity.story.tsx
packages/teleterm/src/ui/services/clusters/clustersService.test.ts
packages/teleterm/src/ui/services/workspacesService/workspacesService.test.ts

Teleport counterpart https://github.com/gravitational/teleport/pull/19829

[Connect] Update protofiles to support `authClusterId`

---

packages/teleport/src/config.ts
packages/teleport/src/services/auth/auth.test.ts
packages/teleport/src/services/auth/auth.ts
packages/teleport/src/services/websession/websession.ts

[v11] Update sessionPath value to new endpoint (#1486)

---

packages/teleterm/package.json
yarn.lock

[v11] Update Electron to 22.0.0

---

packages/design/src/StepSlider/StepSlider.tsx
packages/teleport/src/Welcome/NewCredentials/NewCredentials.tsx
packages/teleport/src/Welcome/NewCredentials/NewMfaDevice.tsx
packages/teleport/src/Welcome/NewCredentials/NewPassword.tsx
packages/teleport/src/Welcome/NewCredentials/Success.tsx
packages/teleport/src/Welcome/useToken.ts
packages/teleport/src/components/RecoveryCodes/RecoveryCodes.tsx
packages/teleport/src/services/userEvent/types.ts
packages/teleport/src/services/userEvent/userEvent.ts

[v11] capture additional prehog events

---

packages/teleport/src/Teleport.tsx

Backport #1503 and #1502 to v10

[v10] Add lazy loading for desktop sessions and session playback

---

packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx

backports #1509 to teleport-v9

[v9] Fix clipboard permissions apparent inconsistency (#1509)

---

package.json

[v11] Add --quiet to eslint package.json script

---

packages/teleterm/src/ui/LayoutManager.tsx
packages/teleterm/src/ui/appContextProvider.tsx
packages/teleterm/src/ui/hooks/useLoggedInUser.ts

Backport https://github.com/gravitational/teleport/pull/20552
e counterpart: https://github.com/gravitational/webapps.e/pull/480

[v11] Connect: Add useWorkspaceLoggedInUser

---

packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabase.story.tsx
packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabase.tsx
packages/teleport/src/Discover/Database/SetupAccess/SetupAccess.story.tsx
packages/teleport/src/Discover/Database/SetupAccess/SetupAccess.tsx
packages/teleport/src/Discover/Database/TestConnection/TestConnection.story.tsx
packages/teleport/src/Discover/Database/TestConnection/TestConnection.tsx
packages/teleport/src/Discover/Database/TestConnection/useTestConnection.ts
packages/teleport/src/Discover/Database/resources.ts
packages/teleport/src/Discover/SelectResource/SelectResource.tsx

backport of https://github.com/gravitational/teleport/pull/20719 and https://github.com/gravitational/teleport/pull/20753 to teleport-v11

[v11] [Discover] Enable mysql flow

---

packages/teleport/src/Console/DocumentSsh/DocumentSsh.story.tsx
packages/teleport/src/Console/DocumentSsh/useSshSession.ts
packages/teleport/src/Console/consoleContext.tsx
packages/teleport/src/Console/stores/types.ts
packages/teleport/src/Console/useTabRouting.ts
packages/teleport/src/Sessions/SessionList/SessionJoinBtn.test.tsx
packages/teleport/src/Sessions/SessionList/SessionJoinBtn.tsx
packages/teleport/src/Sessions/SessionList/SessionList.tsx
packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
packages/teleport/src/Sessions/fixtures/index.ts
packages/teleport/src/config.ts
packages/teleport/src/services/session/makeSession.ts
packages/teleport/src/services/session/types.ts

v11 backport of https://github.com/gravitational/teleport/pull/20782

[v11] Add support for Moderated Sessions in the Web UI
