- packages/shared/components/FormInvite/TwoFaInfo.jsx
- packages/shared/components/FormInvite/__snapshots__/FormInvite.story.test.js.snap
- packages/teleport/src/services/auth/auth.js
- packages/teleport/src/services/auth/auth.test.js
fixes https://github.com/gravitational/teleport/issues/3554
- Wrapped error with Error object
- Updated test to ensure error objects message is defined
- Update `sign up` to `create account` button wording
timeout error:
badrequest error:
facet settings not set:
reword to match button text:
extract error message from u2f lib: https://github.com/gravitational/teleport/pull/3592
> Fix U2F login error messages

- packages/design/src/Box/Box.jsx
- packages/teleport/src/cluster/CommunityCluster.tsx
- packages/teleport/src/cluster/components/Support/Support.story.test.tsx
- packages/teleport/src/cluster/components/Support/Support.story.tsx
- packages/teleport/src/cluster/components/Support/Support.tsx
- packages/teleport/src/cluster/components/Support/__snapshots__/Support.story.test.tsx.snap
- packages/teleport/src/cluster/components/Support/index.ts
- packages/teleport/src/cluster/features/featureSupport.ts
- packages/teleport/src/config.ts
resolves https://github.com/gravitational/webapps/issues/77
- Created a Support component that displays links and cluster info
- Created a story
- Created a snapshot testing
- Brought component in
- I wasn't provided the links, so I tried to search them, some I couldn't find
- Icons were expected on the sidebar b/c of ts, so i used `Icons.Stars` as a placeholders for everywhere
enterprise changes: https://github.com/gravitational/webapps.e/pull/7
> Create Support component, story, and test

- packages/teleport/src/cluster/components/Sessions/SessionList/ActionCell.tsx
- packages/teleport/src/cluster/components/Sessions/SessionList/IconCell.tsx
- packages/teleport/src/cluster/components/Sessions/SessionList/NodeCell.tsx
- packages/teleport/src/cluster/components/Sessions/SessionList/SessionList.tsx
- packages/teleport/src/cluster/components/Sessions/SessionList/UserCell.tsx
- packages/teleport/src/cluster/components/Sessions/Sessions.tsx
- packages/teleport/src/cluster/components/Sessions/__snapshots__/Sessions.story.test.tsx.snap
- packages/teleport/src/services/ssh/makeSession.ts
- packages/teleport/src/services/ssh/ssh.ts
- packages/teleport/src/services/ssh/types.ts
resolves https://github.com/gravitational/teleport/issues/3544
- Removed address, type column
- Renamed `created` to `started (utc)`
- Added duration, session ID columns
- Modified Node and Users to display name and address without port
- Modified action cell to use a dotted button dropdown menu
- Updated session.story snapshot
> Clean up active sessions list

- packages/teleport/src/cluster/components/Audit/AuditSessions/AuditSessions.story.test.tsx
- packages/teleport/src/cluster/components/Audit/AuditSessions/AuditSessions.story.tsx
- packages/teleport/src/cluster/components/Audit/AuditSessions/AuditSessions.tsx
- packages/teleport/src/services/audit/types.ts
closes https://github.com/gravitational/teleport/issues/3545
- Filters out non-interactive sessions (execs)
- Add `interactive` field to `SESSION_END` RawEvent type
- Update unit test
> Filter non interactive sessions out

- packages/gravity/package.json
- packages/teleport/package.json
- yarn.lock
fixes https://github.com/gravitational/webapps/issues/92
Update xterm to the minimum version (`2.8.1`), that fixes the wrap problem when copying and pasting
- Did some light manual testing on the terminal for possible udpate bug: `ls`, `exit`, session replay, alt switch tabs
> Update xterm to 2.8.1

- packages/teleport/src/console/useOnExitConfirmation.test.ts
- packages/teleport/src/console/useOnExitConfirmation.ts
fixes https://github.com/gravitational/webapps/issues/97
- Check for expired session before prompting confirmation
- Test expired session don't prompt
> Check for expired session before resources unload (redirect)

- packages/design/src/DataTable/Paged/Pager/Pager.jsx
- packages/design/src/Dialog/Dialog.jsx
- packages/teleport/src/cluster/components/Audit/AuditEvents/EventList/EventList.tsx
- packages/teleport/src/cluster/components/Audit/AuditEvents/EventList/EventListCells.tsx
- packages/teleport/src/cluster/components/Audit/AuditEvents/__snapshots__/AuditEvents.story.test.tsx.snap
- packages/teleport/src/cluster/components/Audit/AuditSessions/AuditSessions.tsx
- packages/teleport/src/cluster/components/Audit/AuditSessions/__snapshots__/AuditSessions.story.test.tsx.snap
- packages/teleport/src/cluster/components/Audit/EventDialog/EventDialog.tsx
- packages/teleport/src/cluster/components/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/cluster/components/Cluster.tsx
- packages/teleport/src/cluster/components/Nodes/__snapshots__/Nodes.story.test.tsx.snap
- packages/teleport/src/cluster/components/Nodes/useClusterNodes.ts
- packages/teleport/src/cluster/components/Sessions/SessionList/ActionCell.tsx
- packages/teleport/src/cluster/components/Sessions/__snapshots__/Sessions.story.test.tsx.snap
- packages/teleport/src/cluster/components/Support/Support.tsx
- packages/teleport/src/cluster/components/Support/__snapshots__/Support.story.test.tsx.snap
- packages/teleport/src/cluster/components/TopBar/ClusterInfoDialog/ClusterInfoDialog.tsx
- packages/teleport/src/cluster/components/TopBar/ClusterInfoDialog/__snapshots__/ClusterInfoDialog.test.tsx.snap
- packages/teleport/src/cluster/components/TopBar/TopBar.jsx
- packages/teleport/src/cluster/components/TopBar/__snapshots__/TopBar.story.test.tsx.snap
- packages/teleport/src/components/Layout/Layout.jsx
- packages/teleport/src/components/TopBar/TopBar.jsx
- packages/teleport/src/console/components/DocumentNodes/DocumentNodes.tsx
- packages/teleport/src/console/components/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
- packages/teleport/src/console/components/Tabs/JoinedUsers/JoinedUsers.jsx
- packages/teleport/src/dashboard/components/Clusters/ClusterList/ClusterList.tsx
- packages/teleport/src/dashboard/components/Clusters/__snapshots__/Clusters.story.test.tsx.snap
- packages/teleport/src/dashboard/components/Dashboard.tsx
- packages/teleport/src/dashboard/components/Layout/Layout.jsx
- Cluster info and support cluster info has their text aligned
- Put more spacing between number of users joined in session
- Put space between cluster and quick launch component in console
- Set Topbar to `overflowX` to scroll 
- Updated snapshots
https://github.com/gravitational/webapps.e/pull/11
> Tweak styling for topbar auto scrollX and text alignment

- packages/design/src/DataTable/Paged/Pager/Pager.jsx
- packages/design/src/DataTable/Paged/Pager/Pager.test.js
- packages/design/src/DataTable/Table.jsx
- packages/design/src/DataTable/Table.test.js
- packages/teleport/src/cluster/components/Audit/AuditEvents/__snapshots__/AuditEvents.story.test.tsx.snap
- packages/teleport/src/cluster/components/Audit/AuditSessions/__snapshots__/AuditSessions.story.test.tsx.snap
- packages/teleport/src/cluster/components/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/cluster/components/Nodes/__snapshots__/Nodes.story.test.tsx.snap
- packages/teleport/src/cluster/components/Sessions/__snapshots__/Sessions.story.test.tsx.snap
- packages/teleport/src/components/NodeList/NodeList.tsx
- packages/teleport/src/console/components/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
- packages/teleport/src/console/useOnExitConfirmation.test.ts
- packages/teleport/src/console/useOnExitConfirmation.ts
- packages/teleport/src/dashboard/components/Clusters/__snapshots__/Clusters.story.test.tsx.snap
- packages/teleport/src/services/audit/makeEvent.ts
- packages/teleport/src/services/audit/types.ts
fixes https://github.com/gravitational/teleport/issues/3827
fixes https://github.com/gravitational/teleport/issues/3836
fixes https://github.com/gravitational/teleport/issues/3835
fixes https://github.com/gravitational/teleport/issues/3837
- Set sorting to ASC as default, fix Nodelist sort to be ASC on initial render
- On exit confirmation for console, `leave session` for parties > 1, else `terminate session`
- Prevent incrementing page numbers when there are no data
- Provide description for `trusted_cluster_token.created` event
Sort ASC default:
Leave (user > 1) and Terminate (user == 1):
Prevent incrementing page numbers when there are no data:
Provide description for trusted_cluster_token.created:
> Fix assortment of user issues

- packages/teleport/src/components/QuickLaunch/QuickLaunch.jsx
fixes https://github.com/gravitational/teleport/issues/3790
QuickLaunch regex now accepts dashes between words.
> Allow dashes for login name in QuickLauncher

- packages/teleport/src/components/Login/LoginFailed.jsx
- packages/teleport/src/services/history.js
- packages/teleport/src/services/history.test.js
part of https://github.com/gravitational/teleport/issues/3774
- Use native URLSearchParams to handle escape symbols
- Add unit test
> Replace '+' symbols with empty spaces

- packages/design/src/TopNav/TopNavItem.jsx
- packages/design/src/TopNav/TopNavUserMenu/TopNavUserMenu.jsx
- packages/design/src/TopNav/__snapshots__/Topnav.story.test.js.snap
- packages/teleport/src/cluster/components/TopBar/__snapshots__/TopBar.story.test.tsx.snap
fixes https://github.com/gravitational/teleport/issues/3832#issuecomment-651436183 (login names)
- Removes upper casings for usernames/emails in topbars
**Note:** Teleport seems to allow case sensitive usernames, so I did not enforce lowercasing
> Remove uppercasing of login names

- packages/teleport/src/services/user/makeAcl.ts
part of https://github.com/gravitational/teleport/issues/3922
Set user permission for viewing audit logs (events)
https://github.com/gravitational/teleport/pull/3941
> Set user permission for viewing audit logs

- packages/teleport/src/cluster/components/Nodes/Nodes.tsx
- packages/teleport/src/cluster/components/Nodes/__snapshots__/Nodes.story.test.tsx.snap
- packages/teleport/src/components/QuickLaunch/QuickLaunch.jsx
- packages/teleport/src/console/components/DocumentNodes/DocumentNodes.tsx
- packages/teleport/src/console/components/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
- packages/teleport/src/dashboard/components/Clusters/ClusterList/ClusterList.tsx
- packages/teleport/src/dashboard/components/Clusters/__snapshots__/Clusters.story.test.tsx.snap
This change brings back the QuickLaunch input to the Cluster Nodes screen.
It also removes the Cluster list "on row click" event. Now, to get to the cluster management screen you have to click on the cluster name.
> Bring back QuickLaunch

- packages/teleport/src/cluster/components/Support/Support.tsx
- packages/teleport/src/cluster/components/Support/__snapshots__/Support.story.test.tsx.snap
resolves https://github.com/gravitational/webapps/issues/125
Replace `utm_source` and `utm_medium` with `product` and `version`.
Enterprise: 
- before: "https://gravitational.com/teleport/docs/admin-guide?utm_source=teleport&utm_medium=e_5.0.0#troubleshooting"
- after: "https://gravitational.com/teleport/docs/admin-guide?product=teleport&version=e_5.0.0#troubleshooting"
OSS: 
- before: "https://gravitational.com/teleport/docs/admin-guide?utm_source=teleport&utm_medium=oss_5.0.0#troubleshooting"
- after: "https://gravitational.com/teleport/docs/admin-guide?product=teleport&version=oss_5.0.0#troubleshooting"
> Drop UTM link prefixes

- packages/teleport/src/console/components/DocumentSsh/useSshSession.ts
work around for: https://github.com/gravitational/teleport/issues/4025
Work around for now, to handle closing tabs for exec command errors.
> Work around for close events on ssh errors in Client

- packages/teleport/src/console/components/DocumentSsh/ActionBar/ActionBar.jsx
fixes https://github.com/gravitational/teleport/issues/4235
- `flex: 0 0` was canceling `height: 32px`, so the height never mattered here (regardless of browser), so removed both
- `flex: 0 0` the third value is flex-basis which is set to 0. In safari this makes the ActionBar fall/collapse behind the xterm container.
I think this is what we wanted to achieve: https://css-tricks.com/almanac/properties/f/flex/#flex-none
But it isn't necessary b/c the icons sizes are fixed.
manually tested the icons showed in safari/firefox/chrome in mac/linux
> Remove unnecessary css

- packages/teleport/src/services/ssh/ssh.ts
fixes https://github.com/gravitational/teleport/issues/4143
Display hostname instead of nodes UUID (which is less readable and relatable)
- Include serverID and clusterID when making request for a new session
- serverID is required to look up nodes to get its hostname
- include serverId as fallback for hostname to prevent hostname part of tab title to be blank b/c proxy <4.4 returns empty hostname 
https://github.com/gravitational/teleport/pull/4239
First time connecting through UUID and hostname:
First time connecting through ip address:
> Set server/cluster ID for new session requests

- packages/teleport/src/dashboard/People/Users/UserDelete/UserDelete.tsx
- packages/teleport/src/dashboard/People/Users/UserDelete/__snapshots__/UserDelete.story.test.tsx.snap
part of https://github.com/gravitational/teleport/issues/4240
- [updated] Manually set attempts to prevent error about `updating unmounted component`, and to handle (prevent) closing dialog when there are errors
https://github.com/gravitational/teleport.e/pull/157
> Prevent closing when there is an error with deleting user

- packages/teleport/src/console/components/DocumentSsh/useSshSession.ts
resolves https://github.com/gravitational/webapps/issues/133
Removed checking for error keywords for close events.
Tested the error path that handles this error after removal:
> Remove checking for keywords for close event

- Dockerfile
We're running gh directly on the host now that https://github.com/gravitational/ops/pull/171 has been merged, so there's no need to install it inside the Docker image.
> Remove gh from web-apps Docker image

- packages/teleport/src/AppLauncher/useAppLauncher.ts
- packages/teleport/src/Apps/Apps.story.tsx
- packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
- packages/teleport/src/config.ts
- packages/teleport/src/features.ts
- packages/teleport/src/services/apps/apps.ts
- packages/teleport/src/services/apps/makeApps.ts
- packages/teleport/src/services/user/makeAcl.ts
This PR implements additional requirements for AAP 
1. When redirecting to AppLauncher, provide PublicAddr and ClusterName parameters (if available)
> use publicAddr and clusterName URL parameters to launch apps.

- packages/teleport/src/Apps/Apps.tsx
- packages/teleport/src/Apps/ButtonAdd.tsx
- packages/teleport/src/Apps/Empty/Empty.tsx
- packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
- packages/teleport/src/Apps/useApps.ts
- packages/teleport/src/Nodes/ButtonAdd.tsx
- packages/teleport/src/Nodes/Nodes.story.tsx
- packages/teleport/src/Nodes/Nodes.tsx
- packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
- packages/teleport/src/Nodes/useNodes.ts
- packages/teleport/src/TopBar/useTopBar.ts
- packages/teleport/src/types.ts
- packages/teleport/src/useStickyClusterId.ts
A minor change that disables create buttons on leaf clusters
> Disable AddServer and AddApp buttons on leaf clusters

- packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
- packages/teleport/src/Nodes/AddNode/Manually/Manually.tsx
- packages/teleport/src/config.ts
resolve https://github.com/gravitational/teleport/issues/4936
- Add `authType` field to config
- Grab `authType` from config instead of hard coding for manual step flag `--auth`
merge first https://github.com/gravitational/teleport/pull/4946
> Grab auth type from config

- packages/teleport/src/AuthConnectors/templates/oidc.yaml
- packages/teleport/src/AuthConnectors/templates/saml.yaml
When we create a Teleport Cloud instance we've a default role `admin`, customers are getting stuck because the example contents points to `admins`.  
I think this should fix it? If not; let me know where to send the PR.
> Set default role to 'admin' vs 'admins'

- packages/teleport/src/Apps/AddApp/Automatically/Automatically.tsx
resolves https://github.com/gravitational/teleport/issues/4953
- replace URL object app name check with regex (same regex as the backend uses):
https://github.com/kubernetes/apimachinery/blob/release-1.20/pkg/util/validation/validation.go#L219
> Replace app name check with regex

- packages/teleport/src/Recordings/RecordList.tsx
- packages/teleport/src/services/audit/types.ts
Set the node to `$cluster/$namespace/$pod` instead of leaving it blank.
Updates https://github.com/gravitational/teleport/issues/5212
> Populate "Node" name in k8s session recordings

- packages/shared/components/FormInvite/FormInvite.tsx
- packages/teleport/src/services/auth/auth.js
- packages/teleport/src/services/auth/auth.test.js
resolves https://github.com/gravitational/teleport/issues/5397
For screens that used u2f (Login, Invite/Reset), on submit, checks if u2f object exists in browser window before making calls, and returns proper error message. 
From research, there is still no support for fido u2f on safari, however there is support for fido2//webauthn (as with other major browsers)
Tested u2f login on:
- mac browsers: safari, firefox, google
- linux browsers: firefox, google
safari
> Check for browser u2f support

- packages/shared/hooks/useAttemptNext.ts
- packages/teleport/src/Apps/AddApp/AddApp.story.tsx
- packages/teleport/src/Roles/DeleteRole/DeleteRole.tsx
The run method of the `useAttemptNext` hook swallows the error thus preventing the Delete Role dialog to handle the error.
> Fix error handling on the Delete Role Dialog

- packages/teleport/src/AuthConnectors/DeleteConnectorDialog/DeleteConnectorDialog.tsx
- packages/teleport/src/Roles/DeleteRole/DeleteRole.tsx
- packages/teleport/src/TrustedClusters/DeleteTrust/DeleteTrust.tsx
- packages/teleport/src/Users/UserDelete/UserDelete.tsx
- packages/teleport/src/Users/UserDelete/__snapshots__/UserDelete.story.test.tsx.snap
- Similar bug found/fixed in DeleteConnectorDialog as https://github.com/gravitational/webapps/pull/231
- Replaced error banner placements at top in consistent manner among: trusted cluster, user, role, connectors
> Fix delete cn err handling and consistent error banner placement

- packages/shared/components/TextEditor/TextEditor.jsx
Fixes error messages produced when clicking on "Details" on event dialogue:
Disable use of web workers (syntax validators) b/c they are not used. Currently, we only use two modes json and yaml. json is used as read only mode, and yaml doesn't have syntax validating workers
> Disable use of web workers in ace editor

- packages/teleport/src/services/auth/auth.js
The API now returns `u2f_challenges`, a new field with details of all
registered devices. If this field is present, pass it through to the JS
U2F API to accept any of the registered keys.
Related: https://github.com/gravitational/teleport/pull/5837
> mfa: support multiple U2F devices on login

- packages/shared/components/FormInvite/FormInvite.tsx
- packages/shared/components/FormInvite/TwoFaInfo.tsx
- packages/shared/components/FormLogin/FormLogin.story.tsx
- packages/shared/components/FormLogin/FormLogin.tsx
- packages/shared/services/types.ts
- packages/teleport/src/Invite/Invite.story.js
- packages/teleport/src/Invite/Invite.test.js
- packages/teleport/src/Invite/__snapshots__/Invite.test.js.snap
- packages/teleport/src/Login/Login.story.tsx
- packages/teleport/src/Login/Login.test.tsx
- packages/teleport/src/Login/Login.tsx
- packages/teleport/src/Login/useLogin.ts
- packages/teleport/src/services/auth/auth.js
If both OTP and U2F are allowed by the server, give user a dropdown to
pick the right method.
During registration/reset, default to OTP when multiple MFA methods are
supported.
bug fix: https://github.com/gravitational/teleport/pull/5995
Screenshots with `second_factor: optional`:
- none for users who dont have mfa enrolled
- login clicked with U2F
- login with TOTP
> Support multiple MFA methods on login

- packages/teleport/src/components/EventRangePicker/Custom/Custom.jsx
fixes https://github.com/gravitational/teleport/issues/5427
The `7 day` selector chose dates with clock at start of day and end of day. The react day picker library clock started (for me) at 12pm. So to fix the clock inconsitency, converted the time given back from library to `start` and `end` of day.
> Consistent day picker and prettified file

- packages/teleport/src/lib/term/terminal.js
For example, Safari does not support U2F.
> terminal: check whether the browser supports U2F

- packages/shared/hooks/useAttemptNext.ts
- packages/teleport/src/Console/useOnExitConfirmation.ts
- packages/teleport/src/Main/Main.tsx
- packages/teleport/src/Main/index.ts
- packages/teleport/src/config.ts
- packages/teleport/src/services/localStorage/localStorage.ts
- packages/teleport/src/services/localStorage/types.ts
- packages/teleport/src/services/session/index.ts
- packages/teleport/src/services/session/makeSession.ts
- packages/teleport/src/services/session/session.ts
- packages/teleport/src/services/session/types.ts
part of https://github.com/gravitational/teleport/issues/4937
- Renew session endpoint now returns a new field `sessionExpires`. This is the absolute time the web session will expire for the most recently consumed access request. This is the value used in the switchback countdown
- Refactored how bearer token is being set
~~- Added local storage reload broadcaster to be able to reload opened tabs after user assumes a role or switches back to their default roles. This will be important when user switches back from higher privilege to lower privilege especially when they are connected to a node.~~
~~- Added ability to force reload to prevent confirmation pages (terminal) from reloading tabs~~
> Update renew session response and renew URL

- README.md
- packages/teleport/src/Console/DocumentNodes/DocumentNodes.story.tsx
- packages/teleport/src/Nodes/fixtures/index.ts
- packages/teleport/src/components/NodeList/NodeList.tsx
- packages/teleport/src/services/nodes/makeNode.ts
- packages/teleport/src/services/nodes/types.ts
This PR addresses #268 
Users should be able to search through nodes by typing in the exact label/tag in the search bar. (eg. typing `arch: x86_64` in the search bar should return all nodes with `arch: x86_64` in its table column).
Instead of each node storing its labels as an array of objects (eg. `[{name: value}]`), it now stores them as an array of strings (eg. `["name: value"]`). This makes it possible for the labels to be directly compared against the string entered in the search bar, allowing for better and more predictable results when searching.
> Fix not being able to filter nodes by searching exact label

- packages/teleport/src/Databases/Databases.story.test.tsx
- packages/teleport/src/Databases/Databases.story.tsx
- packages/teleport/src/Databases/Databases.tsx
- packages/teleport/src/Databases/__snapshots__/Databases.story.test.tsx.snap
This PR resolves #270 
Add attempt states for the Database table. If the state is `Success`, display the list of databases. If the state is `Loading`, display  an animated loading indicator. If the state is `Failed` display an alert box with the error message. Add snapshot for `Failed` state.
Use prop `attempt` to contain information about the attempt (eg. status, statusText). When rendering the `Databases`, render the appropriate UI based on the `attempt.state`. Create a snapshot test for `Failed` state.
> Add database table attempt states (Success, Loading, Failed)

- packages/teleport/src/Databases/DatabaseList/DatabaseList.tsx
- packages/teleport/src/Databases/Databases.story.tsx
- packages/teleport/src/Databases/Databases.tsx
- packages/teleport/src/Databases/__snapshots__/Databases.story.test.tsx.snap
- packages/teleport/src/Databases/useDatabases.ts
- packages/teleport/src/Main/Main.story.tsx
- packages/teleport/src/Main/fixtures/index.ts
- packages/teleport/src/features.ts
- packages/teleport/src/services/databases/databases.test.ts
- packages/teleport/src/services/databases/databases.ts
- packages/teleport/src/services/databases/makeDatabase.ts
- packages/teleport/src/services/user/makeAcl.ts
- packages/teleport/src/services/user/types.ts
- packages/teleport/src/services/user/user.test.ts
- packages/teleport/src/stores/storeUserContext.ts
- packages/teleport/src/teleportContext.tsx
This PR resolves #272  
Create a custom `useDatabases` hook. Create `Container` component. Register databases as a feature and add it to the side nav. Update Main.story to include it and to use the hook. Updated the enterprise submodule as well.
Created a `useDatabases` hook that uses `useAttemptNext` to set the `attempt` state based on the success of the database fetching, in order to display an error or a loading icon. Registered databases as a feature by creating a `FeatureDatabases` class in `features.ts`, which also adds it to the side nav. Also added it to `Main.story`. Updated the `feature.ts` and `Main.story` of `webapps.e` and made a PR to that repo which you can find [here](https://github.com/gravitational/webapps.e/pull/47). The e-ref will be updated later when merging.
Also …
> Create useDatabases hook, container, Register feature and update Main.story

- packages/teleport/src/AppLauncher/useAppLauncher.ts
- packages/teleport/src/config.ts
- packages/teleport/src/services/apps/apps.ts
Fixes https://github.com/gravitational/teleport/issues/6551, based on https://github.com/gravitational/teleport/pull/6449.
I tried to incorporate the recommendations from #235, feel free to adapt further according to your coding conventions.
> Use dedicated API for app FQDN resolving

- packages/teleport/src/services/session/session.ts
fixes https://github.com/gravitational/teleport/issues/6890
the renew token endpoint expects a request body, sending an empty JSON object is equivalent to 
```
{
requestId: '',
switchback: false,
}
```
> Set default on empty renew session request

- packages/teleport/src/services/links.ts
This PR contains minor refactoring of `getLink` function return value in services.
The reason for the change is to export the defined const and use it for filtering purposes in webapps.e.
> Refactor services get link return value

- Dockerfile
Fix a character class workaround in the Dockerfile so the repository builds correctly without `packages/webapps.e/`.
Fixes #351.
> Allow webapps to build without e

- packages/teleport/src/Recordings/RecordList.tsx
- packages/teleport/src/Recordings/Recordings.tsx
- packages/teleport/src/Recordings/__snapshots__/Recordings.story.test.tsx.snap
- packages/teleport/src/services/audit/audit.ts
- packages/teleport/src/services/audit/types.ts
- packages/teleport/src/useAuditEvents.ts
In response to: https://github.com/gravitational/teleport/pull/7231
- Use filter `session.end` to retrieve events for session recording screen
- Add pagination to session recordings list
> Use filter `session.end` to retrieve events for session recording screen

- packages/teleport/src/Recordings/RecordList.tsx
- packages/teleport/src/Recordings/Recordings.tsx
- packages/teleport/src/Recordings/__snapshots__/Recordings.story.test.tsx.snap
- packages/teleport/src/services/audit/audit.ts
- packages/teleport/src/services/audit/types.ts
- packages/teleport/src/useAuditEvents.ts
backport (#339)
* Add pagination to recording screen
> [backport v6.2] Use filter `session.end` to retrieve events for session recording screen

- packages/teleport/src/TrustedClusters/TrustedClusters.story.tsx
- packages/teleport/src/TrustedClusters/TrustedList/TrustedListItem.tsx
Fix over flowing of long cluster name
before:
after:
> Fix trusted cluster title styling

- packages/teleport/src/services/auth/auth.js
This PR resolves https://github.com/gravitational/teleport/issues/7985
Fix the browser-breaking error that is caused when the user tries to sign up with some characters (such as cyrillic alphabet characters)
We use `window.btoa()` to encode the password string in base64 before it is sent to the backend. However, the `window.btoa()` function only accepts strings with characters within the [Latin-1 character set](https://kb.iu.edu/d/aepu), trying to pass in a string containing characters beyond this range will trigger a `The string to be encoded contains characters outside of the Latin1 range` exception.
This solution from the [MDN Docs](https://developer.mozilla.org/en-US/docs/Glossary/Base64) works by first using `encodeURIComponent()` to percent-encode the special characters in UTF-8, …
> Fix base64 encoding for passwords on signup

- packages/design/src/DataTable/Paged/Paged.jsx
- packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
- packages/teleport/src/Databases/__snapshots__/Databases.story.test.tsx.snap
- packages/teleport/src/Kubes/__snapshots__/Kubes.story.test.tsx.snap
- packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
- packages/teleport/src/Recordings/__snapshots__/Recordings.story.test.tsx.snap
- packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
- packages/teleport/src/Users/__snapshots__/Users.story.test.tsx.snap
This PR resolves https://github.com/gravitational/webapps/issues/388
In some cases the table could exceed the width of its parent and cause it to be misaligned with the pager section above it. this caused it to look clipped and broken.
The issue was that the pager section was respecting the parent div's width, while the table section was overflowing. Adding a `min-width: min-content` to the parent div ensures that it will always be at least as wide as its widest child, and the pager section's width can match and be aligned with the table regardless of how wide it is.
Also fixed the rounded corners so that the table doesn't have rounded corners if the pager section is above it.
> Fix broken paged table layout

- packages/shared/components/FormInvite/FormInvite.story.tsx
- packages/shared/components/FormInvite/FormInvite.tsx
- packages/shared/components/FormInvite/TwoFaInfo.tsx
- packages/shared/components/FormInvite/__snapshots__/FormInvite.story.test.tsx.snap
- packages/shared/components/FormLogin/FormLogin.story.test.tsx
- packages/shared/components/FormLogin/FormLogin.story.tsx
- packages/shared/components/FormLogin/FormLogin.test.tsx
- packages/shared/components/FormLogin/FormLogin.tsx
- packages/shared/components/FormLogin/__snapshots__/FormLogin.story.test.tsx.snap
- packages/teleport/src/Invite/__snapshots__/Invite.test.tsx.snap
- packages/teleport/src/Login/Login.test.tsx
- packages/teleport/src/components/MfaDeviceList/MfaDeviceList.tsx
- packages/teleport/src/components/MfaDeviceList/RemoveDialog/RemoveDialog.tsx
- packages/teleport/src/components/MfaDeviceList/RemoveDialog/index.ts
- packages/teleport/src/components/MfaDeviceList/index.ts
- packages/teleport/src/config.ts
- packages/teleport/src/services/mfa/index.ts
- packages/teleport/src/services/mfa/makeMfaDevice.ts
- packages/teleport/src/services/mfa/mfa.ts
- packages/teleport/src/services/mfa/types.ts
- packages/teleport/src/services/mfa/utils.ts
Changed the way we call MFA devices after discussing with @klizhentas and @kimlisa .
Moved MFA logic to OSS for the upcoming MFA device management feature and also to reduce the scope of the PR in `webapps.e`.
The back-end MFA-related endpoints have been moved to the OSS cfg, and I created a new `MfaService` for MFA-related logic, this service will also be used by the account dashboard device management.
We previously had inconsistent and sometimes confusing naming when it came to MFA devices. We now call them "Two-Factor Devices".
- "TOTP" is now "Authenticator App".
- "U2F" is now "Hardware Key".
The flows for resetting `totp` and `u2f` have been combined into one, there is no longer a "Lost U2F Key?"/"Lost Two-Factor Token?", but a single "Lost Two-Factor Device?".
> MFA-related Language Changes & Move MFA logic to OSS 

- packages/teleport/src/Desktops/useDesktops.ts
- packages/teleport/src/Nodes/useNodes.ts
- packages/teleport/src/lib/util.ts
After reviewing with Sasha yesterday we agreed that desktops should open in a new tab, not a new window.
This pulls the `openNewTab` function out into a new file `teleport/lib/utils.ts`, since I am unaware of another appropriate util file (let me know if you know of a better place).
> moves openNewTab into a utils file and uses it for Desktop

- packages/teleport/src/DesktopSession/TdpClientCanvas.tsx
- packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
- packages/teleport/src/lib/tdp/client.ts
- packages/teleport/src/lib/tdp/codec.ts
Things weren't working in Safari and FF so using the standard onload function to ensure that they do.
> cross browser

- packages/teleport/src/Desktops/DesktopList/DesktopList.tsx
We currently only support Windows, and for hosts discovered via
LDAP we automatically apply a teleport.dev/os label which is more
specific than "Windows", so remove the column to avoid repeating
the same information multiple times.
> desktop access: remove OS column

- packages/teleport/src/Account/Account.tsx
- packages/teleport/src/features.ts
- packages/teleport/src/teleportContext.tsx
- packages/teleport/src/types.ts
This PR allows SSO users to access the account dashboard so they can manage their MFA devices/recovery codes. The "Change Password" tab will be hidden from them.
> Account dashboard support for SSO users

- jest.config.js
Ran into drone test errors in snapshots:
```
-           Created: Fri Aug 30 2019 04:00:00 GMT-0700 (Pacific Daylight Time)
+           Created: Fri Aug 30 2019 11:00:00 GMT+0000 (Coordinated Universal Time)
```
> State timezone for consistent dates in tests

- packages/teleport/src/services/auth/auth.ts
- packages/teleport/src/services/auth/index.ts
- packages/teleport/src/services/auth/makeMfa.ts
- packages/teleport/src/services/auth/makeRecoveryCodes.ts
- packages/teleport/src/services/auth/types.ts
part of https://github.com/gravitational/teleport.e/issues/323
- Moved recovery code typing and make response to open source
- Fixes a regression bug I introduced where firefox still requires global setting of appId and challenges whereas chrome looks for it among the registered keys
https://github.com/gravitational/webapps.e/pull/84
> Add created date to recovery codes respones

- packages/teleterm/package.json
- packages/teleterm/src/boot.tsx
- packages/teleterm/src/mainProcess/mainProcess.ts
- packages/teleterm/src/preload.ts
- packages/teleterm/src/services/logger/index.ts
- packages/teleterm/src/services/logger/loggerService.ts
- packages/teleterm/src/services/pty/ptyProcess.ts
- packages/teleterm/src/types.ts
- packages/teleterm/src/ui/components/CatchError/CatchError.jsx
- packages/teleterm/src/ui/utils/rendererLogger.ts
- yarn.lock
The `loggerService` allows logging events to a file. 
It is initialised separately for each process.
To use logger outside of the renderer process it has to be imported from `services/logger`.  In `renderer` process it's available in `window.electron` - I created an alias (`renererLogger` - not sure about this).
Examples of output:
`browser.log`
```
[15-11-21 16:25:08] [Main Process] error: tshd failed to start Error: spawn /Users/grzegorz/code/webapps/build/tsh ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
at onErrorNT (internal/child_process.js:465:16)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
`renderer.log`
```
[15-11-21 14:22:03] [Uncaught Error] error: Error: Pty Error
at TtyTerminal.open …
```
> Add logging to file

- packages/teleport/src/Apps/Apps.tsx
- packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
- packages/teleport/src/Databases/Databases.tsx
- packages/teleport/src/Databases/__snapshots__/Databases.story.test.tsx.snap
- packages/teleport/src/Kubes/Kubes.tsx
- packages/teleport/src/Kubes/__snapshots__/Kubes.story.test.tsx.snap
- packages/teleport/src/Nodes/Nodes.tsx
- packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
- packages/teleport/src/components/Empty/Empty.test.tsx
- packages/teleport/src/components/Empty/Empty.tsx
This PR resolves https://github.com/gravitational/teleport/issues/8721
Changes the text displayed when there are no resources in a list to be more accurate and take into account the fact that the reason why it is empty may be because the user doesn't have the permissions to view that list.
> Make language for empty resources list more accurate

- packages/build/index.ejs
- packages/teleport/src/Invite/CardWelcome.tsx
- packages/teleport/src/Invite/Invite.story.tsx
- packages/teleport/src/Invite/Invite.test.tsx
- packages/teleport/src/Invite/Invite.tsx
- packages/teleport/src/config.ts
Alternate implementation of https://github.com/gravitational/webapps/pull/475
Adds a new `/continue` route for the invite/reset form that the user gets to by first clicking the button on the initial prompt. This is to prevent crawlers (eg. in gmail) from triggering the OTP QR code generation before the user.
> Add prompt prior to form for Invite and Reset

- packages/teleport/src/DesktopSession/DesktopSession.tsx
- packages/teleport/src/DesktopSession/TdpClientCanvas/TdpClientCanvas.tsx
- packages/teleport/src/DesktopSession/TdpClientCanvas/useTdpClientCanvas.tsx
- packages/teleport/src/DesktopSession/useDesktopSession.tsx
- packages/teleport/src/Desktops/DesktopList/DesktopList.tsx
- packages/teleport/src/Desktops/DesktopList/index.ts
- packages/teleport/src/Desktops/Desktops.story.tsx
- packages/teleport/src/Desktops/useDesktops.ts
- packages/teleport/src/config.ts
- packages/teleport/src/lib/tdp/client.ts
- packages/teleport/src/services/desktops/desktops.ts
Backports https://github.com/gravitational/webapps/pull/448 and https://github.com/gravitational/webapps/pull/480, which are needed to update webassets to keep the client compatible with an impending Teleport proxy patch release that will include https://github.com/gravitational/teleport/pull/9201
> desktop access backports

- .cloudbuild/ci/test.yaml
Uses the existing webapps docker-based test by piggy-backing on GCB's ability to build docker images. The tests being run are a by product of the image being built, and the image is then discarded.
> GCB build support

- packages/teleport/src/Audit/Audit.tsx
- packages/teleport/src/Audit/EventList/EventList.tsx
- packages/teleport/src/Audit/useAuditEvents.ts
- packages/teleport/src/Recordings/Recordings.story.tsx
- packages/teleport/src/Recordings/Recordings.tsx
- packages/teleport/src/Recordings/RecordingsList.tsx
- packages/teleport/src/Recordings/useRecordings.ts
- packages/teleport/src/components/EventRangePicker/EventRangePicker.tsx
- packages/teleport/src/components/EventRangePicker/index.ts
- packages/teleport/src/components/EventRangePicker/utils.ts
- packages/teleport/src/config.ts
- packages/teleport/src/features.ts
- packages/teleport/src/services/recordings/index.ts
- packages/teleport/src/services/recordings/makeRecording.ts
- packages/teleport/src/services/recordings/recordings.ts
- packages/teleport/src/services/recordings/types.ts
- packages/teleport/src/stores/storeUserContext.ts
- packages/teleport/src/teleportContext.tsx
This PR resolves https://github.com/gravitational/webapps/issues/459
This PR resolves https://github.com/gravitational/webapps/issues/406
Separate the recordings service from the other events service, this allows us to use RBAC to control access to recordings.
> Add Separate Recordings List Service

- packages/teleterm/src/ui/DocumentTerminal/DocumentTerminal.tsx
- packages/teleterm/src/ui/DocumentTerminal/Terminal/Terminal.tsx
- packages/teleterm/src/ui/DocumentTerminal/Terminal/xterm.ts
Handles `\033[8;30;80t` sequence.
Imported xterm styling from the `teleport` because it has `overflow: auto` set and I wanted to avoid copy&paste.
> Make xterm understand resize sequence

- packages/shared/components/Select/types.ts
- packages/teleport/src/components/SelectFilters/Pager.tsx
- packages/teleport/src/components/SelectFilters/SelectFilters.story.tsx
- packages/teleport/src/components/SelectFilters/SelectFilters.tsx
- packages/teleport/src/components/SelectFilters/usePages.ts
- Allows pagination for select filter.
- Default is to list 100 filter per page.
- Solves UI freezing from react select trying to list every filter
- searching searches through the entire list of filters (not just what is currently listed)
- Copy and pasted `usePages` and `Pager` from table component
Pages
No pages
> Select filter paginate

- packages/teleport/src/Login/LoginFailed.tsx
- packages/teleport/src/config.ts
This PR adds a new error message for when a user successfully authenticates with SSO but fails to match any roles.
Part of gravitational/teleport#6409.
> Add error message for failed SSO authorization

- packages/design/src/Indicator/Indicator.test.js
- packages/design/src/utils/testing.tsx
- packages/shared/components/FormPassword/FormPassword.test.tsx
- packages/shared/components/Validation/useRule.test.js
- packages/shared/libs/stores/useStore.test.tsx
- packages/teleport/src/Account/ManageDevices/ManageDevices.test.tsx
- packages/teleport/src/Clusters/Clusters.story.test.tsx
- packages/teleport/src/Console/DocumentNodes/DocumentNodes.story.test.tsx
- packages/teleport/src/Login/Login.test.tsx
- packages/teleport/src/Recordings/Recordings.story.test.tsx
- packages/teleport/src/Welcome/Welcome.test.tsx
- packages/teleport/src/components/FormLogin/FormLogin.test.tsx
`waitForElement` and `wait` have been removed from the `@testing-library` after version update.
These functions were re-exported by `design/utils/testing`, but in order to have the same API as `@testing-library` I'm replacing them with `waitFor`.
> Replace both `waitForElement` and `wait` with `waitFor` in tests

- .drone.yml
Disables the drone pull request trigger, leaving the `push` trigger for post-merge builds.
> Disable drone for PR

- packages/design/src/DataTableNext/Cells.tsx
- packages/design/src/DataTableNext/StyledTable.tsx
- packages/design/src/DataTableNext/Table.tsx
- packages/design/src/DataTableNext/types.ts
- packages/design/src/DataTableNext/useTable.ts
- packages/teleport/src/Apps/__snapshots__/Apps.story.test.tsx.snap
- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/Clusters/__snapshots__/Clusters.story.test.tsx.snap
- packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
- packages/teleport/src/Databases/DatabaseList/DatabaseList.tsx
- packages/teleport/src/Databases/__snapshots__/Databases.story.test.tsx.snap
- packages/teleport/src/Desktops/DesktopList/DesktopList.tsx
- packages/teleport/src/Kubes/KubeList/KubeList.tsx
- packages/teleport/src/Kubes/__snapshots__/Kubes.story.test.tsx.snap
- packages/teleport/src/Nodes/__snapshots__/Nodes.story.test.tsx.snap
- packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
- packages/teleport/src/Users/UserList/UserList.tsx
- packages/teleport/src/Users/__snapshots__/Users.story.test.tsx.snap
- packages/teleport/src/components/NodeList/NodeList.tsx
Makes some improvements to Table V2.
Styled Components requires a `className` prop for custom components, this was missing and so custom styles were not applying properly. Added the `className` component to Table.
Make `TextCell` show empty text if data is missing rather than `undefined`.
Make `vertical-align: baseline` the default style for `td`'s so we don't have to keep adding it to Tables.
Add an optional `style` prop for passing in custom styles.
> Table V2 Tweaks

- packages/teleport/src/Audit/EventList/EventTypeCell.tsx
- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/Audit/fixtures/index.ts
- packages/teleport/src/services/audit/makeEvent.ts
- packages/teleport/src/services/audit/types.ts
Backport of #532 with no practical changes.
Subordinate to
* https://github.com/gravitational/teleport/pull/9786
> [v7] backport #532 (`access_request.delete` event)

- packages/teleport/src/Audit/EventList/EventTypeCell.tsx
- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/Audit/fixtures/index.ts
- packages/teleport/src/services/audit/makeEvent.ts
- packages/teleport/src/services/audit/types.ts
Backport of #532 with no practical changes.
Subordinate to
* https://github.com/gravitational/teleport/pull/9787
> [v8] backport #532 (`access_request.delete` event)

- packages/teleport/src/Audit/EventList/EventTypeCell.tsx
- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/Audit/fixtures/index.ts
- packages/teleport/src/services/audit/makeEvent.ts
- packages/teleport/src/services/audit/types.ts
Backport of #532 with no practical changes.
Subordinate to
* https://github.com/gravitational/teleport/pull/9785
> [v6.2] backport #532 (`access_request.delete` event)

- packages/teleterm/src/mainProcess/mainProcess.ts
By default `Ctrl-W` event is captured by `xterm`. When there are no tabs open it runs `Close Window` action from app menu.
I changed the default menu to prevent closing the app (template took from [here](https://www.electronjs.org/docs/latest/api/menu#examples)). I removed `Close` option from `Window` on Linux and from `File` on MacOS (and some electron help items from `Help` menu).
> Remove the `Close window` item and electron help items from the app menu

- packages/teleport/src/Audit/EventList/EventTypeCell.tsx
- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/Audit/fixtures/index.ts
- packages/teleport/src/services/audit/makeEvent.ts
- packages/teleport/src/services/audit/types.ts
resolves https://github.com/gravitational/webapps/issues/493
This is how its normally defined in backend:
```
event = Event{
Name: X11ForwardEvent,
Code: X11ForwardCode,
}
```
1) Add event code (event.name) to `eventCodes` from `services/audit/types.ts`
2) Add event type (event.code) to our `RawEvents` type
3) Add event formatter to our `formatters` from `services/audit/makeEvent.ts`
4) Add a icon for event type to our `EventIconMap` from `Audit/EventList/EventTypeCell.tsx`
5) Add fixtures (raw json) to `events` for storybooking `Audit/fixtures/index.ts`
6) update snapshot
> Add x11 events

- packages/teleport/src/Audit/EventList/EventTypeCell.tsx
- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/Audit/fixtures/index.ts
- packages/teleport/src/services/audit/makeEvent.ts
- packages/teleport/src/services/audit/types.ts
resolves https://github.com/gravitational/webapps/issues/566
before style fix:
after style fix:
> Add session connect event

- packages/build/devserver/modifyResponse.js
6308951f548 changed the regexes used for CSRF & bearer tokens. The previous regexes were matching anything between the end of the `name` attribute and `/>`. The new regex assumes there's no space between the end of the `content` attribute and `/>`, but inspecting the `source` argument shows that there's indeed a space (at least on my machine).
https://github.com/gravitational/webapps/blob/6308951f54871a41a3d8516dad1855608a6182c9/packages/build/devserver/modifyResponse.js#L63-L66
This PR makes it so that the regex accepts an optional space before the end of the tag, just as the regex used to replace the tag in `target`:
https://github.com/gravitational/webapps/blob/6308951f54871a41a3d8516dad1855608a6182c9/packages/build/devserver/modifyResponse.js#L67-L74
> modifyResponse: Add optional space before /> to regex

- packages/teleterm/src/ui/components/VirtualScroll/VirtualScroll.story.tsx
- packages/teleterm/src/ui/components/VirtualScroll/VirtualScroll.tsx
- packages/teleterm/src/ui/components/VirtualScroll/index.ts
- packages/teleterm/src/ui/components/VirtualScroll/prepareVirtualScrollItems.ts
- packages/teleterm/src/ui/components/VirtualScroll/types.ts
- packages/teleterm/src/ui/components/VirtualScroll/useVirtualScrollNodes.tsx
The `VirtualScroll` component can render both simple lists and trees.
It doesn't provide any styling, everything should be configured using props and `Node` rendering function. 
Currently it's not used anywhere in `teleterm` due to design changes.
> Add `VirtualScroll` component

- packages/teleport/src/config.ts
- packages/teleport/src/services/recordings/recordings.ts
`clusterEventsRecordingsPath` respects rbac where clauses, so users won't see desktop sessions they don't have permission to play back in the Recordings table.
Corresponds with https://github.com/gravitational/teleport/pull/10325
> switch recordings service endpoint back to `clusterEventsRecordingsPath`

- packages/teleport/src/components/EventRangePicker/Custom/Custom.jsx
Fixes bug that caused an error if `to` was undefined when using the date picker.
With `momentjs`, if an inputted date was invalid or `undefined`, it would fallback to using the current date. However `date-fns` instead gives `Invalid Date` and this results in an error. This PR returns behaviour to the same way it was prior.
> Fix date picker

- packages/teleport/src/components/FormLogin/FormLogin.tsx
- packages/teleport/src/components/FormLogin/__snapshots__/FormLogin.story.test.tsx.snap
- packages/teleport/src/components/FormNewCredentials/FormNewCredentials.tsx
- packages/teleport/src/components/FormNewCredentials/__snapshots__/FormNewCredentials.story.test.tsx.snap
- packages/teleport/src/services/auth/auth.test.js
- packages/teleport/src/services/auth/auth.ts
** requires backporting to `v8`
u2f api no longer works for chrome ([since this month](https://www.yubico.com/blog/google-chrome-u2f-api-decommission-what-the-change-means-for-your-users-and-how-to-prepare/)), and when users try to log in or 'create account', the error is obscure or hidden (shows up in console log) so it appears to do nothing. Firefox still supports u2f (could not find when they are ending it). 
This PR checks if users are on chrome, to give a better error message. Same error message is shown to safari users.
> Add chrome as unsupported for U2F checks

- packages/teleterm/README.md
Just a single line change, I extracted the gRPC stuff in the Teleport repo (gravitational/teleport@a220e2d).
> Update command for generating gRPC files for Teleterm

- packages/teleport/src/Apps/AddApp/AddApp.tsx
- packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
- packages/teleport/src/Databases/AddDatabase/AddDatabase.story.tsx
- packages/teleport/src/Databases/AddDatabase/AddDatabase.test.tsx
- packages/teleport/src/Databases/AddDatabase/AddDatabase.tsx
- packages/teleport/src/Databases/Databases.tsx
- packages/teleport/src/Nodes/AddNode/AddNode.tsx
- packages/teleport/src/Nodes/AddNode/Manually/Manually.tsx
- packages/teleport/src/Nodes/AddNode/__snapshots__/AddNode.story.test.tsx.snap
- packages/teleport/src/Nodes/AddNode/useAddNode.ts
- packages/teleport/src/components/DownloadLinks/DownloadLinks.tsx
- packages/teleport/src/components/DownloadLinks/index.ts
- packages/teleterm/src/ui/DocumentCluster/ClusterResources/Applications/Applications.tsx
- packages/teleterm/src/ui/DocumentCluster/ClusterResources/Servers/Servers.tsx
- Change the file download link depending on the enterprise status of the deployment.
- Consolidate the links into a separate component.
Fixes: https://github.com/gravitational/teleport/issues/10341
> If running in enterprise version then provide the enterprise download links

- packages/teleport/src/Apps/Apps.story.test.tsx
- packages/teleport/src/Apps/useApps.ts
- packages/teleport/src/Console/consoleContext.tsx
- packages/teleport/src/Databases/useDatabases.ts
- packages/teleport/src/Desktops/useDesktops.ts
- packages/teleport/src/Kubes/useKubes.ts
- packages/teleport/src/Main/Main.story.tsx
- packages/teleport/src/Nodes/useNodes.ts
- packages/teleport/src/services/apps/apps.test.ts
- packages/teleport/src/services/apps/apps.ts
- packages/teleport/src/services/apps/makeApps.ts
- packages/teleport/src/services/apps/types.ts
- packages/teleport/src/services/databases/databases.test.ts
- packages/teleport/src/services/databases/databases.ts
- packages/teleport/src/services/databases/types.ts
- packages/teleport/src/services/desktops/desktops.test.ts
- packages/teleport/src/services/desktops/desktops.ts
- packages/teleport/src/services/desktops/types.ts
- packages/teleport/src/services/kube/kube.test.ts
- packages/teleport/src/services/kube/kube.ts
- packages/teleport/src/services/kube/types.ts
- packages/teleport/src/services/nodes/makeNode.ts
- packages/teleport/src/services/nodes/nodes.test.ts
- packages/teleport/src/services/nodes/nodes.ts
- packages/teleport/src/services/nodes/types.ts
Making changes in response to PR https://github.com/gravitational/teleport/pull/10598, where the api responses are different for our resource getters. Adds extra fields (startKey and totalCount) that are currently not used but will be in future work.
https://github.com/gravitational/webapps.e/pull/122
> Edit api response for getXXX (resources)

- packages/teleport/src/Player/DesktopPlayer.tsx
- packages/teleport/src/Player/ProgressBar/ProgressBar.tsx
- packages/teleport/src/Player/ProgressBar/ProgressBarDesktop.tsx
- packages/teleport/src/Player/ProgressBar/index.tsx
Previously, desktop sessions recorded at one aspect ratio and played at another could look insane (see the screenshot in https://github.com/gravitational/webapps/issues/587). These changes maintain the aspect ratio during playback.
Due to slight differences between the size available to the desktop session during recording, and the size available to the player, a session recorded and then played back in a browser window of precisely the same size may look something like this:
Note the black channels up and down the left and right size of the window, which are created by the same logic that creates the desirable, necessary black-space in the `Playback aspect ratio > recorded aspect ratio` screen shot above. I'm not ecstatic about how that looks, but am not sure precisely what to do about …
> Maintain aspect ratio on Desktop Playback

- packages/teleport/src/Support/Support.story.tsx
- packages/teleport/src/Support/Support.tsx
- packages/teleport/src/config.ts
Backport of https://github.com/gravitational/webapps/pull/580
teleport v8 backport: gravitational/teleport#10514
___
Show the reverse tunnel address on Help & Support screen.
On cloud instances, we use a custom reverse tunnel port for each tenant. In the UI, there is no way to know your reverse tunnel address, which is necessary when adding a trusted cluster.
This PR adds a new field under cluster information Public SSH Tunnel.
Screenshot: 
(new field `Public SSH Tunnel` at the bottom of **Cluster Information**)
> [v8 backport] Add public tunnel address

- packages/teleport/src/Roles/templates/role.yaml
Set v5 as the default and change the default resource rules to more limited RBAC then everything.  Addresses https://github.com/gravitational/teleport/issues/10807
> Update default roles template

- packages/shared/components/MenuSshLogin/MenuSshLogin.tsx
This prevents password managers like 1password from attempting to
autocomplete the SSH login, which is not a standard password field.
Fixes gravitational/teleport#10356
Co-authored-by: Lisa Kim <lisa@goteleport.com>
Backports #605
> [v9] Disable autocomplete on the SSH login input (#605)

- packages/teleport/src/Audit/EventList/EventTypeCell.tsx
- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/Audit/fixtures/index.ts
- packages/teleport/src/services/audit/makeEvent.ts
- packages/teleport/src/services/audit/types.ts
This event is emitted as a fallback if we encounter an event that
Teleport does not know how to interpret.
See: gravitational/teleport#10665
> Support the 'unknown' audit event

- packages/teleport/src/DesktopSession/__snapshots__/DesktopSession.story.test.tsx.snap
It seems we fixed a typo and forgot to update the snapshot, making `yarn test` fail
> [v9] Update snapshot

- packages/design/src/DataTable/types.ts
- packages/design/src/DataTable/useTable.ts
- packages/design/src/utils/match/index.ts
- packages/design/src/utils/match/match.ts
- packages/design/src/utils/match/matchers.ts
- packages/teleport/src/Account/ManageDevices/ManageDevices.story.tsx
- packages/teleport/src/Audit/EventList/EventList.tsx
- packages/teleport/src/Recordings/RecordingsList.tsx
- packages/teleport/src/Sessions/SessionList/SessionList.tsx
- packages/teleport/src/Support/Support.tsx
- packages/teleport/src/Support/__snapshots__/Support.story.test.tsx.snap
- packages/teleport/src/TrustedClusters/TrustedClusters.tsx
- packages/teleport/src/components/MfaDeviceList/MfaDeviceList.tsx
- packages/teleport/src/components/NodeList/NodeList.tsx
This PR resolves #629 
Fixes some table regressions and other improvements
- Added `searchableProps` to Table config to allow searching through the pieces of data that are part of the object but that aren't indexed by the table columns. 
- Added search functionality to arrays of objects and arrays of strings, this is useful in the case of searching through Active Sessions because you are now able to search by participants. 
- Added search functionality for booleans, eg. you can now search `tunnel` and get rows that have `tunnel: true`.
> Fix Table Regression Bugs

- packages/teleport/src/Audit/EventList/EventTypeCell.tsx
- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/Audit/fixtures/index.ts
- packages/teleport/src/services/audit/makeEvent.ts
- packages/teleport/src/services/audit/types.ts
> [backport v8] Support the 'unknown' audit event (#656)

- packages/teleport/src/Nodes/AddNode/useAddNode.test.ts
The test got backported from master that used new date-fns library.
But in v8, we are using moment, which resulted in a slightly diff
test result.
> Fix failing test in useAddNode.test in v8

- packages/teleterm/src/services/config/providers/keyboardShortcutsConfigProvider.ts
- packages/teleterm/src/ui/TabHost/TabHost.test.tsx
- packages/teleterm/src/ui/TabHost/TabHost.tsx
- packages/teleterm/src/ui/TabHost/useNewTabOpener.ts
- packages/teleterm/src/ui/TabHost/useTabShortcuts.ts
- packages/teleterm/src/ui/TabHost/useTabSortcuts.test.tsx
- packages/teleterm/src/ui/TopBar/Clusters/ClusterSelector/ClusterSelector.tsx
- packages/teleterm/src/ui/TopBar/Clusters/Clusters.tsx
- packages/teleterm/src/ui/TopBar/Clusters/ClustersFilterableList/ClusterItem.tsx
- packages/teleterm/src/ui/TopBar/Clusters/ClustersFilterableList/ClustersFilterableList.tsx
- packages/teleterm/src/ui/TopBar/Clusters/index.ts
- packages/teleterm/src/ui/TopBar/Clusters/useClusters.ts
- packages/teleterm/src/ui/TopBar/Connections/Connections.tsx
- packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionItem.tsx
- packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionsFilterableList.tsx
- packages/teleterm/src/ui/TopBar/TopBar.tsx
- packages/teleterm/src/ui/commandLauncher.ts
- packages/teleterm/src/ui/components/FilterableList/FilterableList.tsx
- packages/teleterm/src/ui/components/KeyboardArrowsNavigation/KeyboardArrowsNavigation.test.tsx
- packages/teleterm/src/ui/components/KeyboardArrowsNavigation/KeyboardArrowsNavigation.tsx
- packages/teleterm/src/ui/components/KeyboardArrowsNavigation/useKeyboardArrowsNavigation.ts
- packages/teleterm/src/ui/components/ListItem.tsx
- packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.test.ts
- packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
- packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts
- packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
A few notes:
1. I had to change `KeyboardArrowsNavigation` behaviour a bit: by default none of the items should be selected (`activeIndex: -1`) and when user starts searching then the first item should be selected (`activeIndex: 0`). I was wondering if we don't want to use `KeyboardArrowsNavigation` inside of `FilterableList`, but finally I decided not to do it and add a callback to `FilterableList` to have more flexibility (any thoughts about it?).
2. I reverted the change with providing `clusterUri` to the `DocumentService` (it was used only by `createClusterDocument()`). That document has to be created not only for root, but also for leaf clusters. 
3. I extracted logic for creating a new tab to the `useNewTabOpener` hook.
> Add clusters picker

- packages/build/package.json
- packages/teleterm/src/services/pty/ptyProcess.ts
- packages/teleterm/src/services/pty/ptyService.ts
- packages/teleterm/src/services/pty/types.ts
- packages/teleterm/src/ui/DocumentTerminal/useDocumentTerminal.ts
- packages/teleterm/src/ui/QuickInput/QuickInput.tsx
- packages/teleterm/src/ui/QuickInput/QuickInputList/QuickInputList.tsx
- packages/teleterm/src/ui/QuickInput/useQuickInput.ts
- packages/teleterm/src/ui/appContext.ts
- packages/teleterm/src/ui/commandLauncher.ts
- packages/teleterm/src/ui/services/clusters/clustersService.ts
- packages/teleterm/src/ui/services/quickInput/quickInputService.test.ts
- packages/teleterm/src/ui/services/quickInput/quickInputService.ts
- packages/teleterm/src/ui/services/quickInput/quickPickers.ts
- packages/teleterm/src/ui/services/quickInput/types.ts
- packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
- packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts
- packages/teleterm/src/ui/uri.ts
- yarn.lock
Possibly for later (not this PR)
* Take cursor index into account.
* Handle env vars before the command.
* `FOO=bar tsh ssh` should still offer autocomplete work.
* Perhaps this can be done when we implement a more sophisticated solution.
---
This PR so far implements only showing the suggestions in the UI, not actually picking them. This is what I'm going to work on next.
The biggest change compared to the previous command palette is that it was essentially a multi-stage UI which kept track of the "progress" through `picker` in `QuickInputService` state.
With autocomplete, the only state we need to keep track of is the input value. So I rewrote QuickInputService so that on each input change it just parses the whole input and then returns 
* autocomplete suggestions
* what picker to use
* …
> Implement new version of command bar

- packages/teleterm/src/ui/services/quickInput/quickInputService.test.ts
- packages/teleterm/src/ui/services/quickInput/quickInputService.ts
- packages/teleterm/src/ui/services/quickInput/quickPickers.test.ts
- packages/teleterm/src/ui/services/quickInput/quickPickers.ts
- packages/teleterm/src/ui/services/quickInput/types.ts
Also removes some leftovers from quick pickers.
> Launch unsupported invocations of tsh ssh in local shell

- packages/teleterm/src/ui/DocumentGateway/useDocumentGateway.ts
- packages/teleterm/src/ui/DocumentTerminal/useReconnect.ts
- packages/teleterm/src/ui/ServerConnect/useServerConnect.ts
- packages/teleterm/src/ui/TopBar/Connections/Connections.story.tsx
- packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionItem.tsx
- packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionsFilterableList.tsx
- packages/teleterm/src/ui/TopBar/Connections/ConnectionsIcon/ConnectionsIcon.tsx
- packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.ts
- packages/teleterm/src/ui/services/connectionTracker/types.ts
Also fixes a bug when connecting to server in a leaf cluster
> Display cluster name for each connection & add autoconnect 

- packages/build/package.json
- yarn.lock
Versions lower than 23.0.2 don't work on the newest macOS, see:
* electron-userland/electron-builder#6732
* electron-userland/electron-builder#6606
This is a major version bump to an "unreleased" version of electron-builder, but I think we should be fine. The only breaking changes I could find were in [the release notes of v23.0.0-alpha.0](https://github.com/electron-userland/electron-builder/releases/tag/v23.0.0-alpha.0) and they shouldn't affect us. [Upgrading to 23.0.3 is recommended](https://github.com/electron-userland/electron-builder/issues/6732#issuecomment-1073288437) for macOS 12.3 support.
> Update electron-builder to 23.0.3

- packages/teleport/src/Apps/AddApp/useAddApp.ts
- packages/teleport/src/Nodes/AddNode/useAddNode.test.ts
- packages/teleport/src/Nodes/AddNode/useAddNode.ts
- packages/teleport/src/config.ts
- packages/teleport/src/services/joinToken/index.ts
- packages/teleport/src/services/joinToken/joinToken.ts
- packages/teleport/src/services/joinToken/makeJoinToken.ts
- packages/teleport/src/services/joinToken/types.ts
- packages/teleport/src/services/nodes/index.ts
- packages/teleport/src/teleportContext.tsx
backport of https://github.com/gravitational/webapps/pull/672
should be merged only after the new enpoint is backported too (https://github.com/gravitational/teleport/pull/11256)
> [v9] Refactor join tokens generation to use new endpoint #683

- packages/build/.babelrc.js
Since this plugin was only enabled in the development, [css prop](https://styled-components.com/docs/api#css-prop) worked locally but didn't work in the bundled app.
The plugin also improves bundle size a bit (`2.36 MiB` vs `2.38 MiB` previously).
> Enable `babel-plugin-styled-components` in production and tests

- packages/teleterm/src/ui/TopBar/Clusters/ClusterSelector/ClusterSelector.tsx
- packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionItem.tsx
- packages/teleterm/src/ui/TopBar/Connections/ConnectionsIcon/ConnectionsIcon.tsx
Closes https://github.com/gravitational/webapps.e/issues/148 
Closes https://github.com/gravitational/webapps.e/issues/170
> Make connection icon bigger & fix compressed items on list

- packages/design/src/DataTable/useTable.ts
- packages/teleport/src/Sessions/SessionList/SessionList.tsx
- packages/teleport/src/Sessions/__snapshots__/Sessions.story.test.tsx.snap
Minor fix that fixes a vertical misalignment when text in the `Active Sessions` table wraps
> Fix vertical misalignment in Active Sessions table

- packages/teleterm/src/main.ts
This takes care of TEL-Q122-19 from the recent security audit.
At the moment we don't create new windows nor navigate away from the rendered app, so we can just block everything. Obviously when adding support for multiple windows we'll have to change that and use Node's URL parser, preferably.
To test this, I made it so that the table with servers renders a regular link next to each hostname. Shift + click tries to open the link in a new window.
Testing the `<webview>` tag required adding `webviewTag: true` to `webPreferences` of the `BrowserWindow`.
https://github.com/gravitational/webapps/blob/f8cfdf3839e9efa7faf9067e57c0442baab360c9/packages/teleterm/src/mainProcess/mainProcess.ts#L55-L59
> Limit navigation capabilities to reduce attack surface

- packages/teleterm/package.json
Our build system doesn't support arm64 for Mac releases yet (see gravitational/teleport#4226 for more information). Because of that, for the preview release we're likely going to have only the x64 version of Teleterm.
This means that the shipped version of tsh should also be the x64 version.
I tried to change electron-builder's config to use x64 for macOS, but the config options don't seem to work. I tried `mac.defaultArch` as well as changing `mac.target` in various ways but `electron-builder install-app-deps` just doesn't pick up those options. Both were set through `packages/teleterm/package.json`
> Use x64 arch when building & packaging Teleterm

- packages/teleterm/src/ui/App.tsx
- packages/teleterm/src/ui/DocumentCluster/ClusterResources/Applications/Applications.tsx
- packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/Databases.tsx
- packages/teleterm/src/ui/DocumentCluster/ClusterResources/Kubes/Kubes.tsx
- packages/teleterm/src/ui/DocumentCluster/ClusterResources/Servers/Servers.tsx
- packages/teleterm/src/ui/appContext.ts
- packages/teleterm/src/ui/boot.tsx
- packages/teleterm/src/ui/components/Notifcations/Notification.tsx
- packages/teleterm/src/ui/components/Notifcations/Notifications.story.tsx
- packages/teleterm/src/ui/components/Notifcations/Notifications.tsx
- packages/teleterm/src/ui/components/Notifcations/NotificationsHost.tsx
- packages/teleterm/src/ui/components/Notifcations/index.ts
- packages/teleterm/src/ui/components/Notifcations/types.ts
- packages/teleterm/src/ui/services/clusters/clustersService.test.ts
- packages/teleterm/src/ui/services/clusters/clustersService.ts
- packages/teleterm/src/ui/services/notifications/index.ts
- packages/teleterm/src/ui/services/notifications/notificationsService.ts
- packages/teleterm/src/ui/services/quickInput/quickInputService.test.ts
In some places informing the user about an error was not sufficient.
I added:
- standard, red labels over the tables in `ClusterResources` (servers, dbs, kubes, apps)
- notifications in other places, where we don't have an option to show static error label (closing db connection, synchronising root cluster) 
Notification component: 
(IMO this looks quite nice for someone with no design experience 🙂)
I also let the app render when the init function fails - this should make it easier to track why the app sometimes stops at `Loading`. 
Closes: https://github.com/gravitational/webapps.e/issues/151
> Improve error handling

- packages/teleterm/package.json
This reverts commit 276e9a97402bdffce2e0fbea2a781d51c30cbce3.
Turns out that for development, we need to use arm64 version of native
deps. The build server is going to use x64 anyway, as per the reverted
commit, but when making manual demo builds, we'll have to remember to
use x64 for Teleterm and tsh.
> Revert "Use x64 arch when building & packaging Teleterm"

- packages/teleterm/src/mainProcess/runtimeSettings.ts
While trying to fix the issue with tsh connection on startup, I tried to use the Logger that was already imported in `runtimeSettings`. It turned out that attempting to use it would always crash the app, as the logger from shared/libs/logger attempts to call `window`, which doesn't exist in the context of Electron main process.
So instead we just use the one from `teleterm/logger` which calls `console` directly.
> Use teleterm/logger in runtimeSettings

- packages/teleterm/src/main.ts
- packages/teleterm/src/mainProcess/fixtures/mocks.ts
- packages/teleterm/src/mainProcess/mainProcess.ts
- packages/teleterm/src/mainProcess/mainProcessClient.ts
- packages/teleterm/src/mainProcess/types.ts
- packages/teleterm/src/mainProcess/windowsManager.ts
- packages/teleterm/src/preload.ts
- packages/teleterm/src/services/fileStorage/fileStorage.ts
- packages/teleterm/src/services/fileStorage/fileStorageClient.ts
- packages/teleterm/src/services/fileStorage/fixtures/mocks.ts
- packages/teleterm/src/services/fileStorage/index.ts
- packages/teleterm/src/types.ts
- packages/teleterm/src/ui/appContext.ts
- packages/teleterm/src/ui/fixtures/mocks.ts
- packages/teleterm/src/ui/services/statePersistence/statePersistenceService.ts
Closes https://github.com/gravitational/webapps.e/issues/166
It also solves the problem of not saving the application state when it is closed immediately after an action.
> Store app size and position

- packages/teleport/src/Main/fixtures/index.ts
- packages/teleport/src/features.ts
- packages/teleport/src/services/user/makeAcl.ts
- packages/teleport/src/services/user/types.ts
- packages/teleport/src/services/user/user.test.ts
- packages/teleport/src/stores/storeUserContext.ts
- packages/teleport/src/teleportContext.tsx
Per a discussion in the community [Slack](https://goteleport.slack.com/archives/CEZH6UL64/p1649705079426479), its not uncommon for users to want to hide some of the feature tabs in the sidebar. This is currently possible for all features except Server access; these changes make the Server access tab configurable as well.
A user with this role
```
kind: role
metadata:
name: remove_servers
spec:
allow: {}
deny:
rules:
- resources: [node]
verbs: [list]
version: v5
```
will see a UI that looks like
ike
> Adds the Servers tab as a configurable UI feature

- packages/teleterm/webpack.renderer.extend.js
When packaged, the main window opens this file:
window.loadFile(path.join(__dirname, '../renderer/index.html'));
The assets are under ../renderer/assets, but since Webpack used absolute path for it, Electron tried to load them from /assets instead.
I'm not sure if that's the best way to modify our Webpack config, let me know if you have a better idea.
Fixes gravitational/webapps.e#153.
> Fix path to packaged assets in Teleterm

- packages/teleterm/src/ui/DocumentGateway/DocumentGateway.tsx
- packages/teleterm/src/ui/DocumentGateway/useDocumentGateway.ts
Sasha asked about this change on Slack. For now I just copied the relevant pieces from `TextSelectCopy` implementation.
> DocumentGateway: Replace the Copy button with a Run button

- packages/teleterm/src/ui/TopBar/Identity/Identity.tsx
- packages/teleterm/src/ui/TopBar/Identity/IdentityList/IdentityList.tsx
This prevents long cluster names or long role lists from breaking the UI. Fixes gravitational/webapps.e#225.
String for testing:
```
drone-prod-app-access, grafana-prod-app-access, grafana-staging-app-access, releases-prod-app-access, releases-staging-app-access, sales-center-prod-app-access, sales-center-prod-db-access, sales-center-staging-app-access,sales-center-staging-db-access
```
> Add max-width on Identity popover

- packages/teleport/src/Apps/AddApp/__snapshots__/AddApp.story.test.tsx.snap
- packages/teleport/src/Databases/AddDatabase/__snapshots__/AddDatabase.story.test.tsx.snap
- packages/teleport/src/Nodes/AddNode/__snapshots__/AddNode.story.test.tsx.snap
- packages/teleport/src/services/links.ts
Fixes: https://github.com/gravitational/teleport/issues/11738
> [v8] Use the mac package download link instead of the tarball (#738)

- packages/teleport/src/Apps/AddApp/__snapshots__/AddApp.story.test.tsx.snap
- packages/teleport/src/Databases/AddDatabase/__snapshots__/AddDatabase.story.test.tsx.snap
- packages/teleport/src/Nodes/AddNode/__snapshots__/AddNode.story.test.tsx.snap
- packages/teleport/src/services/links.ts
Fixes: https://github.com/gravitational/teleport/issues/11738
> [v9] Use the mac package download link instead of the tarball (#738)

- packages/teleterm/src/services/pty/ptyProcess.ts
lsof uses stderr to print out warnings. This caused the previous version
of ptyProcess to throw an error, even though the exit code of lsof was 0.
The existing code already handles non-zero exit codes (asyncExec will
reject the promise). Since we don't know why stderr was inspected in
the first place, let's just remove the check for it.
> Fix getting cwd in presence of lsof warnings

- packages/teleterm/README.md
- packages/teleterm/package.json
- packages/teleterm/src/mainProcess/windowsManager.ts
Closes https://github.com/gravitational/webapps.e/issues/223
> Change app name to `Teleport Connect`

- packages/teleterm/src/mainProcess/runtimeSettings.ts
Fixes gravitational/webapps.e#147.
Without this people at Teleport would have harder time trying out Teleconnect in insecure mode – they'd need to know to put `--insecure` as at least the second flag. This PR makes it so that it works as expected.
> Fix check for the --insecure flag

- packages/teleterm/src/ui/appContext.ts
- packages/teleterm/src/ui/services/clusters/clustersService.ts
- packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.ts
- packages/teleterm/src/ui/services/statePersistence/statePersistenceService.ts
- packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
- packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
Closes: https://github.com/gravitational/webapps.e/issues/154
And closes point 1. from https://github.com/gravitational/webapps.e/issues/240
I simplified previous state restoring as we discussed a few days ago (it allowed to fix a bug with restoring previous state after logout and logging back in).
> Remove state related to a cluster when removing it

- packages/shared/components/MenuLogin/MenuLogin.test.tsx
- packages/shared/components/MenuLogin/MenuLogin.tsx
- packages/shared/components/MenuLogin/types.ts
- packages/teleterm/src/services/tshd/createClient.ts
- packages/teleterm/src/services/tshd/types.ts
- packages/teleterm/src/services/tshd/v1/gateway_pb.d.ts
- packages/teleterm/src/services/tshd/v1/gateway_pb.js
- packages/teleterm/src/services/tshd/v1/service_pb.d.ts
- packages/teleterm/src/services/tshd/v1/service_pb.js
- packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/Databases.tsx
- packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/useDatabases.ts
- packages/teleterm/src/ui/DocumentGateway/useDocumentGateway.ts
- packages/teleterm/src/ui/TabHost/useTabShortcuts.test.tsx
- packages/teleterm/src/ui/TopBar/Connections/Connections.story.tsx
- packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionItem.tsx
- packages/teleterm/src/ui/services/clusters/clustersService.test.ts
- packages/teleterm/src/ui/services/connectionTracker/trackedConnectionOperationsFactory.ts
- packages/teleterm/src/ui/services/connectionTracker/trackedConnectionUtils.ts
- packages/teleterm/src/ui/services/connectionTracker/types.ts
- packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.test.ts
- packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
- packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts
Adds a second dropdown for the db name. Needs tsh compiled with changes from gravitational/teleport#12173.
> Teleport Connect: Add dropdown for database name

- packages/teleterm/src/ui/services/clusters/clustersService.ts
- packages/teleterm/src/ui/uri.ts
Backports https://github.com/gravitational/webapps/pull/782
> [v9] Backport when updating cluster resources, remove only those that belong to this cluster

- packages/teleterm/package.json
By the GA release we should have a better versioning scheme in place, but for now let's just bump the version to 1.0.1 so that we can release this preview version with the fix for OTP (gravitational/teleport#12322).
> Bump Teleport Connect version to 1.0.1

- packages/teleterm/package.json
> [v9] Bump Teleport Connect version to 1.0.1 (#796)

- packages/teleport/src/Apps/useApps.ts
- packages/teleport/src/Console/DocumentNodes/useNodes.ts
- packages/teleport/src/Databases/useDatabases.ts
- packages/teleport/src/Desktops/useDesktops.ts
- packages/teleport/src/Kubes/useKubes.ts
- packages/teleport/src/Nodes/useNodes.ts
This PR resolves https://github.com/gravitational/teleport/issues/12289
For certain types of resources, such as apps, the `startKeys` that the back-end uses doesn't match what is being used at the front. This change makes it so that the request for the first page uses a blank `startKey`.
> Fix pagination bug

- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/Audit/fixtures/index.ts
- packages/teleport/src/services/audit/makeEvent.ts
- packages/teleport/src/services/audit/types.ts
We only have a single event type for all `session.network` events, whether the action was allowed or denied. This makes it hard for an administrator or auditor to detect malicious activity, because they have to look at the event JSON to get this info.
Fix this by updating the description in the audit log to clearly indicate whether the action was allowed or denied.
Fixes TEL-Q421-2
Fixes gravitational/teleport.e#331
> Indicate whether session.network events were allowed or blocked

- packages/shared/services/types.ts
- packages/teleport/src/Account/ManageDevices/AddDevice/AddDevice.tsx
- packages/teleport/src/Account/ManageDevices/AddDevice/useAddDevice.ts
- packages/teleport/src/Login/Login.test.tsx
- packages/teleport/src/Login/useLogin.ts
- packages/teleport/src/Welcome/useToken.ts
- packages/teleport/src/components/FormLogin/FormLogin.test.tsx
- packages/teleport/src/components/FormLogin/FormLogin.tsx
- packages/teleport/src/config.ts
- packages/teleport/src/services/auth/auth.ts
- packages/teleport/src/services/auth/types.ts
- packages/teleport/src/services/mfa/mfa.ts
- packages/teleport/src/services/mfa/types.ts
Updates api request bodies to pass on passwordless requests. Does not change any functionality, just wiring (still waiting on final design)
Note: `teleterm` passwordless work will be done separately
To enable passwordless registration (for invites and resets), this [PR](https://github.com/gravitational/teleport/pull/11748) needs to be merged
> Passwordless wiring

- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/Audit/fixtures/index.ts
- packages/teleport/src/services/audit/makeEvent.ts
- packages/teleport/src/services/audit/types.ts
* Indicate whether session.network events were allowed or blocked
Backports #800 
Fixes TEL-Q421-2
Fixes gravitational/teleport.e#331
> [v9] Indicate whether session.network events were allowed or blocked (#800)

- packages/teleport/src/Apps/useApps.ts
- packages/teleport/src/Console/DocumentNodes/__snapshots__/DocumentNodes.story.test.tsx.snap
- packages/teleport/src/Console/DocumentNodes/useNodes.ts
- packages/teleport/src/Databases/DatabaseList/DatabaseList.tsx
- packages/teleport/src/Databases/__snapshots__/Databases.story.test.tsx.snap
- packages/teleport/src/Databases/fixtures/index.ts
- packages/teleport/src/Databases/useDatabases.ts
- packages/teleport/src/Desktops/useDesktops.ts
- packages/teleport/src/Nodes/useNodes.ts
- packages/teleport/src/getUrlQueryParams.tsx
- packages/teleport/src/services/databases/databases.test.ts
- packages/teleport/src/services/databases/makeDatabase.ts
- packages/teleport/src/services/databases/types.ts
Makes tables for Nodes, Apps, Kubes, DB's and Desktops initially sorted for a better user experience.
Adds ability to sort by `type` for Databases.
> Add Initial Sorting for Tables

- packages/teleterm/src/ui/DocumentGateway/useDocumentGateway.ts
Closes gravitational/webapps.e#269.
Commit b5d30b1fa fixed some reconnect issues, but it also introduced a
locally scoped `cluster` variable. This made it seem like it's the cluster
to which the given gateway belongs, but it was actually the root cluster.
This commit renames the old `cluster` variable to `rootCluster`. It also
makes sure that `workspaceDocumentsService.openNewTerminal` receives
correct root & leaf cluster IDs.
> useDocumentGateway: Pin shell to correct cluster

- packages/teleterm/src/ui/DocumentGateway/useDocumentGateway.ts
> [v9] useDocumentGateway: Pin shell to correct cluster (#812)

- packages/teleterm/src/ui/DocumentGateway/useDocumentGateway.ts
Removing those as discussed in another PR: https://github.com/gravitational/webapps/pull/812#issuecomment-1118690563
When a root cluster gets removed (the user logs out of it), we remove
resources related to it, so the `rootCluster` variable should never be
null at this point.
> useDocumentGateway: Remove null rootCluster checks

- packages/teleterm/src/ui/Documents/KeyboardShortcutsPanel.tsx
- packages/teleterm/src/ui/QuickInput/QuickInput.tsx
- packages/teleterm/src/ui/QuickInput/useQuickInput.ts
- packages/teleterm/src/ui/TabHost/TabHost.test.tsx
- packages/teleterm/src/ui/TabHost/TabHost.tsx
- packages/teleterm/src/ui/Tabs/TabItem.tsx
- packages/teleterm/src/ui/Tabs/Tabs.tsx
- packages/teleterm/src/ui/TopBar/Clusters/ClusterSelector/ClusterSelector.tsx
- packages/teleterm/src/ui/TopBar/Connections/ConnectionsIcon/ConnectionsIcon.tsx
- packages/teleterm/src/ui/TopBar/Identity/IdentitySelector/IdentitySelector.tsx
- packages/teleterm/src/ui/services/keyboardShortcuts/index.ts
- packages/teleterm/src/ui/services/keyboardShortcuts/useKeyboardShortcutFormatters.ts
Adds tooltips with format `Label (shortcut)` to:
- Connections 
- Cluster selector
- Identity selector
- Close tab icon
- New tab icon
Also, adds inline shortcut to Quick input:
Closes: https://github.com/gravitational/webapps.e/issues/141
> Add tooltips with keyboard shortcuts

- packages/teleterm/src/ui/AppInitializer.tsx
- packages/teleterm/src/ui/services/workspacesService/workspacesService.test.ts
- packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
Closes https://github.com/gravitational/webapps.e/issues/275
Main reason of the problem:
`restorePersistedState()` starts iterating through the clusters and tries to restore a workspace for each of them, if it starts with the cluster which doesn't have a workspace it will crash on reading `persistedWorkspace.documents` and it won't restore anything.
Additionally, we couldn't spot the problem easily as we didn't show errors from the `init()` function anywhere.
> Prevent `restorePersistedState()` crash when there is no workspace for a cluster

- packages/teleterm/src/ui/AppInitializer.tsx
- packages/teleterm/src/ui/services/workspacesService/workspacesService.test.ts
- packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
> [v9] Prevent `restorePersistedState()` crash when there is no persisted workspace for a cluster (#825)

- packages/teleterm/src/ui/ClusterConnect/ClusterConnect.tsx
Related issue: https://github.com/gravitational/webapps.e/issues/242
Thanks to this PR user won't see login dialog if it is already logged to the cluster.
Teleport counterpart: https://github.com/gravitational/teleport/pull/12940
> Do not show the login dialog when a user adds a cluster that is connected 

- package.json
At some point, we want to rename packages/teleterm to something else.
This script will enable our build scripts (see gravitational/teleport#12257)
to automatically pick up this change without requiring us to change
the build scripts as well.
> Add get-teleport-connect-dir script

- packages/teleport/src/Main/useMain.ts
- packages/teleport/src/TopBar/useTopBar.ts
- packages/teleport/src/features.ts
- packages/teleport/src/types.ts
Updates specific features to extend an abstract Feature class, which demands an `isAvailable()` in order to try to remind us to be more conscientious about disabling features in the nav bar that users aren't allowed to access.
This refactor is just changing the code structure. The behavior is still the same. Next, I will go through the features that have a `TODO(isaiah)` in their `isAvailable`, and figure out the ACL flag to use and/or add to ensure that the features are only shown when available.
The motivation here is to be able to give users simple instructions for disabling UI features, which is apparently a common request (see https://github.com/gravitational/webapps/issues/836, https://github.com/gravitational/teleport/discussions/11920)
`webapps.e` should be updated with the merge …
> Refactor `Feature`

- packages/teleterm/src/logger.ts
- packages/teleterm/src/services/logger/loggerService.ts
- packages/teleterm/src/services/logger/types.ts
- packages/teleterm/src/services/tshd/middleware.test.ts
pipeProcessOutputIntoLogger has been moved to a separate interface, because
Stream is not an API that's available in the browser.
> Fix types for Logger/NullService

- packages/teleport/src/services/user/makeUser.ts
- packages/teleport/src/services/user/user.test.ts
a user ran into an issue in the UI where `cannot read properties of null (reading 'sort')` when listing users:  https://goteleport.slack.com/archives/CEZH6UL64/p1654536009001459
I was able to replicate this issue by modifying a user's yaml file through `tctl` and delete the `role` field, and `tctl create user.yaml -f`. A user can exist with no roles which returns as `null` from the back, which wasn't handled in the UI.
> Fix null role response from users fetch

- packages/build/devserver/index.js
This PR adds an error callback to the `proxyServer.web` call on the devserver. This way, the server won't crash when the target is not running.
The goal is to improve DX and not have to restart the dev server if you restart teleport (or if you run the web UI before running teleport), which can take several seconds.
> Add error callback to `handleRequest()` method on devserver

- README.md
Safari doesn't play nice with https://proxy.0.0.0.0.nip.io but accepts https://proxy.127.0.0.1.nip.io.
> changes 0.0.0.0 to 127.0.0.1 in README

- packages/teleterm/src/ui/DocumentTerminal/useDocumentTerminal.ts
Closes https://github.com/gravitational/webapps.e/issues/327
> Fall back to leaf cluster id when restoring leaf cluster terminal document

- packages/teleport/src/Account/ChangePassword/ChangePassword.tsx
- packages/teleport/src/stores/index.ts
- packages/teleport/src/stores/storeNav.ts
- packages/teleport/src/teleportContext.tsx
There was a bug where if you click to dashboard from a different screen e.g `from console view`, the menu `features` gets registered each time we come back to the dashboard screen. So you'll see like doubled, tripled, etc amount of repeated features. This PR resets the `features` each time we `init` the Main to prevent repeated registering.
Also adds trivial missing margin to Password component that was affecting the OSS version of UI.
https://github.com/gravitational/webapps.e/pull/335
> Fix menu bug

- packages/teleterm/src/mainProcess/windowsManager.ts
- packages/teleterm/src/ui/DocumentGateway/DocumentGateway.tsx
Closes gravitational/webapps.e#304.
---
Since the "Connect with GUI" section now includes the port number, I figured it'd be nice to be able to copy it with a context menu. Before this it was still possible to just copy it with Cmd + C, but I'm not sure how clear this was for the users.
The universal context menu can be overridden by overriding the `contextmenu` event handler.
Since the menu is "universal" and doesn't need any extra dependencies (it's just an array of objects), I decided to define it in `windowsManager.ts` rather than in `packages/teleterm/src/mainProcess/contextMenus`. The latter holds more complex menus that require IPC and some dependencies being passed in to the function.
---
Also, I found out that we should be able to add "Select All" to the terminal context menu so …
> Update "Connect with GUI" section, add universal context menu

- packages/teleport/src/AppLauncher/useAppLauncher.ts
**The Problem**:
When a user navigates to an app url with a path included like https://app1.teleport.example.com/my/path without authentication, the path is lost during the authentication process and eventually just gets the root path instead.
This isn't a problem when launching from the Apps dashboard because 1, they are already authenticated, and 2, the launch button sends to the root path anyway. So the problem usually persists when someone is either sharing a link with a path included to a coworker, or when visiting a bookmark or whatever. 
The current redirect URI only includes the host name (in this example above, it would be app1.teleport.example.com) because the /web/launch/:fqdn URI expects only the name of the app.
**The Solution**:
Because we cannot just simply pass the entire …
> fowards path parameter to app access authentication

- packages/teleterm/src/ui/DocumentCluster/ClusterResources/Applications/Applications.tsx
- packages/teleterm/src/ui/DocumentCluster/ClusterResources/Databases/Databases.tsx
- packages/teleterm/src/ui/DocumentCluster/ClusterResources/Kubes/Kubes.tsx
- packages/teleterm/src/ui/DocumentCluster/ClusterResources/Servers/Servers.tsx
Closes gravitational/webapps.e#343.
Just like in the Web UI, Connect is able to easily accommodate 15 resources
on the screen without vertical scroll in both 1920x1080 and 3024x1964,
as long as labels for the resources span just a single line.
1920x1080 remains the most popular screen size on desktop [1] and 1440x900
seems to be the most popular size on macOS [2].
On 1440x900 the pagination controls are not shown on the screen.
[1] https://gs.statcounter.com/screen-resolution-stats/desktop/north-america/#monthly-202105-202205
[2] https://web.archive.org/web/20220630103803/https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam?platform=mac
1920x1080
3024x1964
1440x900
> Change page size in Connect to 15

- packages/teleterm/src/ui/TabHost/useTabShortcuts.test.tsx
- packages/teleterm/src/ui/TabHost/useTabShortcuts.ts
Closes https://github.com/gravitational/webapps.e/issues/344
Solution:
Check if `allDocuments` has a length before doing any index searching. This will reduce any extra compute if no tabs exist, as well as ensure that `[index].uri` exists when it gets there
> wrap switchTab in a conditional

- packages/teleport/src/Main/fixtures/index.ts
- packages/teleport/src/config.ts
- packages/teleport/src/services/user/makeAcl.ts
- packages/teleport/src/services/user/types.ts
- packages/teleport/src/services/user/user.test.ts
The setting is also modulated by the `enableDirectorySharing` config variable while the feature is still in development.
Corresponds with https://github.com/gravitational/teleport/pull/14103
v9 and v10 backport required
> Add directory sharing to the ACL

- packages/teleterm/src/services/tshd/v1/app_pb.js
- packages/teleterm/src/services/tshd/v1/auth_settings_pb.js
- packages/teleterm/src/services/tshd/v1/cluster_pb.js
- packages/teleterm/src/services/tshd/v1/database_pb.js
- packages/teleterm/src/services/tshd/v1/gateway_pb.js
- packages/teleterm/src/services/tshd/v1/kube_pb.js
- packages/teleterm/src/services/tshd/v1/label_pb.js
- packages/teleterm/src/services/tshd/v1/server_pb.js
- packages/teleterm/src/services/tshd/v1/service_pb.js
gravitational/teleport#14097 updated protoc version on the master branch.
That change wasn't backported so when backporting any tshd protobuf changes
to v10 or earlier we must regenerate the protobuf files in the backport
branch from now on.
> Update teleterm protobuf files

- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/services/audit/makeEvent.ts
`Malfored packed` -> `malformed packet`
All other changes are my editor trimming excess whitespace on save.
> Fix typo in malformed packet error

- packages/design/src/Flex/Flex.jsx
- packages/design/src/Flex/Flex.story.js
- packages/design/src/system/index.js
This will help us stop adding margins on individual items.
styled-system doesn't seem to support gap yet [1] but we can just add it
ourselves.
This code works for styled-system v3.1.11 [2]. In the future we'll need
to simply replace `style` with `system` [3].
[1] https://github.com/styled-system/styled-system/issues/1159
[2] https://github.com/styled-system/styled-system/blob/v3.1.11/docs/custom-props.md
[3] https://styled-system.com/custom-props/
> Add gap property to Flex

- README.md
- packages/README.md
- packages/build/.babelrc.js
Makes supported browser versions explicit in our babel configuration, and allows us to use `async` within the app.
These changes result in a small reduction in bundle size:
oss: 2.38 MiB --> 2.19 MiB
enterprise 2.53 MiB --> 2.3 MiB
Backport to v9 / v10 required
> Updates Babel build targets

- packages/design/src/system/index.js
It makes it impossible to specify gap as a specific value, for example "8px"
as it'll get transformed to "8pxpx".
> Remove unnecessary tranformValue for gap

- packages/teleterm/src/mainProcess/windowsManager.ts
Closes https://github.com/gravitational/teleport-private/issues/146
More info: https://github.com/gravitational/teleport-private/issues/96
For now, due to us not needing any explicit permissions that request this handler, we are just going to deny all until needed.
In the future, we will need a custom confirmation dialog to handle these requests, assuming we pass the request to the user.
> deny any permission requests until needed

- packages/teleterm/src/mainProcess/windowsManager.ts
Closes: https://github.com/gravitational/teleport-private/issues/148
More info: https://github.com/gravitational/teleport-private/issues/96
Notes:
- `enableRemoteModule` defaults to `false` from electron 10+, so we do not need to explicitly set it here. [source](https://www.electronjs.org/docs/latest/breaking-changes#default-changed-enableremotemodule-defaults-to-false)
- `sandbox: true` has much bigger consequences and would require quite a bit of work to enable. We should discuss the implications of this in a separate issue. [docs](https://www.electronjs.org/docs/latest/tutorial/sandbox). As usual, if I'm overthinking this let me know, but the app does not currently work if sandbox is true and the changes appear to be substantial.
> updated webPreferences config

- packages/teleport/src/services/recordings/makeRecording.ts
- packages/teleport/src/services/recordings/recordings.test.ts
Fixes a bug that caused the "Session Recordings" tab to break with a `Cannot read properties of null (reading 'join')` error when there was a Kube session with en empty participants list. 
We defaulted the `participants` to `[]` when destructuring the object, however this only works for `undefined` values, and not for `null` values which is what is returned in this case.
> Fix bug caused by having no participants in a Kube session recording

- packages/teleport/src/services/recordings/makeRecording.ts
- packages/teleport/src/services/recordings/recordings.test.ts
v10 backport of https://github.com/gravitational/webapps/pull/995
> [v10] backport #995 (Fix bug caused by having no participants in a Kube session recording)

- packages/teleport/src/services/recordings/makeRecording.ts
- packages/teleport/src/services/recordings/recordings.test.ts
v9 backport of https://github.com/gravitational/webapps/pull/995
Note: The test is slightly edited in this one such that the expected `recordingType` for the kube recording is `'ssh'` instead of `'k8s'` because in v9 we didn't have support for `recordingType: 'k8s'` (which we use to show the k8s icon in the table).
> [v9] backport #995 (Fix bug caused by having no participants in a Kube session recording)

- packages/teleterm/webpack.renderer.extend.js
Closes: https://github.com/gravitational/teleport-private/issues/147
More info: https://github.com/gravitational/teleport-private/issues/96
Due to electron not being able to set HTTP request headers in production (because files are sent using the `file://` protocol), we can define a Content-Security-Policy in our "index.html" page.
This csp mostly matches the webui csp, with the exception of `font-src` where I've added `data:` to keep our icons working.
Note about `connect-src`: Adding in the urls `https://kcwm2is93l.execute-api.us-west-2.amazonaws.com/prod` and `https://usage.teleport.dev` are required for the feedback form to work on dev (insecure) and prod respectively
> added a content-security-policy

- packages/teleport/src/components/Router/Router.jsx
Closes https://github.com/gravitational/teleport-private/issues/150
More info: https://github.com/gravitational/teleport-private/issues/96
Replaces the requested pathname with a static message for the NotFound component. This removes the ability to display arbitrary text in the pathname and reduces the vector for a phishing attack [more here](https://owasp.org/www-community/attacks/Content_Spoofing) 
My notes on the approach:
I went with the 'easiest' solution for now. If we had used this message in other places, or had more context around the pathname message itself such as `The path: PATHNAME_HERE could not be found.` then we would want to abstract this out into some sort of template. I don't see it used anywhere else in the codebase this way, so for now a static message would suffice. …
> Remove pathname injection in 404 message

- packages/teleterm/src/ui/StatusBar/ShareFeedback/useShareFeedback.ts
[As discussed with Ben](https://gravitational.slack.com/archives/C03FJA391M3/p1658326366770589?thread_ts=1658326270.992069&cid=C03FJA391M3), we want to add this prefix so that dev rel cann differentiate feedback forms sent from Connect.
> Add `c-` prefix to the OS field of the feedback form

- README.md
As stated in https://github.com/gravitational/webapps/pull/970#pullrequestreview-1037970565, adding a new event is very common, but involves many parts that are easy to miss.
This PR adds a new section to the root README on how to add an audit event.
> Add section to README about audit events

- packages/teleport/src/Discover/AgentConnect.tsx
- packages/teleport/src/Discover/LoginTrait/LoginTrait.story.test.tsx
- packages/teleport/src/Discover/LoginTrait/LoginTrait.story.tsx
- packages/teleport/src/Discover/LoginTrait/LoginTrait.test.tsx
- packages/teleport/src/Discover/LoginTrait/LoginTrait.tsx
- packages/teleport/src/Discover/LoginTrait/__snapshots__/LoginTrait.story.test.tsx.snap
- packages/teleport/src/Discover/LoginTrait/index.ts
- packages/teleport/src/Discover/LoginTrait/useLoginTrait.ts
- packages/teleport/src/Discover/Shared.tsx
- packages/teleport/src/Discover/types.ts
- packages/teleport/src/Teleport.tsx
- packages/teleport/src/config.ts
- packages/teleport/src/services/history/history.ts
- packages/teleport/src/services/user/makeUser.ts
- packages/teleport/src/services/user/types.ts
- packages/teleport/src/services/user/user.test.ts
- packages/teleport/src/services/user/user.ts
- packages/teleterm/src/ui/uri.ts
part of https://github.com/gravitational/teleport/issues/13997
I made this component specific to `logins` (ssh) for the first phase. There were too many unknowns to make it generic for all traits (if that's even reasonable to do).
- Create a LoginTrait component that allows user's to add or remove new login principles
- Added trait fields to User response
- Created a shared file that exports shared/common components predicted to be used in each step
It starts with existing traits that I added earlier.
> Create LoginTrait Component

- packages/teleterm/webpack.renderer.dev.config.js
- packages/teleterm/webpack.renderer.extend.js
- packages/teleterm/webpack.renderer.prod.config.js
@ravicious 
Change this back to overriding the plugins like it did before the latest Webpack changes, but also add `fork-ts-checker-webpack-plugin` (the reason why I had originally changed it to just push `createHtmlPlugin` onto the end, as I didn't realise Connect was overriding the default plugins from the base webpack config)
> Fix the plugins for Connect so React Refresh works

- packages/teleterm/src/mainProcess/mainProcess.ts
- packages/teleterm/src/mainProcess/resolveNetworkAddress.test.ts
- packages/teleterm/src/mainProcess/resolveNetworkAddress.ts
- packages/teleterm/src/mainProcess/testProcess.js
Closes gravitational/webapps.e#124.
The problem this PR solves is described here: https://github.com/gravitational/webapps.e/issues/124#issuecomment-1192354642. I also improved the function so that if the child process exits, the function rejects immediately instead of waiting for the timeout.
---
This PR is based on the `gzdunek/add-windows-support` branch because Grzegorz made changes on that branch which massively helped with implementing this solution. As such, the code from this PR needs tsh compiled off `gzdunek/add-windows-support`.
To reproduce the problem on `gzdunek/add-windows-support`, add `time.Sleep(time.Second * 3)` just before `net.Listen` in `lib/teleterm/apiserver/apiserver.go`.
> Connect: Wait for tshd gRPC server to start

- packages/teleterm/src/main.ts
- packages/teleterm/src/mainProcess/windowsManager.ts
To my surprise, you can open the second instance of the app on Windows (on macOS it is not possible when you run the app from Finder). More information [here](https://www.electronjs.org/docs/latest/api/app#apprequestsingleinstancelockadditionaldata).
I was wondering how to implement it and IMO the best option is to only initialize the app, if we know that it's the first instance. Otherwise, some side effects from main process/file storage/logger/etc can occur.  
This change doesn't mean that we can have only one window in the app - when the `app.on('second-instance')` callback is invoked we can simply open a new window. 
By doing it this way, both windows will talk to the same `main` and `shared` process. 
When you try to open the second instance in development you will see the following …
> Allow only one instance of Connect

- packages/teleterm/package.json
Default `artfictName`: `${productName} Setup ${version}.${ext}`.
By adding a dash, @tcsc won't have to change the Houston filename parser.
> Add dash to Windows artifact name

- .github/actions/docker-build-webassets/action.yaml
- .github/workflows/update-webassets.yaml
- Dockerfile
- package.json
This will run using a service account which is the only account
permitted to push to webassets and webassets.e.
The action will run when any commits are pushed to the protected
branches in webapps. This means that commits to webapps.e do not
directly trigger updates - this automation will run when the
enterprise submodule ref is updated in webapps.
The "nop" yarn script allows us to separate the building of the docker
image from the build of Teleport, so that GitHub actions can run the
yarn build after buildling an image from our dockerfile. This is
necessary because container steps do not support build args.
> Add automation to update webassets on push

- packages/teleterm/src/mainProcess/runtimeSettings.ts
- packages/teleterm/src/sharedProcess/sharedProcess.ts
When protocol is not set, `resolveNetworkAddress` fails to match it.
> Set TCP protocol explicitly

- .github/workflows/update-webassets.yaml
Rather than checking out master and then switching to the appropriate
branch, we just check out the right branch from the beginning.
This works because the branches in gravitational/webassets match up
with the branches in this repository.
> Checkout webassets at the right branch

- .github/workflows/update-webassets.yaml
The checkout action leaves the branch in a detached head state.
> Fix git push

- Dockerfile
- yarn.lock
Normally we'd use `yarn install --frozen-lockfile` but yarn has a bug where it ignores this flag when workspaces are set up. https://github.com/yarnpkg/yarn/issues/4098
We can't use git as suggested under that issue because Docker isn't inside a git repo at that point.
* [Example of a failed run](https://console.cloud.google.com/cloud-build/builds/1d47366e-0eef-4532-a492-81c03ca51904;step=1?project=ci-account).
* [Example of a successful run](https://console.cloud.google.com/cloud-build/builds/46011d80-e02a-4921-b080-2e38b3de915e;step=2?project=ci-account) – the cache is working as expected.
> CI: Fail if an update to yarn.lock is needed

- packages/teleterm/src/ui/DocumentGateway/useDocumentGateway.ts
If '0' is provided as the default and the initial call to create a gateway
fails, the user will be presented with an input that says 0. 0 is an invalid
value though that this input will not accept.
An empty string, on the other hand, is a perfectly valid value (the input
doesn't have the `required` attribute). In that scenario, the backend will
default the value to '0' and pick a random port.
> useDocumentGateway: Default to '' rather than '0'

- Dockerfile
This is better than doing using checksums because you get immediate feedback about what went wrong.
[Example of a failed run](https://console.cloud.google.com/cloud-build/builds;region=global/fc219309-61e5-4796-94aa-407caf06af52;step=1?project=ci-account).
> Use git diff to show the difference after yarn install

- .cloudbuild/ci/build.yaml
- .cloudbuild/ci/test.yaml
- Dockerfile
- packages/build/scripts/yarn-install-frozen-lockfile.sh
This change makes it so that yarn.lock is checked only on CI servers and not when just running `make build-teleport`.
We advise people in the readme in the teleport repo to clone webapps and run `make build-teleport`. This shouldn't really check yarn.lock and currently fails because yarn outputs different lock depending on whether you have webapps.e cloned or not.
* [Example of a failed run](https://console.cloud.google.com/cloud-build/builds/d8a12af7-d2c5-476a-8258-50c7c2e8d569?project=ci-account).
* [Example of a successful run](https://console.cloud.google.com/cloud-build/builds/0de2b703-653f-4db2-8d3b-6b2df77aefe9;step=2?project=ci-account). Subsequent steps use cache.
> Dockerfile: Check yarn.lock only on CI servers

- packages/shared/hooks/index.ts
- packages/shared/hooks/useRefAutoFocus/index.ts
- packages/shared/hooks/useRefAutoFocus/useRefAutoFocus.test.tsx
- packages/shared/hooks/useRefAutoFocus/useRefAutoFocus.ts
- packages/teleterm/src/ui/Document/Document.tsx
- packages/teleterm/src/ui/DocumentTerminal/DocumentTerminal.tsx
- packages/teleterm/src/ui/Documents/DocumentsRenderer.tsx
- packages/teleterm/src/ui/TabHost/TabHost.test.tsx
Closes https://github.com/gravitational/webapps.e/issues/323
`useRefAutoFocus` was added mainly because of the changes from this PR: https://github.com/gravitational/webapps/pull/1071
If we decide to not merge it, then probably I would remove this hook and just put the code directly in `Document`.
> Move focus to active document

- .cloudbuild/ci/build.yaml
- .cloudbuild/ci/test.yaml
- Dockerfile
- packages/build/scripts/yarn-install-frozen-lockfile.sh
Backport #1076.
Since the webpack changes weren't merged into teleport-v10 yet, I had a cherry-pick conflict in Dockerfile. The overall changes amounted to just adding that single build arg though.
> [v10] Dockerfile: Check yarn.lock only on CI servers (#1076)

- package.json
- packages/teleterm/README.md
- packages/teleterm/package.json
> [v10] Remove building native deps from `yarn build-term`

- packages/teleport/src/Discover/Discover.tsx
- packages/teleport/src/Discover/DownloadScript/DownloadScript.story.tsx
- packages/teleport/src/Discover/DownloadScript/__snapshots__/DownloadScript.story.test.tsx.snap
- packages/teleport/src/Discover/LoginTrait/LoginTrait.story.tsx
- packages/teleport/src/Discover/LoginTrait/LoginTrait.test.tsx
- packages/teleport/src/Discover/LoginTrait/__snapshots__/LoginTrait.story.test.tsx.snap
- packages/teleport/src/Discover/Shared.tsx
If the user clicks exit, or presses the back button, this will ask the user to confirm that they want to navigate away -
Note - this doesn't include refresh, as we're not sure if it is needed and it's a different looking confirm dialog (you can't change this one) -
We had to remove the exit confirm dialog UI, otherwise we'd end up in a double confirmation situation when the user clicks exit -
It is possible to get around this in the future - with a bit of rework to where the exit dialog open state is, we can disable the prompt when the exit dialog is open.
For now, we just have the one UI when a user tries to navigate away. If we put the exit confirmation dialog UI back in, that'll be two UIs, and if we add the reload, that's three different UIs. Not sure if we care that much about these …
> [Discover] Prompt the user on pressing the back button during Discover

- packages/build/webpack/webpack.base.js
Exclude `**/*.story.tsx` from the issues that `fork-ts-checker-webpack-plugin` reports, so any type errors in a story won't block the app from loading.
> Ignore `*.story.tsx` when type checking during Webpack builds

- packages/teleterm/README.md
- packages/teleterm/src/mainProcess/runtimeSettings.ts
#1116 changes `TELETERM_TSH_PATH` to `CONNECT_TSH_BIN_PATH` and this PR adds a default value for `CONNECT_TSH_BIN_PATH` in dev mode.
> Add default value for CONNECT_TSH_BIN_PATH in dev mode

- packages/teleport/src/config.ts
- packages/teleport/src/services/user/makeAcl.ts
- packages/teleport/src/services/user/user.test.ts
Removes `enableDirectorySharing` flag to turn on directory sharing by default
corresponds with https://github.com/gravitational/teleport/pull/15789
requires backport to v10
> Turn on directory sharing by default 

- .gitignore
- README.md
- packages/build/devserver/index.js
I don't use the default certificates generated by Webpack, opting to use [mkcert](https://github.com/FiloSottile/mkcert) to generate certificates that I share between teleport and webapps.
This change allows for the HTTPS options for Webpack to be configured via environment variables.
Either
- `WEBPACK_HTTPS_CERT` **(required)** - absolute path to the certificate
- `WEBPACK_HTTPS_KEY` **(required)** - absolute path to the key
- `WEBPACK_HTTPS_CA` - absolute path to the ca
- `WEBPACK_HTTPS_PASSPHRASE` - the passphrase
Or:
- `WEBPACK_HTTPS_PFX` **(required)** - absolute path to the certificate
- `WEBPACK_HTTPS_PASSPHRASE` - the passphrase
Also I've added `certs` to be ignored by git, so there's a folder people can use without worrying about committing them to git.
> Allow Webpack's HTTPS options to be set through environment variables

- packages/teleport/src/AuthConnectors/templates/github.yaml
We deprecated teams_to_logins in favor of teams_to_roles in v10.
Starting with v11, teams_to_logins will no longer be accepted.
> Update GitHub connector template

- packages/teleport/src/AuthConnectors/templates/github.yaml
We deprecated teams_to_logins in favor of teams_to_roles in v10.
Starting with v11, teams_to_logins will no longer be accepted.
Backports #1157
> [v10] Update GitHub connector template

- packages/teleport/src/Audit/EventList/EventTypeCell.tsx
- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/Audit/fixtures/index.ts
- packages/teleport/src/services/audit/makeEvent.ts
- packages/teleport/src/services/audit/types.ts
> [v9] Add an event for when a session recording is accessed

- packages/teleterm/webpack.renderer.dev.config.js
- packages/teleterm/webpack.renderer.extend.js
- packages/teleterm/webpack.renderer.prod.config.js
Backport #1031 & #1032.
I forgot to backport this so dev mode in v10 wasn't really working but it looks like no one ran into that problem yet.
> [v10] Add unsafe-eval to CSP in dev mode to make source maps work

- packages/teleport/src/Discover/DownloadScript/DownloadScript.tsx
- packages/teleport/src/Discover/DownloadScript/__snapshots__/DownloadScript.story.test.tsx.snap
- packages/teleport/src/Discover/LoginTrait/LoginTrait.story.tsx
- packages/teleport/src/Discover/LoginTrait/LoginTrait.tsx
- packages/teleport/src/Discover/LoginTrait/__snapshots__/LoginTrait.story.test.tsx.snap
- packages/teleport/src/Discover/LoginTrait/useLoginTrait.ts
- packages/teleport/src/Discover/Shared.tsx
- packages/teleport/src/Discover/TestConnection/TestConnection.story.tsx
- packages/teleport/src/Discover/TestConnection/TestConnection.tsx
- packages/teleport/src/Discover/TestConnection/useTestConnection.ts
- packages/teleport/src/Main/Main.tsx
- packages/teleport/src/components/UserMenuNav/UserMenuNav.test.tsx
- packages/teleport/src/components/UserMenuNav/UserMenuNav.tsx
- packages/teleport/src/services/agents/make.ts
- packages/teleport/src/services/agents/types.ts
- packages/teleport/src/services/user/types.ts
- packages/teleport/src/services/user/user.ts
- packages/teleport/src/services/websession/types.ts
part of https://github.com/gravitational/teleport/issues/13997
- Adds checkmark to where the user is currently on
- Adds alert bubble to the discover nav item if user:
- doesn't have a resource
- has not visited the discover page
- Added allowing user to re-fetch failure points (eg network errors) so they don't need to restart the flow, just refetch the data that was required for that step
on resources (anything but discover or user menu nav items)
no resources alert bubble that goes away when a user visits the discover page (like github)
on discover
on a user menu nav item
Refetching from errors (eg network)
> [Discover] User menu checkmark, alert bubble, tweaks

- packages/teleterm/electron-builder-config.js
By mistake I changed `teleport-connect_1.0.2_amd64.deb` to `teleport-connect-1.0.2_amd64.deb` in this [PR](https://github.com/gravitational/webapps/pull/1142).
Houston can't see the file because of that.
> Change DEB artifact name

- packages/teleport/src/Discover/Discover.tsx
- packages/teleport/src/Discover/DownloadScript/DownloadScript.tsx
- packages/teleport/src/Discover/DownloadScript/__snapshots__/DownloadScript.story.test.tsx.snap
- packages/teleport/src/Discover/Finished/Finished.story.tsx
- packages/teleport/src/Discover/LoginTrait/LoginTrait.story.test.tsx
- packages/teleport/src/Discover/LoginTrait/LoginTrait.story.tsx
- packages/teleport/src/Discover/LoginTrait/LoginTrait.test.tsx
- packages/teleport/src/Discover/LoginTrait/LoginTrait.tsx
- packages/teleport/src/Discover/LoginTrait/__snapshots__/LoginTrait.story.test.tsx.snap
- packages/teleport/src/Discover/LoginTrait/useLoginTrait.ts
- packages/teleport/src/Discover/SelectResource/SelectResource.test.tsx
- packages/teleport/src/Discover/SelectResource/SelectResource.tsx
- packages/teleport/src/Discover/Shared.tsx
- packages/teleport/src/Discover/TestConnection/TestConnection.story.tsx
- packages/teleport/src/Discover/TestConnection/TestConnection.tsx
- packages/teleport/src/Discover/TestConnection/useTestConnection.ts
- packages/teleport/src/Discover/templates/index.ts
- packages/teleport/src/Discover/templates/logins.yaml
- packages/teleport/src/Discover/templates/loginsAndRuleUsers.yaml
- packages/teleport/src/Discover/templates/ruleConnectionDiagnostic.yaml
- packages/teleport/src/Discover/types.ts
- packages/teleport/src/Discover/useDiscover.tsx
- packages/teleport/src/stores/storeUserContext.ts
- Permission redo: basically keeps the old functionality, where we just check for `resource listing/reading` and `tokens.create` before allowing the flow. All other permissions will be checked during the flow step and will show different permission messages depending on level of perm
- Prevent showing prompt when user clicks on "manage access" when already on it
- I just noticed that our sidenav titles renders for our unfinished flows, so I removed them from the sidenav
Removing sidenav titles for unfinished flows
Test connection perm message
LoginTrait message (does not show all combos, just showing the placement of different msgs, storybook will have all combos)
> [Discover] Check permission during the flow step instead of at beginning

- packages/teleport/src/Discover/Discover.tsx
- packages/teleport/src/Discover/SelectResource/SelectResource.tsx
- packages/teleport/src/Main/Main.tsx
- packages/teleport/src/Main/MainContainer.tsx
- packages/teleport/src/Main/index.ts
- packages/teleport/src/SideNav/SideNav.tsx
- packages/teleport/src/SideNav/__snapshots__/SideNav.story.test.tsx.snap
- packages/teleport/src/Teleport.tsx
- packages/teleport/src/components/BannerList/BannerList.tsx
This makes it so `MainContainer` no longer scrolls and `HorizontalSplit` is instead the element that scrolls when the screen width is too small.
To do this, I've made it so the contents inside `HorizontalSplit` are wrapped with a min width, to force `HorizontalSplit` to scroll when its children's size (which is 100% minus the sidebar width) exceed its width. This then makes the `MainContainer` never have to scroll, so double scroll bars won't happen.
This shows the correct scrollbar appearing when the browser width is ~1000px
Everything's fine at wide resolutions
This also changes discover to have a max content width of 1450px (so 1450px + 281px for the sidebar = it'll stop expanding past a browser being 1731px wide).
At 1300px wide
At 1000px wide
> Fix double scroll bars, make everything have min width 1250px

- packages/teleterm/src/mainProcess/fixtures/mocks.ts
- packages/teleterm/src/mainProcess/mainProcess.ts
- packages/teleterm/src/mainProcess/mainProcessClient.ts
- packages/teleterm/src/mainProcess/runtimeSettings.ts
- packages/teleterm/src/mainProcess/types.ts
- packages/teleterm/src/services/pty/ptyHost/buildPtyOptions.ts
- packages/teleterm/src/services/pty/types.ts
- packages/teleterm/src/ui/DocumentCluster/ClusterResources/SideNav/SideNav.tsx
- packages/teleterm/src/ui/DocumentTerminal/useDocumentTerminal.ts
- packages/teleterm/src/ui/Tabs/TabItem.tsx
- packages/teleterm/src/ui/Tabs/Tabs.tsx
- packages/teleterm/src/ui/TopBar/Connections/ConnectionsFilterableList/ConnectionItem.tsx
- packages/teleterm/src/ui/appContext.ts
- packages/teleterm/src/ui/commandLauncher.ts
- packages/teleterm/src/ui/components/LinearProgress/LinearProgress.tsx
- packages/teleterm/src/ui/services/clusters/clustersService.test.ts
- packages/teleterm/src/ui/services/clusters/clustersService.ts
- packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.test.ts
- packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.ts
- packages/teleterm/src/ui/services/connectionTracker/trackedConnectionOperationsFactory.ts
- packages/teleterm/src/ui/services/connectionTracker/trackedConnectionUtils.ts
- packages/teleterm/src/ui/services/connectionTracker/types.ts
- packages/teleterm/src/ui/services/quickInput/quickInputService.test.ts
- packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
- packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts
- packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
Closes https://github.com/gravitational/webapps.e/issues/284 
I extended Zac's idea a bit, we will create a separate kubeconfig per kube cluster (not per tab). The file is deleted when the user removes the connection. Multiple tabs opened to the same kube cluster share the same kubeconfig.     
This is conceptually similar to db access, where we keep a port for a given connection. 
I also added a loading indicator for tsh and kube tabs.
> Add kube support

- packages/teleport/src/Sessions/Sessions.story.tsx
- packages/teleport/src/Sessions/Sessions.tsx
- packages/teleport/src/Sessions/useSessions.ts
This PR resolves https://github.com/gravitational/teleport/issues/16515
Removes the auto-refresh from the Active Sessions page which occurs every 3 seconds. The active sessions are now only fetched on page load.
> Remove auto-refresh for Active Sessions list

- .cloudbuild/ci/test.yaml
This adds a `yarn type-check` step to the CI checks run on every webapps PR. This prevents inadvertently merging changes containing type errors.
> Add `type-check` step to CI checks

- packages/teleport/src/Discover/Discover.tsx
- packages/teleport/src/Main/Main.tsx
- packages/teleport/src/components/BannerList/Banner.test.tsx
- packages/teleport/src/components/BannerList/Banner.tsx
- packages/teleport/src/components/BannerList/BannerList.tsx
- packages/teleport/src/components/BannerList/useAlerts.test.tsx
- packages/teleport/src/services/alerts/alerts.tsx
Supports: https://github.com/gravitational/teleport/issues/16425
Teleport PR: https://github.com/gravitational/teleport/pull/16426
Renders "teleport.internal/link" label as link in UX
> add cluster alert links to UX

- packages/teleterm/src/mainProcess/mainProcess.ts
- packages/teleterm/src/mainProcess/mainProcessClient.ts
- packages/teleterm/src/mainProcess/types.ts
- packages/teleterm/src/services/pty/ptyHost/buildPtyOptions.ts
- packages/teleterm/src/services/pty/types.ts
- packages/teleterm/src/ui/ClusterLogout/useClusterLogout.ts
- packages/teleterm/src/ui/TopBar/Connections/Connections.story.tsx
- packages/teleterm/src/ui/commandLauncher.ts
- packages/teleterm/src/ui/services/clusters/clustersService.test.ts
- packages/teleterm/src/ui/services/clusters/clustersService.ts
- packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.ts
- packages/teleterm/src/ui/services/connectionTracker/trackedConnectionOperationsFactory.ts
- packages/teleterm/src/ui/services/connectionTracker/trackedConnectionUtils.ts
- packages/teleterm/src/ui/services/connectionTracker/types.ts
- packages/teleterm/src/ui/services/workspacesService/documentsService/documentsService.ts
- packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts
I didn't want to add new things to the previous PR, so I'm starting a new one.
It fixes two issues:
- connection resources are now correctly cleaned up when user logs out
- `insecure` flag is passed to `kube login` when you run the app in that mode
> Minor kube fixes

- @types/raw-loader.d.ts
We still have `raw-loader` usage in our enterprise codebase, which is only working because a dependency of a dependency of a dependency of a dependency (yes, that many levels) of`@storybook/react` has `raw-loader` as a dependency.
This PR removes the custom type we have declared, so TypeScript will complain on any future `raw-loader` usage.
It will also pull in the master commit from the enterprise side, once that PR is merged.
> Remove `raw-loader` completely

- README.md
- packages/build/webpack/webpack.dev.config.js
This adds file system based caching to Webpack during development, so subsequent re-runs of `webpack-dev-server` will start up really quickly as it'll reuse the cache from when it last ran.
I've added environment variables to disable this behaviour and to configure the path if wanted.
Initial compile time: 10317ms.
Stopping and then starting Webpack again, compile time: 697ms.
> Add caching to Webpack during development

- packages/teleport/src/Discover/Discover.test.tsx
- packages/teleport/src/Discover/Discover.tsx
- packages/teleport/src/FeaturesContext.tsx
- packages/teleport/src/Main/Main.story.tsx
- packages/teleport/src/Main/Main.tsx
- packages/teleport/src/Main/useMain.ts
- packages/teleport/src/Teleport.tsx
- packages/teleport/src/features.ts
#1172 incorrectly assumed that `useFeatures()` was agnostic like `useTeleport()` which returns the correct context based on OSS vs enterprise. As a result, the enterprise version is now being passed the OSS feature set, instead of the correct enterprise feature set. This caused access requests to go missing from the UI.
This fixes that by actually making it a context that will have its value change depending on if entered from the enterprise side or OSS side.
The feature set will always default to OSS if not set, but enterprise overrides this value with its own feature set.
> Change `getFeatures()` to use a context and use `useFeatures()` instead

- packages/teleport/src/Discover/Discover.test.tsx
- packages/teleport/src/Discover/Discover.tsx
- packages/teleport/src/FeaturesContext.tsx
- packages/teleport/src/Main/Main.story.tsx
- packages/teleport/src/Main/Main.tsx
- packages/teleport/src/Main/useMain.ts
- packages/teleport/src/Teleport.tsx
- packages/teleport/src/features.ts
backport #1211 to teleport-v10
> [v10] Create a FeatureContext to replace passing features as a prop (#1211)

- packages/build/package.json
- packages/design/src/Icon/Icon.jsx
- packages/design/src/Icon/Icon.story.js
- packages/design/src/utils/copyToClipboard.ts
- packages/design/src/utils/testing.tsx
- packages/teleport/src/components/TextSelectCopy/TextSelectCopy.story.tsx
- packages/teleport/src/components/TextSelectCopy/TextSelectCopy.tsx
- packages/teleport/src/components/TextSelectCopy/TextSelectCopyMulti.story.test.tsx
- packages/teleport/src/components/TextSelectCopy/TextSelectCopyMulti.story.tsx
- packages/teleport/src/components/TextSelectCopy/TextSelectCopyMulti.test.tsx
- packages/teleport/src/components/TextSelectCopy/TextSelectCopyMulti.tsx
- packages/teleport/src/components/TextSelectCopy/__snapshots__/TextSelectCopyMulti.story.test.tsx.snap
- packages/teleport/src/components/TextSelectCopy/index.tsx
- yarn.lock
Create a `TextSelectCopyMulti` matching figma design (below) and allows multi text selects and adding comments
Note: Will update and delete the original single text copy `TextSelectCopy` after this PR is approved and merged
https://www.figma.com/file/8DQZl1mYUPLgvKgmA6zPOM/In-Progress-Work?node-id=444%3A49313
scrollbar appearances
> Create TextSelectCopyMulti that allows multi lines and adding comments

- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/services/audit/makeEvent.ts
Connecting to some DB sessions does not have a db name.  Then you get a undefined database in the log.
Modifies 
To show as
When available it will still show as in this postgres
> Remove database reference when undefined in session start, end for Audit Log

- packages/teleport/src/Discover/Desktop/ConnectTeleport/CreateTeleportConfigAnimation.tsx
- packages/teleport/src/Discover/Desktop/ConnectTeleport/RunConfigureScriptAnimation.tsx
Once https://github.com/gravitational/teleport/pull/15761 lands, it'll output a v3 config. This needs backporting to v11
This updates the Desktop setup animation flow to match the new v3 config it outputs.
> [Discover] Update the Desktop animation to output a v3 config

- packages/teleport/src/Discover/Desktop/ConnectTeleport/RunConfigureScript.tsx
As it stands, the spacing is too little between the text and the button. This adds some spacing between them. This needs backporting to v11.
> Add spacing between the text and generate button

- packages/teleterm/src/services/tshd/types.ts
- packages/teleterm/src/ui/QuickInput/QuickInput.story.tsx
- packages/teleterm/src/ui/services/clusters/clustersService.test.ts
- packages/teleterm/src/ui/services/clusters/clustersService.ts
- packages/teleterm/src/ui/services/connectionTracker/connectionTrackerService.test.ts
- packages/teleterm/src/ui/services/statePersistence/statePersistenceService.ts
- packages/teleterm/src/ui/services/workspacesService/accessRequestsService.test.ts
- packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts
- packages/teleterm/src/ui/services/workspacesService/workspacesService.test.ts
- packages/teleterm/src/ui/services/workspacesService/workspacesService.ts
[[webapps.e](https://github.com/gravitational/webapps.e/pull/408/files)]
This PR removes assumed requests from `app_state.json`, we shouldn't keep them there, because it means duplicating `tsh` state. 
I added `assumedRolesRequests` to the current `LoggedInUser` type, I treat it as a temporary solution. In the future we'll only be able to assume 1 access request at a time, it will be a good opportunity to change the backend to just return `cluster.loggedInUser.assumedRequest`(containing `id`, `expires` and `roles`) instead of `cluster.loggedInUser.activeRequestsList` (which is a list containing only IDs).
> Do not keep assumed roles in `app_state.json`

- packages/teleterm/src/ui/DocumentCluster/ClusterResources/ClusterSearch.tsx
- packages/teleterm/src/ui/DocumentCluster/DocumentCluster.tsx
Backport #1280
The size of the sync button was changed to match the refresh button of access requests (https://github.com/gravitational/webapps.e/pull/396#discussion_r982842537). The change was reverted in #1269.
Instead of making the sync button to be of custom height, I think we should just change the size of the search input.
It also has the added bonus of making the sync and refresh button be on a matching height on both tabs, so they don't shift when switching between access requests and cluster resources.
> [v11] Connect: Adjust size of sync button & search input

- packages/teleport/src/Discover/Kubernetes/LoginTrait/useLoginTrait.ts
The bug was that after a user updated their trait, the cert was not updated so it was referring to stale user traits.
> [Discover] Fix bug where user traits were not updated in cert

- packages/teleport/src/Desktops/Desktops.tsx
- packages/teleport/src/Kubes/Kubes.tsx
- packages/teleport/src/Kubes/__snapshots__/Kubes.story.test.tsx.snap
This changes the desktop list to have a button to add a desktop which goes through to the Discover flow, similar to k8s and servers.
I also noticed kubernetes was spelt wrong so thought I'd throw it in with this PR.
This needs backporting to v11
> Change Desktop page to link to Discover, fix k8s typo

- .gitattributes
Linguist seems to expect that on line 6, those files have a specific string in them but that's not true for our files.
Maybe that's because we use buf and not protoc to generate them.
This should automatically collapse those files in diffs and properly count JavaScript usage in language stats for the repo.
See: https://github.com/github/linguist/blob/master/docs/overrides.md
> Make linguist correctly classify JS protobuf files

- .gitattributes
Backport #1300
Linguist seems to expect that on line 6, those files have a specific string in them but that's not true for our files.
Maybe that's because we use buf and not protoc to generate them.
This should automatically collapse those files in diffs and properly count JavaScript usage in language stats for the repo.
See: https://github.com/github/linguist/blob/master/docs/overrides.md
> [v11] Make linguist correctly classify JS protobuf files

- packages/teleterm/src/ui/DocumentCluster/ClusterResources/renderLabelCell.tsx
- packages/teleterm/src/ui/TopBar/Identity/IdentityList/IdentityList.tsx
This avoids extra space where it's not necessary.
Before | After
:-:|:-:
> Connect: Use gap instead of margins for <Label> groups

- packages/teleterm/src/ui/DocumentCluster/ClusterResources/renderLabelCell.tsx
- packages/teleterm/src/ui/TopBar/Identity/IdentityList/IdentityList.tsx
Backport #1316.
@avatus Could you merge it to v11 after reviewing? I won't be able to do it tomorrow and I'd like this change to be released together with the other change to the role list that was submitted.
> [v11] Connect: Use gap instead of margins for <Label> groups

- packages/teleport/src/services/history/history.test.ts
- packages/teleport/src/services/history/history.ts
Fixes https://github.com/gravitational/security-findings/issues/5
Previously we would only check if the `cfg.baseUrl` was the 0th index of the url being passed in during redirects. This would catch most 'bad' redirects except for ones that would use the entire baseUrl as subdomains. For example,
if `cfg.baseUrl` was `https://teleport.avat.us`, I could perform an open redirect by passing a redirect_uri of `https://teleport.avat.us.bad.io` because the baseUrl was still the 0th index of the passed url. This fix takes advantage of the URL api by passing in `cfg.baseUrl` as the optional base param in URL.
If a full, valid url is passed as the first param into `new URL`, any base param passed as the second will be overridden. If thats the case, we can check if it is still equal to our …
> Update ensureBaseUrl conditional

- packages/teleport/src/Discover/Kubernetes/TestConnection/TestConnection.story.tsx
- packages/teleport/src/Discover/Kubernetes/TestConnection/TestConnection.tsx
- packages/teleport/src/Discover/Kubernetes/TestConnection/useTestConnection.ts
- packages/teleport/src/Discover/Server/TestConnection/TestConnection.story.tsx
- packages/teleport/src/Discover/Server/TestConnection/TestConnection.tsx
- packages/teleport/src/Discover/Server/TestConnection/useTestConnection.ts
- packages/teleport/src/Discover/Shared/Header.tsx
- packages/teleport/src/Discover/Shared/index.ts
- packages/teleport/src/Discover/types.ts
- packages/teleport/src/Discover/useDiscover.tsx
- packages/teleport/src/services/agents/agents.test.ts
- packages/teleport/src/services/agents/agents.ts
- As discussed in discover meeting, allow user to go back to the `Setup Access` screen from `TestConnection` screen to fix incorrect access when testing connection (otherwise they are stuck and have to restart the flow).
- Fix a bug where we try to access a possible undefined field
-  [ ] backport to v11
-  [ ] backport to v10
on hover
> [Discover] Add back button for `TestConnection` screens

- packages/teleport/src/services/history/history.test.ts
- packages/teleport/src/services/history/history.ts
An update to https://github.com/gravitational/webapps/pull/1320
We were checking `hostname` which would be something like `localhost` when the `cfg.baseUrl` would be `http://localhost`, so... no open redirect could ever succeed since we were 100% of the time always updating the base. The desired outcome of preventing an open redirect was fixed in the PR above but in the wrong way. 
This PR checks the origin now instead of hostname, and if not matching, will just create a new URL with `cfg.baseUrl`
> Update ensureBaseUrl to use URL constructors only

- README.md
- packages/build/devserver/index.js
Checking the `Host` header against the hostname for the given `--target` flag probably isn't a desirable by-default behaviour. This is because it assumes some kind of completely local configured setup.
I've made it so it requires the environment variable `WEBPACK_PROXY_APP_ACCESS` to be set , so it's now opt-in and configurable.
This means that when trying to run Webpack in front of a Cloud host, it'll work properly now (whereas it wouldn't before, as it would see there was a mismatch in hostnames and proxy all the traffic to Cloud).
> Disable hostname comparison when proxying by default, add feature flag

- packages/teleterm/src/main.ts
Fixes https://github.com/gravitational/teleport-private/issues/173
As far as I'm aware, we only open two external links and both of them are `https` protocol. This only allows that protocol and prevents any links such as `window.open("ftp://badurl.here")` from being opened.
> Prevent non-https protocol from opening external windows

- packages/teleport/src/Login/Login.test.tsx
- packages/teleport/src/Login/Login.tsx
Correct "Sign into Teleport" to "Sign in to Teleport"
Needs a backport to.. well, probably every version
> Correct "sign into" to "sign in"

- packages/teleport/src/Apps/AddApp/Manually/Manually.tsx
- packages/teleport/src/Apps/AddApp/__snapshots__/AddApp.story.test.tsx.snap
As part of config v3, `teleport configure` was changed to allow `--proxy`, which will set `proxy_server` to the correct proxy address. This also changed the previous use of `--auth-server` to set `auth_server`, which doesn't work with a proxy URL.
This changes the manual step's command for adding an application to use `--proxy`. Will also need a backport to v11.
> Change `teleport configure` to use `--proxy`

- packages/teleport/src/lib/util.test.ts
- packages/teleport/src/lib/util.ts
- packages/teleport/src/services/nodes/makeNode.ts
- packages/teleport/src/services/nodes/nodes.test.ts
fixes https://github.com/gravitational/teleport/issues/18369
fixes bug where we try to iterate over a `null` array. the source was from `services/nodes/makeNodes`. I also placed checks for `arrayStrDiff` thinking this was the source of bug initially but it wasn't but why not.
> Fix null array

- packages/teleport/src/Main/index.ts
- packages/teleport/src/Teleport.tsx
Historically, we render our public routes differently from our private routes, and only private routes had a suspense fallback. This means any non-logged in user would be met with a suspense error.
This changes the way we render the routes to match the private method.
> Render public routes with a suspense fallback

- packages/teleport/src/Teleport.tsx
The waiting room from enterprise was being put into the `Switch` element first, taking precedence over all other routes. This would cause the SSH console to 404.
To fix this, I've just put the routes coming in from enterprise to be last in the list.
> Render extra private routes last

- packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabase.story.tsx
- packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabase.tsx
- packages/teleport/src/Discover/Database/CreateDatabase/index.ts
- packages/teleport/src/Discover/Database/CreateDatabase/useCreateDatabase.ts
- packages/teleport/src/Discover/Database/DownloadScript/DownloadScript.tsx
- packages/teleport/src/Discover/Shared/LabelsCreater/LabelsCreater.story.tsx
- packages/teleport/src/Discover/Shared/LabelsCreater/LabelsCreater.tsx
- packages/teleport/src/Discover/Shared/LabelsCreater/index.ts
- packages/teleport/src/Discover/useDiscover.tsx
- packages/teleport/src/config.ts
- packages/teleport/src/services/databases/databases.ts
- packages/teleport/src/services/databases/makeDatabase.ts
- packages/teleport/src/services/databases/types.ts
part of https://github.com/gravitational/teleport/issues/16858
There's a lot of TODO, but wanted to ship it out because it will be used for both `self-hosted` and `aws` flows
- added new endpoints from https://github.com/gravitational/teleport/pull/17783
- extracted label creating logic from `Database/DownloadScript` to re-use elsewhere
- Tentatively created a `CreateDatabase` component for `self-hosted`. The AWS portion for the backend was not included so left it out until it is done (pinged @marcoandredinis and he will focus on it next week)
Self-hosted: https://www.figma.com/file/8DQZl1mYUPLgvKgmA6zPOM/In-Progress-Work?node-id=1299%3A69070&t=U9L15xmjMaN6JJAq-0
AWS (very sim to self-hosted): https://www.figma.com/file/8DQZl1mYUPLgvKgmA6zPOM/In-Progress-Work?node-id=1296%3A67025&t=U9L15xm …
> [Discover] Tentatively implement Create Database screen

- packages/teleport/src/lib/tdp/sharedDirectoryManager.ts
Previously we were calling `fileHandle.createWritable()` without any options, meaning that every time we wrote to a file during directory sharing it was being overwritten:
> keepExistingData: If false or not specified, the temporary file starts out empty, otherwise the existing file is first copied to this temporary file.
(quote from [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle/createWritable))
I managed to overlook this during manual testing because I was primarily using smaller files which are written in a single message. However in the case of larger files, which are written over the course of several messages (with an incrementing `offset`), this was causing us to erase the file on each write message. In effect, we'd only save the the last write …
> Fix large file corruption

- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/services/audit/makeEvent.ts
- packages/teleport/src/services/audit/types.ts
Fixes https://github.com/gravitational/teleport/issues/16973.
This commit eases the navigation through the audit log by not requiring a click on the `kube.request` event to see all details about it.
> Display `verb`, `request_path` & `response_code` in `kube.request` events

- packages/teleterm/src/ui/DocumentCluster/ClusterResources/useServerSideResources.ts
> [v11] Pass clusterUri rather than documentUri to retryWithRelogin

- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/services/audit/makeEvent.ts
- packages/teleport/src/services/audit/types.ts
> [v9] Display `verb`, `request_path` & `response_code` in `kube.request` events

- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/services/audit/makeEvent.ts
- packages/teleport/src/services/audit/types.ts
Backport #1384 to teleport-v10
> [v10] Display `verb`, `request_path` & `response_code` in `kube.request` events

- packages/teleport/src/Discover/Database/TestConnection/TestConnection.story.tsx
- packages/teleport/src/Discover/Database/TestConnection/TestConnection.tsx
- packages/teleport/src/Discover/Database/TestConnection/index.ts
- packages/teleport/src/Discover/Database/TestConnection/useTestConnection.ts
- packages/teleport/src/Discover/Kubernetes/TestConnection/TestConnection.story.tsx
- packages/teleport/src/Discover/Kubernetes/TestConnection/TestConnection.tsx
- packages/teleport/src/Discover/Kubernetes/TestConnection/useTestConnection.ts
- packages/teleport/src/Discover/Server/TestConnection/TestConnection.story.tsx
- packages/teleport/src/Discover/Server/TestConnection/TestConnection.tsx
- packages/teleport/src/Discover/Server/TestConnection/useTestConnection.ts
- packages/teleport/src/Discover/Shared/ConnectionDiagnostic/ConnectionDiagnosticResult.story.tsx
- packages/teleport/src/Discover/Shared/ConnectionDiagnostic/ConnectionDiagnosticResult.tsx
- packages/teleport/src/Discover/Shared/ConnectionDiagnostic/index.ts
- packages/teleport/src/Discover/Shared/ConnectionDiagnostic/useConnectionDiagnostic.ts
part of https://github.com/gravitational/teleport/issues/16858
- extract common logic used throughout all resource test connection screens 
- reorganized story
- refactored existing screens
- tentatively implement the database test connection screen (backend is still unfinished)
https://www.figma.com/file/8DQZl1mYUPLgvKgmA6zPOM/In-Progress-Work?node-id=1315%3A70746&t=MKwOH53cFBLIV3FK-0
> [Discover] Refactor TestConnection Screens

- packages/teleport/src/components/BannerList/useAlerts.tsx
- packages/teleport/src/services/alerts/alerts.tsx
This will partly fix https://github.com/gravitational/teleport/issues/17670
> We UI alert banner dismissal is currently bugged. After clicking the x button on the alert, it reappears whenever you switch to a different page (e.g. clicking over from Servers to Applications).
Previously:
https://user-images.githubusercontent.com/7922109/204788037-27040182-9a41-4d53-89e9-75f22c45084c.mp4
After:
https://user-images.githubusercontent.com/7922109/204788616-41978d79-12ce-4ad9-8b07-d1423f3d09c7.mp4
The `dismissedAlerts` state was not being updated when an alert is dismissed, so it wouldn't be filtered out the next time `useAlerts` was called (on a route change), so this changes that.
For some reason the state was using `DismissedAlert[]`, but `DismissedAlert` (now `DismissedAlerts`) is an object …
> Fix alerts from not disappearing on route changes

- packages/teleport/src/boot.tsx
The introduction of https://github.com/gravitational/webapps/pull/1361 caused our main production entry bundle (the JS the user loads when first opening teleport) to increase by 152 KiB, a 30% increase.
Before the PR:
After the PR:
This changes the code to only import the `telemetry-boot` file, which in turn includes 13 Telemetry packages, when needed (the user has set `enable-telemetry` to `true` in local storage and refreshed the page).
After this change:
This will also make the time to first render faster for those that have enabled telemetry, as the telemetry instantiation is no longer blocking React from rendering the app.
> Lazy load Telemetry only when needed

- packages/teleport/package.json
- yarn.lock
Fixes https://github.com/gravitational/teleport/issues/18784
A big highlight of xterm 5.0.0 is the update to underline rendering. Check it [here](https://github.com/xtermjs/xterm.js/releases/tag/5.0.0). 
Updated the package and the issue was resolved. Here is a before and after (4 on the left, 5 on the right)
All tests pass, manual testing shows no issues, and I don't believe any of the breaking changes affect us. Wouldn't mind a double check
> Update xterm to 5.0.0

- packages/teleterm/README.md
- packages/teleterm/electron-builder-config.js
> [v11] Connect: Tell fpm to not use symlinks when building the rpm package

- packages/teleport/src/components/BannerList/Banner.tsx
- packages/teleport/src/services/userEvent/userEvent.ts
Updates the alert field to match the grpc method/expected request on the API->Prehog side of the fence
`alertId -> alert`
Fixes the dropped field from event capture:
```
{"caller":"local/usagereporter.go:198","component":"usage-reporting","level":"warning","message":"Failed to submit batch of 2 usage events: invalid_argument: missing alert","timestamp":"2022-12-08T22:32:39Z"}
```
> update alert field on banner capture

- packages/design/src/Checkbox/Checkbox.story.tsx
- packages/design/src/Checkbox/Checkbox.tsx
- packages/design/src/Checkbox/index.ts
- packages/teleterm/src/services/tshd/createClient.ts
- packages/teleterm/src/services/tshd/fixtures/mocks.ts
- packages/teleterm/src/services/tshd/types.ts
- packages/teleterm/src/services/tshd/v1/service_pb.d.ts
- packages/teleterm/src/services/tshd/v1/service_pb.js
- packages/teleterm/src/ui/services/clusters/clustersService.ts
- packages/teleterm/src/ui/uri.ts
This PR is part of https://github.com/gravitational/teleport/issues/16647
`e` counterpart (where most of the changes are): https://github.com/gravitational/webapps.e/pull/424
`teleport` counterpart: https://github.com/gravitational/teleport/pull/18036
Adds the ability to specify which roles to tie to a resource access request.
- Slight color and text styling changes in order to use our `theme`.
- Arrow points right instead of up when the items are hidden, this is to remain consistent with how we have it elsewhere in the app (eg. sidebar nav)
> Allow for specifying roles when making Resource Access Requests

- packages/build/package.json
- packages/teleport/src/Console/Console.tsx
- packages/teleport/src/Console/consoleContext.tsx
- packages/teleport/src/Console/useOnExitConfirmation.test.ts
- packages/teleport/src/Console/useOnExitConfirmation.ts
- packages/teleport/src/Discover/Discover.test.tsx
- packages/teleport/src/Discover/Discover.tsx
- packages/teleport/src/Discover/Shared/SetupAccess/useUserTraits.test.tsx
- packages/teleport/src/Discover/Shared/SetupAccess/useUserTraits.ts
- packages/teleport/src/Discover/useDiscover.tsx
- packages/teleport/src/Login/useLogin.ts
- packages/teleport/src/Player/Player.tsx
- packages/teleport/src/TopBar/useTopBar.ts
- packages/teleport/src/WebSessionContext.tsx
- packages/teleport/src/components/Authenticated/Authenticated.tsx
- packages/teleport/src/services/api/api.js
- packages/teleport/src/services/localStorage/localStorage.ts
- packages/teleport/src/services/user/user.ts
- packages/teleport/src/services/websession/index.ts
- packages/teleport/src/services/websession/storeWebSession.ts
- packages/teleport/src/services/websession/test-utils.ts
- packages/teleport/src/services/websession/types.ts
- packages/teleport/src/services/websession/websession.ts
- packages/teleport/src/useWebSession.ts
- yarn.lock
This PR resolves https://github.com/gravitational/teleport-private/issues/158
Resolves a security concern due to using localStorage to store the session token. This is how it was initially but was changed to use localStorage in [this PR](https://github.com/gravitational/webapps/pull/215) due to a Firefox bug involving access request waiting rooms, this bug has been addressed in the `e` counterpart to this PR. 
TODO:
> Use sessionStorage for Authentication Bearer Token

- packages/teleterm/src/mainProcess/fixtures/mocks.ts
This unbreaks some Connect stories which depend on keyboard shortcuts config.
If we ever need to change the config in stories or tests, we should revisit the mock. But it might be enough to call the `set` method on the config service.
> Connect: Use default config in main process fixtures

- packages/teleport/src/lib/tdp/client.ts
- packages/teleport/src/lib/term/enums.ts
backports #1463 to teleport-v11
> [v11] Fix websocket close (#1463)

- packages/teleport/src/lib/tdp/sharedDirectoryManager.ts
It's still not entirely clear to me why this was only showing up with large zip files (whereas I wasn't able to induce it with merely large text files). However after making this change, previously problematic large zip files are being copied correctly. 
Generally it makes sense that these operations need to be `await`ed, to ensure that the write completes before another comes in, the file is closed, etc. When testing, I noticed that the way the zip files were becoming corrupted wasn't entirely consistent from run to run (i.e. one time byte 115 was incorrect, the next time it was written correctly). So I believe that by not `await`ing, I was creating a race condition that was for whatever reason more likely to be beaten by a big binary file like a zip.
Fixes …
> Fix large zip file sharing

- packages/teleport/src/lib/tdp/sharedDirectoryManager.ts
backports https://github.com/gravitational/webapps/pull/1471 to teleport-v10
> [v10] awaits the file write and close to avoid data corruption (#1471)

- packages/teleport/src/services/audit/makeEvent.ts
Includes the session id in the Session Uploaded display.  Currently if you search for a session id you won't get the uploaded which tells you the session is now available.
Before
After
> Include session id in Session Uploaded event display

- packages/design/src/ButtonIcon/ButtonIcon.jsx
- packages/shared/components/Notification/Notification.story.tsx
- packages/shared/components/Notification/Notification.tsx
I noticed that when the notification has a single line with no title, the text and the icon are misaligned.
before | after
--- | ---
To make sure I can fix this without breaking everything else, I added a story which shows each notification type.
While adding the story, I noticed that the types for the Notification component don't alert me when I forgot to add required props, so I fixed that too.
> Notifications: Add showcase story & fix icon alignment

- packages/teleterm/src/ui/ClusterConnect/ClusterAdd/ClusterAdd.story.tsx
- packages/teleterm/src/ui/ClusterConnect/ClusterLogin/ClusterLogin.story.tsx
- packages/teleterm/src/ui/ClusterLogout/ClusterLogout.story.tsx
- packages/teleterm/src/ui/DocumentsReopen/DocumentsReopen.story.tsx
- packages/teleterm/src/ui/ModalsHost/modals/UsageData/UsageData.story.tsx
- packages/teleterm/src/ui/services/modals/modalsService.ts
Originally I had these two commits on the branch where I'm working on symlinking tsh on macOS. I wanted to add a new modal, similar to how VSCode prompts you before actually executing osascript, but I found out you can have [a custom prompt for osascript](https://apple.stackexchange.com/a/303363/103152) so the additional modals are no longer necessary.
Still, I'm submitting a PR with small fixes to modals. When I was adding the new modals, I lacked a place where I can quickly look up how all the other modals look like, so I grouped them all together in the storybook and added some missing stories.
> Connect: Add missing modal stories, misc modal fixes

- packages/teleport/src/config.ts
- packages/teleport/src/services/auth/auth.test.ts
- packages/teleport/src/services/auth/auth.ts
- packages/teleport/src/services/websession/websession.ts
When https://github.com/gravitational/teleport/pull/19593 went in, it removed the deprecated(?) route to `webapi/sessions` in favor of `webapi/sessions/web` but the frontend was never updated since v5 to change this route. It looks like we were always calling to the same old route instead of the updated one. When the old route was removed, you can no longer login on the web ui. 
This change allows the login with the web ui again. I've checked around to find other instances and so far haven't found any but I may have missed something. Some sets of eyes and any historical data around this route would be great!
Teleport buddy: https://github.com/gravitational/teleport/pull/19892
> Update sessionPath value to new endpoint

- packages/teleport/src/config.ts
- packages/teleport/src/services/auth/auth.test.ts
- packages/teleport/src/services/auth/auth.ts
- packages/teleport/src/services/websession/websession.ts
> [v10] Update sessionPath value to new endpoint (#1486)

- packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabase.story.tsx
- packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabase.tsx
- packages/teleport/src/Discover/Database/CreateDatabase/useCreateDatabase.test.tsx
- packages/teleport/src/Discover/Database/CreateDatabase/useCreateDatabase.ts
- packages/teleport/src/Discover/Database/DownloadScript/DownloadScript.story.tsx
- packages/teleport/src/Discover/Database/DownloadScript/DownloadScript.tsx
- packages/teleport/src/Discover/Shared/ActionButtons.tsx
- packages/teleport/src/services/databases/databases.test.ts
- packages/teleport/src/services/databases/makeDatabase.ts
part of https://github.com/gravitational/teleport/issues/16858
- Fixes a bug where when we query for db service (no longer called atm), the labels return can be a `map[string]string OR []string`, so we just check if the label value is an array.
- Temporarily remove the service checker until bug is fixed: https://github.com/gravitational/teleport/issues/19919
- Because of no service checker which guaranteed that there was a active db server that can pick up the newly created database, we now leave it up to the user to add or skip installing the database service
- If user skipped the installing step, and there was no active db service, the user will have to restart the flow at this time
> [Discover] Temp remove db service checker

- packages/teleterm/package.json
- yarn.lock
11.1.5-dev.ravicious.1 was tested by me on macOS, Ubuntu and Fedora and on Windows by Michael.
There's no breaking changes which would affect us.
https://releases.electronjs.org/release/v22.0.0
> Update Electron to 22.0.0

- packages/teleport/src/Teleport.tsx
This would fix https://github.com/gravitational/teleport/issues/20044
The immediate rendering of the `Authenticated` component in OSS means that we don't have enough time to receive a token from other tabs on the `BroadcastChannel`, so when opening a new tab (for session playback) the tab becomes unauthenticated during the initial render.
By adding lazy loading, we can delay the rendering of `Authenticated` enough (by falling back to the `Suspense` component) for the token to be received and the tab to be authenticated during the initial render.
> [v11] Add lazy loading for session playback

- packages/teleport/src/Teleport.tsx
As desktop sessions also start in a new tab, we should lazy load them so there's time for the broadcast channel to receive a token.
Similar to #1502
> [v11] Add lazy loading for desktop sessions

- packages/design/src/StepSlider/StepSlider.tsx
- packages/teleport/src/Welcome/NewCredentials/NewCredentials.tsx
- packages/teleport/src/Welcome/NewCredentials/NewMfaDevice.tsx
- packages/teleport/src/Welcome/NewCredentials/NewPassword.tsx
- packages/teleport/src/Welcome/NewCredentials/Success.tsx
- packages/teleport/src/Welcome/useToken.ts
- packages/teleport/src/components/RecoveryCodes/RecoveryCodes.tsx
- packages/teleport/src/services/userEvent/types.ts
- packages/teleport/src/services/userEvent/userEvent.ts
supports https://github.com/gravitational/cloud/issues/2520
Part of a series of PRs to add the orange-* events belonging to phase 1 reporting
Removes one unused event
Adds mfaType & loginFlow to PreUserOnboardRegisterChallengeSubmitEvent
Moves the credential event to onSuccess
Adds the"PreUserCompleteGoToDashboardClickEvent
Adds "copy" and "paste" PreUserRecoveryCodes<_>ClickEvents
Removes deprecated/unused PreUserOnboardGetStartedClickEvent
> capture additional prehog events

- packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
When playing around with desktops, I noticed that even if I denied clipboard permissions at the browser level, the remote clipboard would still get synced to my local clipboard (but not the other way around). This fixes that, see the comment on `shouldTryClipboardRW`.
> Fix clipboard permissions apparent inconsistency

- packages/teleport/src/AppLauncher/AppLauncher.tsx
The new app access authentication workflow inadvertently preserves the URL encoded values present in the AWS role ARN, which are then passed directly to the webapi/sessions endpoint. As a result, Teleport RBAC doesn't properly match AWS role ARNs, as they contain (in particular) `/` characters encoded as `%2F`.
> [v10] Decode URL encoded values from AppLauncher's ARN.

- packages/teleport/src/AppLauncher/AppLauncher.tsx
The new app access authentication workflow inadvertently preserves the URL encoded values present in the AWS role ARN, which are then passed directly to the webapi/sessions endpoint. As a result, Teleport RBAC doesn't properly match AWS role ARNs, as they contain (in particular) `/` characters encoded as `%2F`.
> [v11] Decode URL encoded values from AppLauncher's ARN.

- packages/teleport/src/Audit/EventList/EventTypeCell.tsx
- packages/teleport/src/Audit/__snapshots__/Audit.story.test.tsx.snap
- packages/teleport/src/Audit/fixtures/index.ts
- packages/teleport/src/services/audit/makeEvent.ts
- packages/teleport/src/services/audit/types.ts
Backport https://github.com/gravitational/teleport/pull/20722 to v11.
This commit adds frontend support for displaying login rule audit events.
> [v11] feat: login rule audit events

- packages/teleport/src/AppLauncher/AppLauncher.test.tsx
The AppLauncher test added into the `teleport` repo has been migrated here as well.
> [v11] Migrate AppLauncher tests into webapps.

- packages/teleport/src/AppLauncher/AppLauncher.test.tsx
The AppLauncher test added into the `teleport` repo has been migrated here as well.
> [v10] Migrate AppLauncher tests into webapps.
